@pangea_test @AEAZ-1480 @AEAZ-3178
Feature: PlanCnsTlaneItem AEAZ-1480 @AEAZ-3178

  @Scenario1
  Scenario: Plant to Plant Transfer and subcon Vendor to Plant and Vendor to Plant

    Given I import "/plan/cns_tlane_control" by keyFields "sequenceNumber,tlaneName"
      | sequenceNumber | tlaneName   | validFrom | validTo  | originLocation   | destinationLocation | mode | leadTime | triangulationDetail | processTypeId | sourceSystemCriticalParameters | criticalParameter1Table | criticalParameter1Field  | criticalParameter1Low | criticalParameter1Operator | criticalParameter1IE | criticalParameter2Table | criticalParameter2Field | criticalParameter2Low | criticalParameter2High | criticalParameter2Operator | criticalParameter2IE | criticalParameter3Table | criticalParameter3Field | criticalParameter3Low | criticalParameter3High | criticalParameter3Operator | criticalParameter3IE | criticalParameter4Table | criticalParameter4Field | criticalParameter4Low | criticalParameter4High | criticalParameter4Operator | criticalParameter4IE | criticalParameter5Table | criticalParameter5Field | criticalParameter5Low | criticalParameter5High | criticalParameter5Operator | criticalParameter5IE | criticalParameter6Table | criticalParameter6Field     | criticalParameter6Low | criticalParameter6High | criticalParameter6Operator | criticalParameter6IE | criticalParameter7Table | criticalParameter7Field | criticalParameter7Low | criticalParameter7High | criticalParameter7Operator | criticalParameter7IE | criticalParameter8Table | criticalParameter8Field | criticalParameter8Low | criticalParameter8High | criticalParameter8Operator | criticalParameter8IE | criticalParameter9Table | criticalParameter9Field | criticalParameter9Low | criticalParameter9High | criticalParameter9Operator | criticalParameter9IE | criticalParameter10Table | criticalParameter10Field | criticalParameter10Low | criticalParameter10High | criticalParameter10Operator | criticalParameter10IE |
      | 2              | CO01toPE01  | 101018    | 12319999 | CONS_LATAM_CO01  | CONS_LATAM_PE01     | Ship | 28       | No                  | 1             | CONS_LATAM                     | cns_prod_loc_attrib     | primarySupplierPlantCode | CO01                  | =                          | I                    | material_plant          | localPlant              | PE01                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType | 44                    |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |
      | 3              | AR01toAR02  | 101018    | 12312018 | CONS_LATAM_AR01  | CONS_LATAM_AR02     | Ship | 1        | No                  | 1             | CONS_LATAM                     | cns_prod_loc_attrib     | primarySupplierPlantCode | AR01                  | =                          | I                    | material_plant          | localPlant              | AR02                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType | 90                    |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |
      | 26             | 15574toCO01 | 101018    | 12319999 | CONS_LATAM_15574 | CONS_LATAM_CO01     | Ship | 28       | No                  | 1             | CONS_LATAM                     | source_list             | localVendorAccountNumber | 15574                 | =                          | I                    | material_plant          | localPlant              | CO01                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType | 44                    |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |
      | 27             | 50161toCO01 | 101018    | 12319999 | CONS_LATAM_50161 | CONS_LATAM_CO01     | Ship | 28       | No                  | 1             | CONS_LATAM                     | source_list             | localVendorAccountNumber | 50161                 | =                          | I                    | material_plant          | localPlant              | CO01                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType |                       |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |
      #Capture the scenario where "cns_spl_pln_loc-vendorOrCustomer) <> V ".
      | 33             | 33333toCO01 | 101018    | 12319999 | CONS_LATAM_33333 | CONS_LATAM_CO01     | Ship | 28       | No                  | 1             | CONS_LATAM                     | source_list             | localVendorAccountNumber | 33333                 | =                          | I                    | material_plant          | localPlant              | CO01                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType |                       |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |
      #Capture scenario "If (material_global_v1-primaryPlanningCode) not equal to (material_global_v1-MaterialNumber)".
      | 44             | CO02toPE01  | 101018    | 12319999 | CONS_LATAM_CO02  | CONS_LATAM_PE01     | Ship | 28       | No                  | 1             | CONS_LATAM                     | cns_prod_loc_attrib     | primarySupplierPlantCode | CO02                  | =                          | I                    | material_plant          | localPlant              | PE01                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType | 50                    |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |
      #Capture scenario where "(cns_material_plan_status-spRelevant) <> X and (cns_material_plan_status_v1-noPlanRelevant) <> X".
      | 55             | CO03toPE01  | 101018    | 12319999 | CONS_LATAM_CO03  | CONS_LATAM_PE01     | Ship | 28       | No                  | 1             | CONS_LATAM                     | cns_prod_loc_attrib     | primarySupplierPlantCode | CO03                  | =                          | I                    | material_plant          | localPlant              | PE01                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType | 55                    |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |
      #Capture "(cns_material_plan_status-spRelevant) <> X" when Vendor is supplying to Plant (i.e in rule N2 scenario 2).
      | 66             | 66666toCO01 | 101018    | 12319999 | CONS_LATAM_66666 | CONS_LATAM_CO01     | Ship | 28       | No                  | 1             | CONS_LATAM                     | source_list             | localVendorAccountNumber | 66666                 | =                          | I                    | material_plant          | localPlant              | CO01                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType | 66                    |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |
      #material_plant-V1-localMaterialNumber not equal cns_materia_plan_status-localmaterial
      | 77             | 77777toCO01 | 101018    | 12319999 | CONS_LATAM_77777 | CONS_LATAM_CO01     | Ship | 28       | No                  | 1             | CONS_LATAM                     | source_list             | localVendorAccountNumber | 77777                 | =                          | I                    | material_plant          | localPlant              | CO01                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType | 77                    |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |
      #N1 can't find in table cns_spl_pln_loc
      | 81             | CO04toCO01  | 101018    | 12319999 | CONS_LATAM_CO04  | CONS_LATAM_CO01     | Ship | 28       | No                  | 1             | CONS_LATAM                     | source_list             | localVendorAccountNumber | CO04                  | =                          | I                    | material_plant          | localPlant              | CO01                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType | 77                    |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |
      #N1 cns_spl_pln_loc-sourceSystem != cns_lane_control-sourceSystemCriticalParameters
      | 82             | CO05toCO01  | 101018    | 12319999 | CONS_LATAM_CO05  | CONS_LATAM_CO01     | Ship | 28       | No                  | 1             | CONS_LATAM                     | source_list             | localVendorAccountNumber | CO05                  | =                          | I                    | material_plant          | localPlant              | CO01                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType | 77                    |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |
      #N1 cns_spl_pln_loc-localNumber != cns_lane_control-"origin location"
      | 83             | CO06toCO16  | 101018    | 12319999 | CONS_LATAM_CO06  | CONS_LATAM_CO16     | Ship | 28       | No                  | 1             | CONS_LATAM                     | source_list             | localVendorAccountNumber | CO06                  | =                          | I                    | material_plant          | localPlant              | CO01                  |                        | =                          | I                    | material_plant          | localProcurementType    | F                     |                        | =                          | I                    | material_plant          | localMrpType            | X0                    |                        | =                          | I                    | material_plant          | localMrpController      | 999                   |                        | =                          | E                    | material_plant          | localSpecialProcurementType | 77                    |                        | =                          | I                    | material_plant          | localPlantStatus        | 08,11,13              |                        | =                          | I                    |                         |                         |                       |                        |                            |                      |                         |                         |                       |                        |                            |                      |                          |                          |                        |                         |                             |                       |


    And I wait "/plan/cns_tlane_control" Async Queue complete

    And I import "/plan/cns_spl_pln_loc" by keyFields "localName,localNumber,sourceSystem"
      | sourceSystem   | localPlant | localCountry | localCurrency | localName                           | localNumber | localRegion | pLanlocTypeDesc    | pLanlocTypeId | specLocAtt1 | specLocAtt2 | specLocAtt3 | specLocAttDesc1 | specLocAttDesc2 | specLocAttDesc3 | vendorOrCustomer |
      | CONS_LATAM     | CO01       | CO           | COP           | ASPRILLA ORTIZ FABIO                | 15574       | 103         | Mfg Plant Copacker | SUBCON        |             |             |             |                 |                 |                 | V                |
      | CONS_LATAM     |            | MX           | MXN           | AVP MAQUILA DE MEXICO S DE RL DE CV | 50161       | 103         | VENDOR             | PureBuy       |             |             |             |                 |                 |                 | V                |
      | CONS_LATAM     |            | MX           | MXN           | AVP MAQUILA DE MEXICO S DE RL DE CV | 33333       | 103         | VENDOR             | PureBuy       |             |             |             |                 |                 |                 |                  |
      | CONS_LATAM     | CO02       | CO           | COP           | ASPRILLA ORTIZ FABIO                | 15573       | 103         | Mfg Plant Copacker | SUBCON        |             |             |             |                 |                 |                 | V                |
      | CONS_LATAM     | CO03       | CO           | COP           | ASPRILLA ORTIZ FABIO                | 95555       | 103         | Mfg Plant Copacker | SUBCON        |             |             |             |                 |                 |                 | V                |
      | CONS_LATAM     |            | MX           | MXN           | AVP MAQUILA DE MEXICO S DE RL DE CV | 66666       | 103         | VENDOR             | PureBuy       |             |             |             |                 |                 |                 | V                |
      | CONS_LATAM     |            | MX           | MXN           | AVP MAQUILA DE MEXICO S DE RL DE CV | 77777       | 103         | VENDOR             | PureBuy       |             |             |             |                 |                 |                 | V                |

    And I wait "/plan/cns_spl_pln_loc" Async Queue complete

    And I import "/edm/plant_v1" by keyFields "localPlant,sourceSystem"
      | localAbcIndicator | localBaseQuantity | localBatchManagementRequirementIndicator | localCheckingGroupForAvailabilityCheck | localComponentScrap | localComponentScrapInPercent | localConsumptionMode | localConsumptionPeriodBackward | localConsumptionPeriodForward | localCriticalPart | localDeletionFlagPlant | localDependentRequirements | localFixedLotSize | localGoodsReceiptProcessingTimeInDays | localInHouseProcessingTime | localLotSize | localMaterialNumber | localMaximumLotSize | localMaximumStockLevel | localMinimumLotSize | localMinimumSafetyStock | localMrpController | localMrpType | localPlannedDeliveryTimeInDays | localPlanningStrategyGroup | localPlanningTimeFence | localPlant | localPlantStatus | localPostToInspStk | localPostToInspectionStock | localProcurementType | localProductionSupervisor | localProductionUnit | localRoundingValueForPoq | localSafetyStock | localSafetyTime | localSafetyTimeIndicator | localSpecialProcurementType | materialNumber | plant | plantStatus | sourceSystem |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            | 2                    | 45                             | 7                             |                   |                        | 1                          | 0                 | 15                                    | 0                          | MB           | 88382               | 0                   | 0                      | 1                   | 0                       | U01                | X0           | 0                              | 40                         | 0                      | PE01       | 11               |                    |                            | F                    |                           |                     | 1                        | 0                | 0               |                          | 44                          | 88382          | UY07  |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            |                      | 0                              | 0                             |                   |                        |                            | 0                 | 0                                     | 0                          |              | 69056               | 0                   | 0                      | 0                   | 0                       | U01                | X0           | 0                              |                            | 0                      | AR02       | 13               |                    |                            | F                    |                           |                     | 0                        | 0                | 0               |                          | 90                          | 69056          |       |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            |                      | 0                              | 0                             |                   |                        |                            | 0                 | 0                                     | 0                          |              | 93937               | 0                   | 0                      | 0                   | 0                       | U01                | X0           | 0                              |                            | 0                      | AR01       | 13               |                    |                            | F                    |                           |                     | 0                        | 0                | 0               |                          | 30                          | 93937          |       |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            |                      | 0                              | 0                             |                   |                        |                            | 0                 | 0                                     | 0                          |              | 93616               | 0                   | 0                      | 0                   | 0                       | U01                | X0           | 0                              |                            | 0                      | CO01       | 13               |                    |                            | F                    |                           |                     | 0                        | 0                | 0               |                          |                             | 93616          |       |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            | 2                    | 45                             | 7                             |                   |                        | 1                          | 0                 | 15                                    | 0                          | MB           | 88382               | 0                   | 0                      | 1                   | 0                       | U01                | X0           | 0                              | 40                         | 0                      | PE01       | 11               |                    |                            | F                    |                           |                     | 1                        | 0                | 0               |                          | 50                          | 88382          | UY07  |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            |                      | 0                              | 0                             |                   |                        |                            | 0                 | 0                                     | 0                          |              | 93444               | 0                   | 0                      | 0                   | 0                       | U01                | X0           | 0                              |                            | 0                      | CO02       | 13               |                    |                            | F                    |                           |                     | 0                        | 0                | 0               |                          |                             | 93444          |       |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            | 2                    | 45                             | 7                             |                   |                        | 1                          | 0                 | 15                                    | 0                          | MB           | 95555               | 0                   | 0                      | 1                   | 0                       | U01                | X0           | 0                              | 40                         | 0                      | CO03       | 11               |                    |                            | F                    |                           |                     | 1                        | 0                | 0               |                          | 55                          | 95555          | UY07  |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            |                      | 0                              | 0                             |                   |                        |                            | 0                 | 0                                     | 0                          |              | 96666               | 0                   | 0                      | 0                   | 0                       | U01                | X0           | 0                              |                            | 0                      | CO01       | 13               |                    |                            | F                    |                           |                     | 0                        | 0                | 0               |                          | 66                          | 96666          |       |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            |                      | 0                              | 0                             |                   |                        |                            | 0                 | 0                                     | 0                          |              | 97777               | 0                   | 0                      | 0                   | 0                       | U01                | X0           | 0                              |                            | 0                      | CO01       | 13               |                    |                            | F                    |                           |                     | 0                        | 0                | 0               |                          | 77                          | 97777          |       |             | CONS_LATAM   |

    And I wait "/edm/plant_v1" Async Queue complete

    And I import "/edm/material_global_v1" by keyFields "localMaterialNumber,sourceSystem"
      | baseUom | batchManageIndicator | brand | category | division | flagForDeletion | form | franchise | globalBusinessUnit | globalDpParentCode | localBaseUom | localDpParentCode | localManufacturingTechnology | localMaterialGroup | localMaterialNumber | localMaterialType | localRefDescription           | manufacturingTechnology | materialGroup | materialNumber | materialStatus | materialType | minRemShelfLife | parentCode | primaryPlanningCode | productFamily | refDescription | sourceSystem | subBrand | totalShelfLife |
      |         |                      |       |          |          |                 |      |           |                    |                    | EA           |                   |                              |                    | 88382               | CBAU              | EMS - Indisponivel para LATAM |                         |               | 88382          | 11             |              | 0               |            | 88382               |               |                | CONS_LATAM   |          | 0              |
      |         |                      |       |          |          |                 |      |           |                    |                    | EA           |                   |                              |                    | 69056               | CBAU              | EMS - Indisponivel para LATAM |                         |               | 69056          | 13             |              | 0               |            | 69056               |               |                | CONS_LATAM   |          | 0              |
      |         |                      |       |          |          |                 |      |           |                    |                    | EA           |                   |                              |                    | 93937               | CBAU              | EMS - Indisponivel para LATAM |                         |               | 93937          | 11             |              | 0               |            | 93937               |               |                | CONS_LATAM   |          | 0              |
      |         |                      |       |          |          |                 |      |           |                    |                    | EA           |                   |                              |                    | 93616               | CBAU              | EMS - Indisponivel para LATAM |                         |               | 93616          | 13             |              | 0               |            |                     |               |                | CONS_LATAM   |          | 0              |
      |         |                      |       |          |          |                 |      |           |                    |                    | EA           |                   |                              |                    | 93444               | CBAU              | EMS - Indisponivel para LATAM |                         |               | 93444          | 11             |              | 0               |            | 93445               |               |                | CONS_LATAM   |          | 0              |
      |         |                      |       |          |          |                 |      |           |                    |                    | EA           |                   |                              |                    | 95555               | CBAU              | EMS - Indisponivel para LATAM |                         |               | 95555          | 11             |              | 0               |            | 95555               |               |                | CONS_LATAM   |          | 0              |
      |         |                      |       |          |          |                 |      |           |                    |                    | EA           |                   |                              |                    | 96666               | CBAU              | EMS - Indisponivel para LATAM |                         |               | 96666          | 13             |              | 0               |            |                     |               |                | CONS_LATAM   |          | 0              |
      |         |                      |       |          |          |                 |      |           |                    |                    | EA           |                   |                              |                    | 97777               | CBAU              | EMS - Indisponivel para LATAM |                         |               | 97777          | 13             |              | 0               |            |                     |               |                | CONS_LATAM   |          | 0              |

    And I wait "/edm/material_global_v1" Async Queue complete

    And I import "/edm/material_plant_v1" by keyFields "localMaterialNumber,localPlant,sourceSystem"
      | localAbcIndicator | localBaseQuantity | localBatchManagementRequirementIndicator | localCheckingGroupForAvailabilityCheck | localComponentScrap | localComponentScrapInPercent | localConsumptionMode | localConsumptionPeriodBackward | localConsumptionPeriodForward | localCriticalPart | localDeletionFlagPlant | localDependentRequirements | localFixedLotSize | localGoodsReceiptProcessingTimeInDays | localInHouseProcessingTime | localLotSize | localMaximumLotSize | localMaximumStockLevel | localMinimumLotSize | localMinimumSafetyStock | localMrpController | localMrpType | localPlannedDeliveryTimeInDays | localPlanningStrategyGroup | localPlanningTimeFence | localPlant | localPlantStatus | localPostToInspStk | localPostToInspectionStock | localProcurementType | localProductionSupervisor | localProductionUnit | localRoundingValueForPoq | localSafetyStock | localSafetyTime | localSafetyTimeIndicator | localSpecialProcurementType | localMaterialNumber | materialNumber | plant | plantStatus | sourceSystem |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            | 2                    | 45                             | 7                             |                   |                        | 1                          | 0                 | 15                                    | 0                          | MB           | 0                   | 0                      | 1                   | 0                       | U01                | X0           | 0                              | 40                         | 0                      | PE01       | 11               |                    |                            | F                    |                           |                     | 1                        | 0                | 0               |                          | 44                          | 88382               | 88382          | UY07  |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            |                      | 0                              | 0                             |                   |                        |                            | 0                 | 0                                     | 0                          |              | 0                   | 0                      | 0                   | 0                       | U01                | X0           | 0                              |                            | 0                      | AR02       | 13               |                    |                            | F                    |                           |                     | 0                        | 0                | 0               |                          | 90                          | 69056               | 69056          |       |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            |                      | 0                              | 0                             |                   |                        |                            | 0                 | 0                                     | 0                          |              | 0                   | 0                      | 0                   | 0                       | U01                | X0           | 0                              |                            | 0                      | CO01       | 13               |                    |                            | F                    |                           |                     | 0                        | 0                | 0               |                          | 44                          | 93937               | 93937          |       |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            |                      | 0                              | 0                             |                   |                        |                            | 0                 | 0                                     | 0                          |              | 0                   | 0                      | 0                   | 0                       | U01                | X0           | 0                              |                            | 0                      | CO01       | 13               |                    |                            | F                    |                           |                     | 0                        | 0                | 0               |                          |                             | 93616               | 93616          |       |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            | 2                    | 45                             | 7                             |                   |                        | 1                          | 0                 | 15                                    | 0                          | MB           | 0                   | 0                      | 1                   | 0                       | U01                | X0           | 0                              | 40                         | 0                      | PE01       | 11               |                    |                            | F                    |                           |                     | 1                        | 0                | 0               |                          | 50                          | 93444               | 93444          | UY07  |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            | 2                    | 45                             | 7                             |                   |                        | 1                          | 0                 | 15                                    | 0                          | MB           | 0                   | 0                      | 1                   | 0                       | U01                | X0           | 0                              | 40                         | 0                      | PE01       | 11               |                    |                            | F                    |                           |                     | 1                        | 0                | 0               |                          | 55                          | 95555               | 95555          | UY07  |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            |                      | 0                              | 0                             |                   |                        |                            | 0                 | 0                                     | 0                          |              | 0                   | 0                      | 0                   | 0                       | U01                | X0           | 0                              |                            | 0                      | CO01       | 13               |                    |                            | F                    |                           |                     | 0                        | 0                | 0               |                          | 66                          | 96666               | 96666          |       |             | CONS_LATAM   |
      |                   | 0                 | X                                        | 2                                      | 0                   | 0                            |                      | 0                              | 0                             |                   |                        |                            | 0                 | 0                                     | 0                          |              | 0                   | 0                      | 0                   | 0                       | U01                | X0           | 0                              |                            | 0                      | CO01       | 13               |                    |                            | F                    |                           |                     | 0                        | 0                | 0               |                          | 77                          | 97777               | 97777          |       |             | CONS_LATAM   |

    And I wait "/edm/material_plant_v1" Async Queue complete

    And I import "/plan/cns_prod_loc_attrib" by keyFields "localMaterialNumber,localPlant,sourceSystem"
      | localMaterialNumber | sourceSystem | localPlant | minMinShelfLife | minShelfLife | schAttrbDesc1 | schAttrbDesc2 | schAttrbDesc3 | schdAttrbName1 | schdAttrbName2 | schdAttrbName3 | supplyGroup | primarySupplierPlantCode |
      | 88382               | CONS_LATAM   | 50161      | 90              | 180          |               |               |               |                |                |                | LA_SG_34    | CO01                     |
      | 69056               | CONS_LATAM   | 50161      | 90              | 180          |               |               |               |                |                |                | LA_SG_34    | AR01                     |
      | 93937               | CONS_LATAM   | 50161      | 90              | 180          |               |               |               |                |                |                | LA_SG_34    |                          |
      | 93616               | CONS_LATAM   | 50161      | 90              | 180          |               |               |               |                |                |                | LA_SG_34    |                          |
      | 33631               | CONS_LATAM   | 33333      | 90              | 180          |               |               |               |                |                |                | LA_SG_34    |                          |
      | 93444               | CONS_LATAM   | 50161      | 90              | 180          |               |               |               |                |                |                | LA_SG_34    | CO02                     |
      | 95555               | CONS_LATAM   | 50161      | 90              | 180          |               |               |               |                |                |                | LA_SG_34    | CO03                     |

    And I wait "/plan/cns_prod_loc_attrib" Async Queue complete

    And I import "/plan/cns_material_plan_status" by keyFields "localMaterialNumber,localPlant,sourceSystem"
      | localMaterialNumber | sourceSystem | localPlant | active | dpRelevant | localParentCode    | materialNumber | noPlanRelevant | parentActive | ppc   | spRelevant |
      | 88382               | CONS_LATAM   | PE01       | X      | X          | 178962124094540000 | 88382          |                | X            | 88382 | X          |
      | 69056               | CONS_LATAM   | AR02       | X      | X          | 178962124094540000 | 69056          |                | X            | 69056 | X          |
      | 93937               | CONS_LATAM   | CO01       | X      | X          | 178962124094540000 | 93937          |                | X            | 93937 | X          |
      | 93616               | CONS_LATAM   | CO01       | X      | X          | 178962124094540000 | 93616          |                | X            |       | X          |
      | 93444               | CONS_LATAM   | PE01       | X      | X          | 178962124094540000 | 93444          |                | X            | 93444 | X          |
      | 95555               | CONS_LATAM   | PE01       | X      | X          | 178962124094540000 | 95555          |                | X            | 93444 |            |
      | 96666               | CONS_LATAM   | CO01       | X      | X          | 178962124094540000 | 96666          |                | X            |       |            |

    And I wait "/plan/cns_material_plan_status" Async Queue complete

    And I import "/edm/source_list_v1" by keyFields "localMaterialNumber,localPlant,sourceSystem"
      | localMaterialNumber | sourceSystem | localPlant | localAgreementItem | localAgreementNumber | localBlockedSourceofSupply | localCategoryofSourceListRecord | localDateonWhichRecordWasCreated | localFixedOutlinePurchaseAgreementItem | localFixedvendor | localMaterialNumberCorrespondingtoManufacturerPartNumber | localNameofPersonwhoCreatedtheObject | localNumberofSourceListRecord | localPlantfromWhichMaterialisProcured | localPurchasingDocumentCategory | localPurchasingOrganization | localSourceListRecordValidFrom | localSourceListRecordValidTo | localSourceListUsageinMaterialsPlanning | localVendorAccountNumber |
      | 93937               | CONS_LATAM   | CO01       | 0                  |                      |                            | 7                               | 20030306                         |                                        |                  |                                                          | CCASTRO1                             | 4                             | CO01                                  |                                 | CO00                        | 20030206                       | 29991231                     |                                         | 15574                    |
      | 93616               | CONS_LATAM   | CO01       | 0                  |                      |                            | 7                               | 20020522                         |                                        |                  |                                                          | CARGA03                              | 2                             | CO01                                  |                                 | CO00                        | 20020301                       | 99991231                     |                                         | 50161                    |

    And I wait "/edm/source_list_v1" Async Queue complete

    When I submit task with xml file "xml/plan/PlanCnsTlaneItem.xml" and execute file "jar/pangea-view.jar"

    And wait 10000 millisecond

    Then I check region data "/plan/cns_tlane_item" by keyFields "sequenceNumber,tlaneName,materialNumber"
      | sequenceNumber | tlaneName   | materialNumber | validFrom | validTo  | originLocation   | destinationLocation | mode | leadTime | processTypeId           |
      | 2              | CO01toPE01  | 88382          | 101018    | 12319999 | CONS_LATAM_CO01  | CONS_LATAM_PE01     | Ship | 28       | InternalTransport       |
      | 3              | AR01toAR02  | 69056          | 101018    | 12312018 | CONS_LATAM_AR01  | CONS_LATAM_AR02     | Ship | 1        | InternalTransport       |
      | 26             | 15574toCO01 | 93937          | 101018    | 12319999 | CONS_LATAM_15574 | CONS_LATAM_CO01     | Ship | 28       | SubcontractingTransport |
      | 27             | 50161toCO01 | 93616          | 101018    | 12319999 | CONS_LATAM_50161 | CONS_LATAM_CO01     | Ship | 28       | VendorTransport         |


    Then I check region data "/plan/edm_failed_data" by keyFields "functionalArea,interfaceID,errorCode,sourceSystem,key1,key2,key3,key4,key5"
      | functionalArea | interfaceID      | errorCode | sourceSystem | businessArea | key1 | key2        | key3 | key4 | key5 | errorValue |
      | SP             | PlanCnsTlaneItem |           |              |              | 33   | 33333toCO01 |      |      |      |            |
      | SP             | PlanCnsTlaneItem |           |              |              | 81   | CO04toCO01  |      |      |      |            |
      | SP             | PlanCnsTlaneItem |           |              |              | 82   | CO05toCO01  |      |      |      |            |
      | SP             | PlanCnsTlaneItem |           |              |              | 83   | CO06toCO16  |      |      |      |            |

  Scenario: delete all test data

    Then I delete the test data

    And I will remove all data with region "/plan/cns_tlane_item"

    And I will remove all data with region "/plan/edm_failed_data"


