@pangea_test @AEAZ-3678
Feature: EDMInventoryStock AEAZ-3678
    #1.get sourceSystem from source_system_v1 (rule T1)
    #2.Join (MARC-MATNR) = (MCHB-MATNR) and (MARC-WERKS) = (MCHB-WERKS) (rule N1)
    #3.Join (MARC-MATNR) = (MSLB-MATNR) and (MARC-WERKS) = (MSLB-WERKS) (rule N2)
    #4.Join (MARC-MATNR) = (MKOL-MATNR) and (MARC-WERKS) = (MKOL-WERKS) (rule N3)
    #5.Join (MARC-MATNR) = (MARD-MATNR) and (MARC-WERKS) = (MARD-WERKS) (rule N4)
    #6.If no record is found in MCHB or MSLB or MKOL or MARD, still there needs to be an output record with blank values for attributes from them;
#  @Scenario1
#  Scenario:
#      Given I import "/project_one/marc" by keyFields "mandt,matnr,werks"
#      | abcin | abfac | ahdis | altsl | aplal | apokz | atpkz | auftl | ausdt | ausme | ausss | autru | awsls | basmg | bearz | beskz | bstfe | bstma | bstmi | bstrf | bwesb | bwscl | bwtty | casnr | ccfix | compl | consProcg | convt | copam | cuobj | cuobv | diber | disgr | disls | dismm | dispo | dispr | dplfs | dplho | dplpu | dzeit | eisbe | eislo | ekgrp | eprio | expme | fabkz | fevor | ffrei | fhori | fixls | fprfm | frtme | fvidk | fxhor | fxpru | giPrTime | glgmg | gpmkz | gpnum | herbl | herkl | herkr | indus | insmk | itark | iuidRelevant | iuidType | kausf | kautb | kordb | kzagl | kzaus | kzbed | kzdie | kzdkz | kzech | kzkfk | kzkri | kzkup | kzppv | kzpro | kzpsp | ladgr | lagpr | lfgja | lfmon | lfrhy | lgfsb | lgpro | lgrad | lizyk | loggr | losfx | losgr | ltinc | lvorm | lzeih | maabc | mabst | mandt | matgr |         matnr     | maxls | maxlz | maxTroc | mcrue | mdach | megru | mfrgr | minbe | minls | minTroc | miskz | mmsta |   mmstd  | mogru | mownr | mpdau | mrppp | mtver | mtvfp | multipleEkgrp | ncost | nfmat | nkmpr | objid | ocmpf | otype | periv | perkz | pfrei | plifz | plnnr | plnty | plvar |  prctr  | prefe | prenc | prend | prene | preng | preno | prfrq |  pstat | qmata | qmatv | qssys | quazt | qzgtp | rdprf | refSchema | resvp | rgekz | rotationDate | ruezt | rwpro | sauft | sbdkz | schgt | sernp | servg | sfcpf | sfepr | shflg | shpro | shzet | sobsk | sobsl | sproz | ssqss | stawn | stdpd | steuc | stlal | stlan | strgr | takzt | targetStock | trame | tranz | uchkz | ucmat | ueetk | ueeto | uidIea | umlmc | umrsl | uneto | uomgr | usequ | vbamg | vbeaz | verkz | vint1 | vint2 | vkglg | vktrw | vkumc | vrbdt | vrbfk | vrbmt | vrbwk | vrmod | vrvez | vsorForkDir | vsorLaneNum | vsorPalVend | vsorPkgrp | vspvb | vzusl | webaz | werks | wstgh | wzeit | xchar | xchpf | xmcng | zdtalancprev | zdtalancreal | zindnbnp |
#      |	  C   |	  0	  |       |       |       |       |       |       |   0	  |       |   0	  |   X	  |Z00001 |	  0	  |    0  |	  F   |	  0	  |   0	  | 20000 |   0	  |   0	  |       |       |       |       |   0	  |	          |       | 	  |	  0   |	  0   |	 	  |       |   MB  |	  ND  |  C52  |	 	  |       |	   0  |	      |   0   |	  0   |   0   |	 C23  |	 	  |	 	  | 	  |       |       |    0  |   0   |       |       |  	  |	  0	  |	      |     0    |	 0   |	 	 |	 	 |	 	 |	 	 |	 	 |	     |       |       |              |          |   0   |   X   |   X   |	   |       |       |       |    X  |	   | 	   |       |       |       |       |       |       |       |  2006 |   8   | 	   |       |  CO02 |  94   |	   |       |   0   |  1000 |   0   |	   |	   | 	   |   0   |  120  |	   | 000000000000132288|   0   |   0   |	0    |	 	 |	 	 |       |       |	 0	 |   0   |	  0    |	   |   8   | 20060831 |	 	  |	      |   0	  |	 	  |       |   2   |               |       |       |   0   |   0   |	 	  |	 	  |       |   W   |	 	  |   0   |	 	  | 	  |       |21110813	| 	 	|       |   0   |	 	|   0	|  	    |   0   |EDPLSQBG|	 21	 |   X	 |	     |   0   |	CQF	 |       |           |	 0	 |   2   |	 	        |   0	| 	 	|       |   2   |	 	| 	 	| 	 	| 	 	|       |       |       |   0   |	 	|       | 	0	|   5	|  	 	| 	 	| 	 	|       |       |       |   0   |	   0      |	  0   |	  0   |	      | 	  |	 	  |   0   |	 	   |   0   |       |   0   |	   |	   |   0   |   0   |	   |   45  |   7   |   0   |    0  |   0   |	0  |   0   | 	   |       |   2   |   0   |             |	 	 	   |             |           |       |   0   |	 5   |	CO01 |	 0   |	 0   |	 X   |	 X   |	 	 |       0      |	    0      |	 	  |
#      |	  C   |	  0	  |       |       |       |       |       |       |   0	  |       |   0	  |   X	  |Z00001 |	  0	  |    0  |	  F   |	  0	  |   0	  | 20000 |   0	  |   0	  |       |       |       |       |   0	  |	          |       | 	  |	  0   |	  0   |	 	  |       |   MB  |	  ND  |  C52  |	 	  |       |	   0  |	      |   0   |	  0   |   0   |	 C23  |	 	  |	 	  | 	  |       |       |    0  |   0   |       |       |  	  |	  0	  |	      |     0    |	 0   |	 	 |	 	 |	 	 |	 	 |	 	 |	     |       |       |              |          |   0   |   X   |   X   |	   |       |       |       |    X  |	   | 	   |       |       |       |       |       |       |       |  2006 |   8   | 	   |       |  CO02 |  94   |	   |       |   0   |  1000 |   0   |	   |	   | 	   |   0   |  120  |	   | 000000000000132289|   0   |   0   |	0    |	 	 |	 	 |       |       |	 0	 |   0   |	  0    |	   |   8   | 20060831 |	 	  |	      |   0	  |	 	  |       |   2   |               |       |       |   0   |   0   |	 	  |	 	  |       |   W   |	 	  |   0   |	 	  | 	  |       |21110813	| 	 	|       |   0   |	 	|   0	|  	    |   0   |EDPLSQBG|	 21	 |   X	 |	     |   0   |	CQF	 |       |           |	 0	 |   2   |	 	        |   0	| 	 	|       |   2   |	 	| 	 	| 	 	| 	 	|       |       |       |   0   |	 	|       | 	0	|   5	|  	 	| 	 	| 	 	|       |       |       |   0   |	   0      |	  0   |	  0   |	      | 	  |	 	  |   0   |	 	   |   0   |       |   0   |	   |	   |   0   |   0   |	   |   45  |   7   |   0   |    0  |   0   |	0  |   0   | 	   |       |   2   |   0   |             |	 	 	   |             |           |       |   0   |	 5   |	CO01 |	 0   |	 0   |	 X   |	 X   |	 	 |       0      |	    0      |	 	  |
#
#    And I wait "/project_one/marc" Async Queue complete
#
#    Given I import "/edm/source_system_v1" by keyFields "localSourceSystem"
#      | localSourceSystem        | localSourceSystemName | sourceSystem |            sourceSystemName              |
#      |  Project_One             |     Project One       |  CONS_LATAM  | Consumer Latam Ent                       |
#      |  [Consumer LATAM]        |     Consumer Latam    |  CONS_LATAM  | Consumer Latam Ent                       |
#      |  [EMS]                   |     EMS               |  EMS         | Enterprise Master Data Management System |
#      |  [MD DePuy Spine JDE XE] |     Spine             |  MDDePuy     | MD DePuy Ent                             |
#      |  ems                     |     EMS               |  EMS         | Enterprise Master Data Management System |
#    And I wait "/edm/source_system_v1" Async Queue complete
#
#    Given I import "/project_one/mchb" by keyFields "charg,lgort,matnr,werks,mandt"
#      | ceinm |   charg  | cinsm | clabs | cretm | cspem | cumlm | lgort |         matnr     | werks | mandt |
#      |   0	  |0416LKH25 |	 1	 | 6	 |   0	 |  0	 |   0	 |  CO01 | 000000000000132288|	CO01 |  120  |
#      |   0	  |0416LKH26 |	 1	 | 11	 |   0	 |  0	 |   0	 |  CO01 | 000000000000132288|	CO01 |  120  |
#    And I wait "/project_one/mchb" Async Queue complete
#
#    When I submit task with xml file "xml/edm/EDMInventoryStock.xml" and execute file "jar/pangea-view.jar"
#
#    Then I check region data "/edm/inventory_stock" by keyFields "localBatchId,localConsignmentSpecialStockIndicator,localPlant,localSpecialStockIndicator,sourceSystem"
#      | sourceSystem | localPlant |        localMaterial      | localStorageLocation | localBatchId | localVendorNumber | localSpecialStockIndicator | localConsignmentSpecialStockIndicator | localUnrestrictedStock  | localUnrestrictedSpecialStock | localUnrestrictedBatchStock | localUnrestrictedConsignmentStock | localQualityInspectionStock | localQualityInspectionSpecialStock | localQualityInspectionBatchStock | localQualityInspectionConsignmentStock | localRestrictedStock | localRestrictedSpecialStock | localRestrictedBatchStock | localRestrictedConsignmentStock | localBlockedStock | localBlockedBatchStock  | localBlockedConsignmentStock| localReturnsStock | localReturnsBatchStock | localStockInTransitStorageLocation | localStockInTransitPlantToPlant |  localStockInTransitPlant | localStockInTransitSpecial | localStockInTransitBatch | localRestrictedUseConsignment | localConsignmentStockInQualityInspection | localUnrestrictedUseConsignment | standLocalBlockedConsignmentStock | localTotalStockAllRestrictedBatches |
#      |  CONS_LATAM  |            |                           |                      |   0416LKH25  |                   |                            |                                       |                         |                               |            6                |                                   |                             |                                    |                1                 |                                        |                      |                             |            0              |                                 |                   |            0            |                             |                   |            0           |               0                    |                                 |                           |                            |            0             |                               |                                          |                                 |                                   |                                     |
#      |  CONS_LATAM  |            |                           |                      |   0416LKH26  |                   |                            |                                       |                         |                               |            11               |                                   |                             |                                    |                1                 |                                        |                      |                             |            0              |                                 |                   |            0            |                             |                   |            0           |               0                    |                                 |                           |                            |            0             |                               |                                          |                                 |                                   |                                     |
#      |  CONS_LATAM  |            |                           |                      |              |                   |                            |                                       |                         |                               |                             |                                   |                             |                                    |                                  |                                        |                      |                             |                           |                                 |                   |                         |                             |                   |                        |               0                    |                                 |                           |                            |                          |                               |                                          |                                 |                                   |                                     |
#
#    Then I check region data "/plan/edm_failed_data" by keyFields "functionalArea,interfaceID,errorCode,sourceSystem,key1,key2,key3,key4,key5"
#      | functionalArea | interfaceID | errorCode | sourceSystem | businessArea | key1 | key2 | key3 | key4 | key5 | errorValue |
#
##    And I compare the number of records between "/project_one/marc" and "/edm/inventory_stock,/plan/edm_failed_data"
#
#    And I delete the test data
#
#    And I will remove all data with region "/edm/inventory_stock"
#
#    And I will remove all data with region "/plan/edm_failed_data"


#  @Scenario2
#  Scenario: N2,Join mslb
#    Given I import "/project_one/marc" by keyFields "mandt,matnr,werks"
#      | abcin | abfac | ahdis | altsl | aplal | apokz | atpkz | auftl | ausdt | ausme | ausss | autru | awsls | basmg | bearz | beskz | bstfe | bstma | bstmi | bstrf | bwesb | bwscl | bwtty | casnr | ccfix | compl | consProcg | convt | copam | cuobj | cuobv | diber | disgr | disls | dismm | dispo | dispr | dplfs | dplho | dplpu | dzeit | eisbe | eislo | ekgrp | eprio | expme | fabkz | fevor | ffrei | fhori | fixls | fprfm | frtme | fvidk | fxhor | fxpru | giPrTime | glgmg | gpmkz | gpnum | herbl | herkl | herkr | indus | insmk | itark | iuidRelevant | iuidType | kausf | kautb | kordb | kzagl | kzaus | kzbed | kzdie | kzdkz | kzech | kzkfk | kzkri | kzkup | kzppv | kzpro | kzpsp | ladgr | lagpr | lfgja | lfmon | lfrhy | lgfsb | lgpro | lgrad | lizyk | loggr | losfx | losgr | ltinc | lvorm | lzeih | maabc | mabst | mandt | matgr |         matnr     | maxls | maxlz | maxTroc | mcrue | mdach | megru | mfrgr | minbe | minls | minTroc | miskz | mmsta |   mmstd  | mogru | mownr | mpdau | mrppp | mtver | mtvfp | multipleEkgrp | ncost | nfmat | nkmpr | objid | ocmpf | otype | periv | perkz | pfrei | plifz | plnnr | plnty | plvar |  prctr  | prefe | prenc | prend | prene | preng | preno | prfrq |  pstat | qmata | qmatv | qssys | quazt | qzgtp | rdprf | refSchema | resvp | rgekz | rotationDate | ruezt | rwpro | sauft | sbdkz | schgt | sernp | servg | sfcpf | sfepr | shflg | shpro | shzet | sobsk | sobsl | sproz | ssqss | stawn | stdpd | steuc | stlal | stlan | strgr | takzt | targetStock | trame | tranz | uchkz | ucmat | ueetk | ueeto | uidIea | umlmc | umrsl | uneto | uomgr | usequ | vbamg | vbeaz | verkz | vint1 | vint2 | vkglg | vktrw | vkumc | vrbdt | vrbfk | vrbmt | vrbwk | vrmod | vrvez | vsorForkDir | vsorLaneNum | vsorPalVend | vsorPkgrp | vspvb | vzusl | webaz | werks | wstgh | wzeit | xchar | xchpf | xmcng | zdtalancprev | zdtalancreal | zindnbnp |
#      |	  C   |	  0	  |       |       |       |       |       |       |   0	  |       |   0	  |   X	  |Z00001 |	  0	  |    0  |	  F   |	  0	  |   0	  | 20000 |   0	  |   0	  |       |       |       |       |   0	  |	          |       | 	  |	  0   |	  0   |	 	  |       |   MB  |	  ND  |  C52  |	 	  |       |	   0  |	      |   0   |	  0   |   0   |	 C23  |	 	  |	 	  | 	  |       |       |    0  |   0   |       |       |  	  |	  0	  |	      |     0    |	 0   |	 	 |	 	 |	 	 |	 	 |	 	 |	     |       |       |              |          |   0   |   X   |   X   |	   |       |       |       |    X  |	   | 	   |       |       |       |       |       |       |       |  2006 |   8   | 	   |       |  CO02 |  94   |	   |       |   0   |  1000 |   0   |	   |	   | 	   |   0   |  120  |	   | 000000000000132288|   0   |   0   |	0    |	 	 |	 	 |       |       |	 0	 |   0   |	  0    |	   |   8   | 20060831 |	 	  |	      |   0	  |	 	  |       |   2   |               |       |       |   0   |   0   |	 	  |	 	  |       |   W   |	 	  |   0   |	 	  | 	  |       |21110813	| 	 	|       |   0   |	 	|   0	|  	    |   0   |EDPLSQBG|	 21	 |   X	 |	     |   0   |	CQF	 |       |           |	 0	 |   2   |	 	        |   0	| 	 	|       |   2   |	 	| 	 	| 	 	| 	 	|       |       |       |   0   |	 	|       | 	0	|   5	|  	 	| 	 	| 	 	|       |       |       |   0   |	   0      |	  0   |	  0   |	      | 	  |	 	  |   0   |	 	   |   0   |       |   0   |	   |	   |   0   |   0   |	   |   45  |   7   |   0   |    0  |   0   |	0  |   0   | 	   |       |   2   |   0   |             |	 	 	   |             |           |       |   0   |	 5   |	CO01 |	 0   |	 0   |	 X   |	 X   |	 	 |       0      |	    0      |	 	  |
#      |	  C   |	  0	  |       |       |       |       |       |       |   0	  |       |   0	  |   X	  |Z00001 |	  0	  |    0  |	  F   |	  0	  |   0	  | 20000 |   0	  |   0	  |       |       |       |       |   0	  |	          |       | 	  |	  0   |	  0   |	 	  |       |   MB  |	  ND  |  C52  |	 	  |       |	   0  |	      |   0   |	  0   |   0   |	 C23  |	 	  |	 	  | 	  |       |       |    0  |   0   |       |       |  	  |	  0	  |	      |     0    |	 0   |	 	 |	 	 |	 	 |	 	 |	 	 |	     |       |       |              |          |   0   |   X   |   X   |	   |       |       |       |    X  |	   | 	   |       |       |       |       |       |       |       |  2006 |   8   | 	   |       |  CO02 |  94   |	   |       |   0   |  1000 |   0   |	   |	   | 	   |   0   |  120  |	   | 000000000000132289|   0   |   0   |	0    |	 	 |	 	 |       |       |	 0	 |   0   |	  0    |	   |   8   | 20060831 |	 	  |	      |   0	  |	 	  |       |   2   |               |       |       |   0   |   0   |	 	  |	 	  |       |   W   |	 	  |   0   |	 	  | 	  |       |21110813	| 	 	|       |   0   |	 	|   0	|  	    |   0   |EDPLSQBG|	 21	 |   X	 |	     |   0   |	CQF	 |       |           |	 0	 |   2   |	 	        |   0	| 	 	|       |   2   |	 	| 	 	| 	 	| 	 	|       |       |       |   0   |	 	|       | 	0	|   5	|  	 	| 	 	| 	 	|       |       |       |   0   |	   0      |	  0   |	  0   |	      | 	  |	 	  |   0   |	 	   |   0   |       |   0   |	   |	   |   0   |   0   |	   |   45  |   7   |   0   |    0  |   0   |	0  |   0   | 	   |       |   2   |   0   |             |	 	 	   |             |           |       |   0   |	 5   |	CO01 |	 0   |	 0   |	 X   |	 X   |	 	 |       0      |	    0      |	 	  |
#
#    And I wait "/project_one/marc" Async Queue complete
#
#    Given I import "/edm/source_system_v1" by keyFields "localSourceSystem"
#      | localSourceSystem        | localSourceSystemName | sourceSystem |            sourceSystemName              |
#      |  Project_One             |     Project One       |  CONS_LATAM  | Consumer Latam Ent                       |
#      |  [Consumer LATAM]        |     Consumer Latam    |  CONS_LATAM  | Consumer Latam Ent                       |
#      |  [EMS]                   |     EMS               |  EMS         | Enterprise Master Data Management System |
#      |  [MD DePuy Spine JDE XE] |     Spine             |  MDDePuy     | MD DePuy Ent                             |
#      |  ems                     |     EMS               |  EMS         | Enterprise Master Data Management System |
#    And I wait "/edm/source_system_v1" Async Queue complete
#
#    Given I import "/project_one/mslb" by keyFields "charg,lifnr,mandt,matnr,sobkz,werks"
#      | mandt |        matnr     | werks |   charg  | sobkz | lifnr |  lblab |lbins | lbein | lbuml |
#      |  120  |000000000000132288|	CO01 |4000263375|	O	| 1023	|6840.000|0.000	| 0.000 | 0.000 |
#      |  120  |000000000000132288|	CO01 |4000279972|	O	| 1023	|6840.000|0.000	| 0.000 | 0.000 |
#    And I wait "/project_one/mslb" Async Queue complete
#
#    When I submit task with xml file "xml/edm/EDMInventoryStock.xml" and execute file "jar/pangea-view.jar"
#
#    Then I check region data "/edm/inventory_stock" by keyFields "localBatchId,localConsignmentSpecialStockIndicator,localPlant,localSpecialStockIndicator,sourceSystem"
#      | sourceSystem | localPlant |        localMaterial      | localStorageLocation | localBatchId | localVendorNumber | localSpecialStockIndicator | localConsignmentSpecialStockIndicator | localUnrestrictedStock  | localUnrestrictedSpecialStock | localUnrestrictedBatchStock | localUnrestrictedConsignmentStock | localQualityInspectionStock | localQualityInspectionSpecialStock | localQualityInspectionBatchStock | localQualityInspectionConsignmentStock | localRestrictedStock | localRestrictedSpecialStock | localRestrictedBatchStock | localRestrictedConsignmentStock | localBlockedStock | localBlockedBatchStock  | localBlockedConsignmentStock| localReturnsStock | localReturnsBatchStock | localStockInTransitStorageLocation | localStockInTransitPlantToPlant |  localStockInTransitPlant | localStockInTransitSpecial | localStockInTransitBatch | localRestrictedUseConsignment | localConsignmentStockInQualityInspection | localUnrestrictedUseConsignment | standLocalBlockedConsignmentStock | localTotalStockAllRestrictedBatches |
#      |  CONS_LATAM  |            |                           |                      |              |       1023        |           0                |                                       |                         |             6840.000          |                             |                                   |                             |             0.000                       |                                  |                                        |                      |          0.000              |                           |                                 |                   |                         |                             |                   |                        |               0                    |                                 |                           |         0.000              |                          |                               |                                          |                                 |                                   |                                     |
#      |  CONS_LATAM  |            |                           |                      |              |                   |                            |                                       |                         |                               |                             |                                   |                             |                                    |                                  |                                        |                      |                             |                           |                                 |                   |                         |                             |                   |                        |               0                    |                                 |                           |                            |                          |                               |                                          |                                 |                                   |                                     |
#
#
#    Then I check region data "/plan/edm_failed_data" by keyFields "functionalArea,interfaceID,errorCode,sourceSystem,key1,key2,key3,key4,key5"
#      | functionalArea | interfaceID | errorCode | sourceSystem | businessArea | key1 | key2 | key3 | key4 | key5 | errorValue |
#
##    And I compare the number of records between "/project_one/marc" and "/edm/inventory_stock,/plan/edm_failed_data"
#
#    And I delete the test data
#
#    And I will remove all data with region "/edm/inventory_stock"
#
#    And I will remove all data with region "/plan/edm_failed_data"

  @Scenario3
  Scenario: N3,Join mkol
    Given I import "/project_one/marc" by keyFields "mandt,matnr,werks"
      | abcin | abfac | ahdis | altsl | aplal | apokz | atpkz | auftl | ausdt | ausme | ausss | autru | awsls | basmg | bearz | beskz | bstfe | bstma | bstmi | bstrf | bwesb | bwscl | bwtty | casnr | ccfix | compl | consProcg | convt | copam | cuobj | cuobv | diber | disgr | disls | dismm | dispo | dispr | dplfs | dplho | dplpu | dzeit | eisbe | eislo | ekgrp | eprio | expme | fabkz | fevor | ffrei | fhori | fixls | fprfm | frtme | fvidk | fxhor | fxpru | giPrTime | glgmg | gpmkz | gpnum | herbl | herkl | herkr | indus | insmk | itark | iuidRelevant | iuidType | kausf | kautb | kordb | kzagl | kzaus | kzbed | kzdie | kzdkz | kzech | kzkfk | kzkri | kzkup | kzppv | kzpro | kzpsp | ladgr | lagpr | lfgja | lfmon | lfrhy | lgfsb | lgpro | lgrad | lizyk | loggr | losfx | losgr | ltinc | lvorm | lzeih | maabc | mabst | mandt | matgr |         matnr     | maxls | maxlz | maxTroc | mcrue | mdach | megru | mfrgr | minbe | minls | minTroc | miskz | mmsta |   mmstd  | mogru | mownr | mpdau | mrppp | mtver | mtvfp | multipleEkgrp | ncost | nfmat | nkmpr | objid | ocmpf | otype | periv | perkz | pfrei | plifz | plnnr | plnty | plvar |  prctr  | prefe | prenc | prend | prene | preng | preno | prfrq |  pstat | qmata | qmatv | qssys | quazt | qzgtp | rdprf | refSchema | resvp | rgekz | rotationDate | ruezt | rwpro | sauft | sbdkz | schgt | sernp | servg | sfcpf | sfepr | shflg | shpro | shzet | sobsk | sobsl | sproz | ssqss | stawn | stdpd | steuc | stlal | stlan | strgr | takzt | targetStock | trame | tranz | uchkz | ucmat | ueetk | ueeto | uidIea | umlmc | umrsl | uneto | uomgr | usequ | vbamg | vbeaz | verkz | vint1 | vint2 | vkglg | vktrw | vkumc | vrbdt | vrbfk | vrbmt | vrbwk | vrmod | vrvez | vsorForkDir | vsorLaneNum | vsorPalVend | vsorPkgrp | vspvb | vzusl | webaz | werks | wstgh | wzeit | xchar | xchpf | xmcng | zdtalancprev | zdtalancreal | zindnbnp |
      |	  C   |	  0	  |       |       |       |       |       |       |   0	  |       |   0	  |   X	  |Z00001 |	  0	  |    0  |	  F   |	  0	  |   0	  | 20000 |   0	  |   0	  |       |       |       |       |   0	  |	          |       | 	  |	  0   |	  0   |	 	  |       |   MB  |	  ND  |  C52  |	 	  |       |	   0  |	      |   0   |	  0   |   0   |	 C23  |	 	  |	 	  | 	  |       |       |    0  |   0   |       |       |  	  |	  0	  |	      |     0    |	 0   |	 	 |	 	 |	 	 |	 	 |	 	 |	     |       |       |              |          |   0   |   X   |   X   |	   |       |       |       |    X  |	   | 	   |       |       |       |       |       |       |       |  2006 |   8   | 	   |       |  CO02 |  94   |	   |       |   0   |  1000 |   0   |	   |	   | 	   |   0   |  120  |	   | 000000000000132288|   0   |   0   |	0    |	 	 |	 	 |       |       |	 0	 |   0   |	  0    |	   |   8   | 20060831 |	 	  |	      |   0	  |	 	  |       |   2   |               |       |       |   0   |   0   |	 	  |	 	  |       |   W   |	 	  |   0   |	 	  | 	  |       |21110813	| 	 	|       |   0   |	 	|   0	|  	    |   0   |EDPLSQBG|	 21	 |   X	 |	     |   0   |	CQF	 |       |           |	 0	 |   2   |	 	        |   0	| 	 	|       |   2   |	 	| 	 	| 	 	| 	 	|       |       |       |   0   |	 	|       | 	0	|   5	|  	 	| 	 	| 	 	|       |       |       |   0   |	   0      |	  0   |	  0   |	      | 	  |	 	  |   0   |	 	   |   0   |       |   0   |	   |	   |   0   |   0   |	   |   45  |   7   |   0   |    0  |   0   |	0  |   0   | 	   |       |   2   |   0   |             |	 	 	   |             |           |       |   0   |	 5   |	CO01 |	 0   |	 0   |	 X   |	 X   |	 	 |       0      |	    0      |	 	  |
      |	  C   |	  0	  |       |       |       |       |       |       |   0	  |       |   0	  |   X	  |Z00001 |	  0	  |    0  |	  F   |	  0	  |   0	  | 20000 |   0	  |   0	  |       |       |       |       |   0	  |	          |       | 	  |	  0   |	  0   |	 	  |       |   MB  |	  ND  |  C52  |	 	  |       |	   0  |	      |   0   |	  0   |   0   |	 C23  |	 	  |	 	  | 	  |       |       |    0  |   0   |       |       |  	  |	  0	  |	      |     0    |	 0   |	 	 |	 	 |	 	 |	 	 |	 	 |	     |       |       |              |          |   0   |   X   |   X   |	   |       |       |       |    X  |	   | 	   |       |       |       |       |       |       |       |  2006 |   8   | 	   |       |  CO02 |  94   |	   |       |   0   |  1000 |   0   |	   |	   | 	   |   0   |  120  |	   | 000000000000132289|   0   |   0   |	0    |	 	 |	 	 |       |       |	 0	 |   0   |	  0    |	   |   8   | 20060831 |	 	  |	      |   0	  |	 	  |       |   2   |               |       |       |   0   |   0   |	 	  |	 	  |       |   W   |	 	  |   0   |	 	  | 	  |       |21110813	| 	 	|       |   0   |	 	|   0	|  	    |   0   |EDPLSQBG|	 21	 |   X	 |	     |   0   |	CQF	 |       |           |	 0	 |   2   |	 	        |   0	| 	 	|       |   2   |	 	| 	 	| 	 	| 	 	|       |       |       |   0   |	 	|       | 	0	|   5	|  	 	| 	 	| 	 	|       |       |       |   0   |	   0      |	  0   |	  0   |	      | 	  |	 	  |   0   |	 	   |   0   |       |   0   |	   |	   |   0   |   0   |	   |   45  |   7   |   0   |    0  |   0   |	0  |   0   | 	   |       |   2   |   0   |             |	 	 	   |             |           |       |   0   |	 5   |	CO01 |	 0   |	 0   |	 X   |	 X   |	 	 |       0      |	    0      |	 	  |

    And I wait "/project_one/marc" Async Queue complete

    Given I import "/edm/source_system_v1" by keyFields "localSourceSystem"
      | localSourceSystem        | localSourceSystemName | sourceSystem |            sourceSystemName              |
      |  Project_One             |     Project One       |  CONS_LATAM  | Consumer Latam Ent                       |
      |  [Consumer LATAM]        |     Consumer Latam    |  CONS_LATAM  | Consumer Latam Ent                       |
      |  [EMS]                   |     EMS               |  EMS         | Enterprise Master Data Management System |
      |  [MD DePuy Spine JDE XE] |     Spine             |  MDDePuy     | MD DePuy Ent                             |
      |  ems                     |     EMS               |  EMS         | Enterprise Master Data Management System |
    And I wait "/edm/source_system_v1" Async Queue complete

    Given I import "/project_one/mkol" by keyFields "charg,lifnr,logrt,mandt,matnr,sobkz,werks"
      | mandt |        matnr       | werks | logrt |   charg  | sobkz | lifnr |    slabs  |   sinsm  | seinm | sspem |
      |  120  |	000000000000132288 |  CO01 |  CO02 |4000290989|   K	  |  6137 |	660.000   |0.000	 | 0.000 | 0.000 |
      |  120  |	000000000000132288 |  CO01 |  CO02 |4000290991|   K	  |  6137 |	0.000	  |28800.000 | 0.000 | 0.000 |

    And I wait "/project_one/mkol" Async Queue complete

    When I submit task with xml file "xml/edm/EDMInventoryStock.xml" and execute file "jar/pangea-view.jar"

    Then I check region data "/edm/inventory_stock" by keyFields "localBatchId,localConsignmentSpecialStockIndicator,localPlant,localSpecialStockIndicator,sourceSystem"
      | sourceSystem | localPlant |        localMaterial      | localStorageLocation | localBatchId | localVendorNumber | localSpecialStockIndicator | localConsignmentSpecialStockIndicator | localUnrestrictedStock  | localUnrestrictedSpecialStock | localUnrestrictedBatchStock | localUnrestrictedConsignmentStock | localQualityInspectionStock | localQualityInspectionSpecialStock | localQualityInspectionBatchStock | localQualityInspectionConsignmentStock | localRestrictedStock | localRestrictedSpecialStock | localRestrictedBatchStock | localRestrictedConsignmentStock | localBlockedStock | localBlockedBatchStock  | localBlockedConsignmentStock| localReturnsStock | localReturnsBatchStock | localStockInTransitStorageLocation | localStockInTransitPlantToPlant |  localStockInTransitPlant | localStockInTransitSpecial | localStockInTransitBatch | localRestrictedUseConsignment | localConsignmentStockInQualityInspection | localUnrestrictedUseConsignment | standLocalBlockedConsignmentStock | localTotalStockAllRestrictedBatches |
      |  CONS_LATAM  |            |                           |                      |              |       1023        |           0                |                                       |                         |             6840.000          |                             |                                   |                             |             0.000                       |                                  |                                        |                      |          0.000              |                           |                                 |                   |                         |                             |                   |                        |               0                    |                                 |                           |         0.000              |                          |                               |                                          |                                 |                                   |                                     |
      |  CONS_LATAM  |            |                           |                      |              |                   |                            |                                       |                         |                               |                             |                                   |                             |                                    |                                  |                                        |                      |                             |                           |                                 |                   |                         |                             |                   |                        |               0                    |                                 |                           |                            |                          |                               |                                          |                                 |                                   |                                     |


    Then I check region data "/plan/edm_failed_data" by keyFields "functionalArea,interfaceID,errorCode,sourceSystem,key1,key2,key3,key4,key5"
      | functionalArea | interfaceID | errorCode | sourceSystem | businessArea | key1 | key2 | key3 | key4 | key5 | errorValue |

#    And I compare the number of records between "/project_one/marc" and "/edm/inventory_stock,/plan/edm_failed_data"

    And I delete the test data

    And I will remove all data with region "/edm/inventory_stock"

    And I will remove all data with region "/plan/edm_failed_data"

#  Scenario: Full Load curation
#
#    Given I import "/project_one/marc" by keyFields "mandt,matnr,werks"
#      | abcin | abfac | ahdis | altsl | aplal | apokz | atpkz | auftl | ausdt | ausme | ausss | autru | awsls | basmg | bearz | beskz | bstfe | bstma | bstmi | bstrf | bwesb | bwscl | bwtty | casnr | ccfix | compl | consProcg | convt | copam | cuobj | cuobv | diber | disgr | disls | dismm | dispo | dispr | dplfs | dplho | dplpu | dzeit | eisbe | eislo | ekgrp | eprio | expme | fabkz | fevor | ffrei | fhori | fixls | fprfm | frtme | fvidk | fxhor | fxpru | giPrTime | glgmg | gpmkz | gpnum | herbl | herkl | herkr | indus | insmk | itark | iuidRelevant | iuidType | kausf | kautb | kordb | kzagl | kzaus | kzbed | kzdie | kzdkz | kzech | kzkfk | kzkri | kzkup | kzppv | kzpro | kzpsp | ladgr | lagpr | lfgja | lfmon | lfrhy | lgfsb | lgpro | lgrad | lizyk | loggr | losfx | losgr | ltinc | lvorm | lzeih | maabc | mabst | mandt | matgr |         matnr     | maxls | maxlz | maxTroc | mcrue | mdach | megru | mfrgr | minbe | minls | minTroc | miskz | mmsta |   mmstd  | mogru | mownr | mpdau | mrppp | mtver | mtvfp | multipleEkgrp | ncost | nfmat | nkmpr | objid | ocmpf | otype | periv | perkz | pfrei | plifz | plnnr | plnty | plvar |  prctr  | prefe | prenc | prend | prene | preng | preno | prfrq |  pstat | qmata | qmatv | qssys | quazt | qzgtp | rdprf | refSchema | resvp | rgekz | rotationDate | ruezt | rwpro | sauft | sbdkz | schgt | sernp | servg | sfcpf | sfepr | shflg | shpro | shzet | sobsk | sobsl | sproz | ssqss | stawn | stdpd | steuc | stlal | stlan | strgr | takzt | targetStock | trame | tranz | uchkz | ucmat | ueetk | ueeto | uidIea | umlmc | umrsl | uneto | uomgr | usequ | vbamg | vbeaz | verkz | vint1 | vint2 | vkglg | vktrw | vkumc | vrbdt | vrbfk | vrbmt | vrbwk | vrmod | vrvez | vsorForkDir | vsorLaneNum | vsorPalVend | vsorPkgrp | vspvb | vzusl | webaz | werks | wstgh | wzeit | xchar | xchpf | xmcng | zdtalancprev | zdtalancreal | zindnbnp |
#      |	  C   |	  0	  |       |       |       |       |       |       |   0	  |       |   0	  |   X	  |Z00001 |	  0	  |    0  |	  F   |	  0	  |   0	  | 20000 |   0	  |   0	  |       |       |       |       |   0	  |	          |       | 	  |	  0   |	  0   |	 	  |       |   MB  |	  ND  |  C52  |	 	  |       |	   0  |	      |   0   |	  0   |   0   |	 C23  |	 	  |	 	  | 	  |       |       |    0  |   0   |       |       |  	  |	  0	  |	      |     0    |	 0   |	 	 |	 	 |	 	 |	 	 |	 	 |	     |       |       |              |          |   0   |   X   |   X   |	   |       |       |       |    X  |	   | 	   |       |       |       |       |       |       |       |  2006 |   8   | 	   |       |  CO02 |  94   |	   |       |   0   |  1000 |   0   |	   |	   | 	   |   0   |  120  |	   | 000000000000132288|   0   |   0   |	0    |	 	 |	 	 |       |       |	 0	 |   0   |	  0    |	   |   8   | 20060831 |	 	  |	      |   0	  |	 	  |       |   2   |               |       |       |   0   |   0   |	 	  |	 	  |       |   W   |	 	  |   0   |	 	  | 	  |       |21110813	| 	 	|       |   0   |	 	|   0	|  	    |   0   |EDPLSQBG|	 21	 |   X	 |	     |   0   |	CQF	 |       |           |	 0	 |   2   |	 	        |   0	| 	 	|       |   2   |	 	| 	 	| 	 	| 	 	|       |       |       |   0   |	 	|       | 	0	|   5	|  	 	| 	 	| 	 	|       |       |       |   0   |	   0      |	  0   |	  0   |	      | 	  |	 	  |   0   |	 	   |   0   |       |   0   |	   |	   |   0   |   0   |	   |   45  |   7   |   0   |    0  |   0   |	0  |   0   | 	   |       |   2   |   0   |             |	 	 	   |             |           |       |   0   |	 5   |	CO01 |	 0   |	 0   |	 X   |	 X   |	 	 |       0      |	    0      |	 	  |
#      |	  C   |	  0	  |       |       |       |       |       |       |   0	  |       |   0	  |   X	  |Z00001 |	  0	  |    0  |	  F   |	  0	  |   0	  | 20000 |   0	  |   0	  |       |       |       |       |   0	  |	          |       | 	  |	  0   |	  0   |	 	  |       |   MB  |	  ND  |  C52  |	 	  |       |	   0  |	      |   0   |	  0   |   0   |	 C23  |	 	  |	 	  | 	  |       |       |    0  |   0   |       |       |  	  |	  0	  |	      |     0    |	 0   |	 	 |	 	 |	 	 |	 	 |	 	 |	     |       |       |              |          |   0   |   X   |   X   |	   |       |       |       |    X  |	   | 	   |       |       |       |       |       |       |       |  2006 |   8   | 	   |       |  CO02 |  94   |	   |       |   0   |  1000 |   0   |	   |	   | 	   |   0   |  120  |	   | 000000000000132289|   0   |   0   |	0    |	 	 |	 	 |       |       |	 0	 |   0   |	  0    |	   |   8   | 20060831 |	 	  |	      |   0	  |	 	  |       |   2   |               |       |       |   0   |   0   |	 	  |	 	  |       |   W   |	 	  |   0   |	 	  | 	  |       |21110813	| 	 	|       |   0   |	 	|   0	|  	    |   0   |EDPLSQBG|	 21	 |   X	 |	     |   0   |	CQF	 |       |           |	 0	 |   2   |	 	        |   0	| 	 	|       |   2   |	 	| 	 	| 	 	| 	 	|       |       |       |   0   |	 	|       | 	0	|   5	|  	 	| 	 	| 	 	|       |       |       |   0   |	   0      |	  0   |	  0   |	      | 	  |	 	  |   0   |	 	   |   0   |       |   0   |	   |	   |   0   |   0   |	   |   45  |   7   |   0   |    0  |   0   |	0  |   0   | 	   |       |   2   |   0   |             |	 	 	   |             |           |       |   0   |	 5   |	CO01 |	 0   |	 0   |	 X   |	 X   |	 	 |       0      |	    0      |	 	  |
#
#    And I wait "/project_one/marc" Async Queue complete
#
#    Given I import "/edm/source_system_v1" by keyFields "localSourceSystem"
#      | localSourceSystem        | localSourceSystemName | sourceSystem |            sourceSystemName              |
#      |  Project_One             |     Project One       |  CONS_LATAM  | Consumer Latam Ent                       |
#      |  [Consumer LATAM]        |     Consumer Latam    |  CONS_LATAM  | Consumer Latam Ent                       |
#      |  [EMS]                   |     EMS               |  EMS         | Enterprise Master Data Management System |
#      |  [MD DePuy Spine JDE XE] |     Spine             |  MDDePuy     | MD DePuy Ent                             |
#      |  ems                     |     EMS               |  EMS         | Enterprise Master Data Management System |
#    And I wait "/edm/source_system_v1" Async Queue complete
#
#    Given I import "/project_one/mchb" by keyFields "charg,lgort,matnr,werks,mandt"
#      | ceinm |   charg  | cinsm | clabs | cretm | cspem | cumlm | lgort |         matnr     | werks | mandt |
#      |   0	  |0416LKH25 |	 1	 | 6	 |   0	 |  0	 |   0	 |  CO01 | 000000000000132288|	CO01 |  120  |
#      |   0	  |0416LKH26 |	 1	 | 11	 |   0	 |  0	 |   0	 |  CO01 | 000000000000132288|	CO01 |  120  |
#    And I wait "/project_one/mchb" Async Queue complete
#
#    Given I import "/project_one/mkol" by keyFields "charg,lifnr,logrt,mandt,matnr,sobkz,werks"
#      | mandt |        matnr       | werks | logrt |   charg  | sobkz | lifnr |    slabs  |   sinsm  | seinm | sspem |
#      |  120  |	000000000000132288 |  CO01 |  CO02 |4000290989|   K	  |  6137 |	660.000   |0.000	 | 0.000 | 0.000 |
#      |  120  |	000000000000132288 |  CO01 |  CO02 |4000290991|   K	  |  6137 |	0.000	  |28800.000 | 0.000 | 0.000 |
#
#    And I wait "/project_one/mkol" Async Queue complete
#
#    Given I import "/project_one/mard" by keyFields "lgort,mandt,matnr,werks"
#      | mandt |         matnr     | werks | lgort | labst | umlme | insme | einme | speme | retme | klabs | kinsm | keinm |kspem | umlmc |
#      |   120 | 000000000000132288|  CO01 |  CO07 |  1807  |   0  |  213  |   0   | 2     |   0   |   0   |   6   |   0   |  0   |   0   |
#      |   120 | 000000000000132288|  CO01 |  CO08 |  1807  |   0  |  213  |   0   | 2     |   0   |   0   |   6   |   0   |  0   |   0   |
#    And I wait "/project_one/mard" Async Queue complete
#
#    Given I import "/project_one/mslb" by keyFields "charg,lifnr,mandt,matnr,sobkz,werks"
#      | mandt |        matnr     | werks |   charg  | sobkz | lifnr |  lblab |lbins | lbein | lbuml |
#      |  120  |000000000000132288|	CO01 |4000263375|	O	| 1023	|6840.000|0.000	| 0.000 | 0.000 |
#      |  120  |000000000000132288|	CO01 |4000279972|	O	| 1023	|6840.000|0.000	| 0.000 | 0.000 |
#    And I wait "/project_one/mslb" Async Queue complete
#
#
#    When I submit task with xml file "xml/edm/EDMInventoryStock.xml" and execute file "jar/pangea-view.jar"

#    Then I check region data "/edm/inventory_stock" by keyFields "localBatchId,localConsignmentSpecialStockIndicator,localPlant,localSpecialStockIndicator,sourceSystem"
#      | sourceSystem | localPlant |        localMaterial      | localStorageLocation | localBatchId | localVendorNumber | localSpecialStockIndicator | localConsignmentSpecialStockIndicator | localUnrestrictedStock  | localUnrestrictedSpecialStock | localUnrestrictedBatchStock | localUnrestrictedConsignmentStock | localQualityInspectionStock | localQualityInspectionSpecialStock | localQualityInspectionBatchStock | localQualityInspectionConsignmentStock | localRestrictedStock | localRestrictedSpecialStock | localRestrictedBatchStock | localRestrictedConsignmentStock | localBlockedStock | localBlockedBatchStock  | localBlockedConsignmentStock| localReturnsStock | localReturnsBatchStock | localStockInTransitStorageLocation | localStockInTransitPlantToPlant |  localStockInTransitPlant | localStockInTransitSpecial | localStockInTransitBatch | localRestrictedUseConsignment | localConsignmentStockInQualityInspection | localUnrestrictedUseConsignment | standLocalBlockedConsignmentStock | localTotalStockAllRestrictedBatches |
#      |  CONS_LATAM  |    CO01    |     000000000000132288    |         CO07         |   0416LKH25  |         1023      |              O             |                   K                   |          1807           |             6840.000          |                 6           |                 0.000             |            213              |                0.000               |                1                 |               28800.000                |           0          |              0.000          |              0            |                0.000            |       2           |             0           |          0.000              |         0         |            0           |                 0                  |                 0               |              0            |             0.000          |              0           |                0              |                     6                    |                0                |                   0               |                  0                  |
#      |  CONS_LATAM  |    CO01    |     000000000000132288    |         CO07         |   0416LKH26  |         1023      |              O             |                   K                   |          1807           |             6840.000          |                 11          |                 0.000             |            213              |                0.000               |                1                 |               28800.000                |           0          |              0.000          |              0            |                0.000            |       2           |             0           |          0.000              |         0         |            0           |                 0                  |                 0               |              0            |             0.000          |              0           |                0              |                     6                    |                0                |                   0               |                  0                  |
#      |  CONS_LATAM  |            |                           |                      |              |                   |                            |                                       |                         |                               |                             |                                   |                             |                                    |                                  |                                        |                      |                             |                           |                                 |                   |                         |                             |                   |                        |                 0                  |                                 |                           |                            |                          |                               |                                          |                                 |                                   |                                     |
#    Then I check region data "/plan/edm_failed_data" by keyFields "functionalArea,interfaceID,errorCode,sourceSystem,key1,key2,key3,key4,key5"
#      | functionalArea | interfaceID | errorCode | sourceSystem | businessArea | key1 | key2 | key3 | key4 | key5 | errorValue |
#
#    And I compare the number of records between "/project_one/marc" and "/edm/inventory_stock,/plan/edm_failed_data"
#
#    And I delete the test data
#
#    And I will remove all data with region "/edm/inventory_stock"
#
#    And I will remove all data with region "/plan/edm_failed_data"

