@pangea_test @AEAZ-8900
Feature:  OMPGdmStockPurchaseOrder-Curation

  Scenario: Full Load consumption

    Given I import "/edm/purchase_order_oa_v1" by keyFields "delvSchedCntNbr,evTypeCd,localSeqNumActAsgn,localSeqNumVendConf,matlMvmtNum,matlMvmtSeqNbr,matlMvmttYr,poLineNbr,poNum,sourceSystem"
      | sourceSystem |    poNum   | poLineNbr | evTypeCd | matlMvmttYr | matlMvmtNum | matlMvmtSeqNbr | delvSchedCntNbr | poCatTypeCd | poTypeCd | crtOnDt  | supNum | prchsngOrgNum | prchsngGrpNum | prchsngCoCd | crncyCd |   poDt   | vldFromDt | vldToDt | suplVendNum | suplPlntCd | rlseCmpltInd | rlseDocInd | delInd | matlNum | plntCd | slocCd | intrnlRefNum | poLineQty | poUomCd | localNumerator | localDenominator | stkTypeCd | delvCmpltInd | lineItemTypeCd | acctAsgnmtCatCd | prinPrchAgmtNum | prinPrchAgmtLineNbr | localBaseUOM | delvAddrNum | localPDT | localSpecialStock | cnfrmCd | subcntrcInd | localdelvAddrNum | prDocId    | prLineNbr | localBrazilianNCMCode | isuSlocCd | poHistCatCd | localMovementType | localPostingDate | recvEaQty | cnfrmSeqNbr | delvDt   | cnfrmQty | mrpAdjQty | localCreationIndVendorConf | slsOrdrNum | slsOrdrLineNbr | vendBtchNum | localdelvDt | schdQty | recvQty | localPurchaseReq | localPurchaseReqItem | stkTfrRecvQty | localmrpAdjQty | grLeadTimeDays | custNum | localSeqNumActAsgn | localSeqNumVendConf |
      | CONS_LATAM   | 3000793997 |    10     |    1     |    2017     | 5006382844  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58752  |  MX01  |  MX01  |              |   1968    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793991 |    20     |    1     |    2017     | 5006382844  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58753  |  MX01  |  MX01  |              |   2000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      20   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    200   |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793992 |    20     |    1     |    2017     | 5006382844  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58754  |  MX01  |  MX01  |              |   3000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      20   |                       |           |      E      |    101            |    20170103      |  3000.000 |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793993 |    11     |    1     |    2017     | 5006382844  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58755  |  CR02  |  MX01  |              |   1000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      11   |                       |           |      E      |    101            |    20170103      |  200.000  |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793993 |    11     |    1     |    2017     | 5006382845  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58755  |  CR02  |  MX01  |              |   1000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      11   |                       |           |      E      |    101            |    20170103      |  300.000  |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793998 |    20     |    1     |    2017     | 5006382844  |        1       |        1        |     L       |    ZLA   | 20170102 |  1189  |       BR12    |      M39      |     8302    |   BR    | 20170102 |           |         |             | BR12       |              |     1      |        |  80990  |  BR12  |  BR12  |              |   2350    |    EA   |       1        |         1        |    X      |              |       K        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      20   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    250   |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793999 |    10     |    1     |    2017     | 5006382844  |        1       |        1        |     L       |    ZLA   | 20170102 |  1189  |       BR12    |      M39      |     8302    |   BR    | 20170102 |           |         |             | BR12       |              |     1      |        |  96161  |  BR12  |  BR12  |              |   3000    |    EA   |       1        |         1        |    X      |              |       K        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    1000  |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793995 |    20     |    1     |    2017     | 5006382844  |        1       |        1        |     L       |    ZNB   | 20170102 |  1189  |       BR12    |      M39      |     8302    |   BR    | 20170102 |           |         |             | BR12       |              |     1      |        |  528395 |  CO01  |  BR12  |              |   1000    |    EA   |       1        |         1        |    X      |              |       K        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      20   |                       |           |      E      |    101            |    20170103      |  100.000  |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793990 |    40     |    1     |    2017     | 5006382844  |        1       |        1        |     L       |    UB    | 20170102 |  1189  |       BR14    |      M39      |     8302    |   BR    | 20170102 |           |         |             |            |              |     1      |        |  57039  |  MX02  |  BR14  |              |   2000    |    EA   |       1        |         1        |    X      |              |       K        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      40   |                       |           |      E      |    101            |    20170103      |  200.000  |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793111 |    40     |    1     |    2017     | 5006382844  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58752  |  MX01  |  MX01  |              |   2000    |    EA   |       1        |         1        |    X      |              |       3        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      40   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    200   |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 30007930001|    40     |    1     |    2017     | 5006382844  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |    X   |  58752  |  BR22  |  MX01  |              |   2000    |    EA   |       1        |         1        |    X      |       X      |       L        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      40   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    200   |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793100 |    10     |    1     |    2017     | 5006382844  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58755  |  CR02  |  MX01  |              |   2000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    200   |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793100 |    10     |    1     |    2017     | 5006382845  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58755  |  CR02  |  MX01  |              |   2000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    300   |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793200 |    10     |    1     |    2017     | 5006382841  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58756  |  PE01  |  MX01  |              |   4000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    1000  |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793200 |    10     |    1     |    2017     | 5006382842  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58756  |  PE01  |  MX01  |              |   4000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    1000  |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793200 |    10     |    1     |    2017     | 5006382843  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58756  |  PE01  |  MX01  |              |   4000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    1000  |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793200 |    10     |    1     |    2017     | 5006382844  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58756  |  PE01  |  MX01  |              |   4000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  1000.000 |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793200 |    10     |    1     |    2017     | 5006382845  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58756  |  PE01  |  MX01  |              |   4000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  1000.000 |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793211 |    10     |    1     |    2017     | 5006382840  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  58799  |  MX02  |  MX01  |              |   4000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  1000.000 |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793212 |    10     |    1     |    2017     | 5006382840  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  12345  |  MX02  |  MX01  |              |   4000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  1000.000 |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793213 |    10     |    1     |    2017     | 5006382840  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX010   |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX010      |              |            |        |  12346  |  MX010 |  MX010 |              |   4000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  1000.000 |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793214 |    10     |    1     |    2017     | 5006382840  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  12347  |  MX02  |  MX01  |              |   1000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  1000.000 |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793215 |    10     |    1     |    2017     | 5006382840  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  12347  |  MX02  |  MX01  |              |   1000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    1000  |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793216 |    10     |    1     |    2017     | 5006382840  |        1       |        1        |     F       |    GGG   | 20170102 |  6109  |       MXX1    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MXX1       |              |            |        |  12347  |  MXX1  |  MXX1  |              |   1000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    1000  |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793217 |    10     |    1     |    2017     | 5006382840  |        1       |        1        |     F       |    GGG   | 20170102 |  6109  |       MXX1    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MXX1       |              |            |        |  12347  |  MXX1  |  MXX1  |              |   1000    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    1000  |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793218 |    10     |    1     |    2017     | 5006382840  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  12348  |  MX02  |  MX01  |              |   800     |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  1000.000 |             | 20170103 |    0     |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793219 |    10     |    1     |    2017     | 5006382840  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  12348  |  MX02  |  MX01  |              |   800     |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    1000  |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793270 |    10     |    1     |    2017     | 5006382840  |        1       |        1        |     F       |    HH    | 20170102 |  6109  |       MX01    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MX01       |              |            |        |  12348  |  MX02  |  MX01  |              |   1100    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    1000  |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |
      | CONS_LATAM   | 3000793271 |    10     |    1     |    2017     | 5006382840  |        1       |        1        |     F       |    NB    | 20170102 |  6109  |       HHHH    |      M39      |     8302    |   MXN   | 20170102 |           |         |             | MXXX       |              |            |        |  12348  |  MXHH  |  MX01  |              |   1100    |    EA   |       1        |         1        |    X      |              |       2        |                 |    5100003715   |       4950          |       EA     |             |    0     |                   |         |             |                  | 1603571115 |      10   |                       |           |      E      |    101            |    20170103      |  0.000    |             | 20170103 |    1000  |           |                            |            |                |             |   20170103  |         |         |                  |                      |               |                |      1         |         |                    |                     |

    And I wait "/edm/purchase_order_oa_v1" Async Queue complete

    Given I import "/edm/material_global_v1" by keyFields "localMaterialNumber,sourceSystem"
      | baseUom | batchManageIndicator | brand | category | division | flagForDeletion | form | franchise | globalBusinessUnit | globalDpParentCode | localBaseUom | localDpParentCode | localManufacturingTechnology | localMaterialGroup | localMaterialNumber | localMaterialType |       localRefDescription                | manufacturingTechnology | materialGroup | materialNumber | materialStatus | materialType | minRemShelfLife | parentCode | primaryPlanningCode | productFamily | refDescription | sourceSystem | subBrand | totalShelfLife |
      |         |                      |       |          |    10    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         58752       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      58752     |        8       |              |       0         |            |                     |               |                |   CONS_LATAM |          |       0        |
      |         |                      |       |          |    11    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         80990       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      99999     |        8       |              |       365       |            |        80990        |               |                |   CONS_LATAM |          |       1825     |
      |         |                      |       |          |    10    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         57039       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      57039     |        8       |              |       120       |            |        57039        |               |                |   CONS_LATAM |          |       11       |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         96161       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      96161     |        9       |              |       11        |            |        96161        |               |                |   CONS_LATAM |          |       1        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         91732       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      91732     |        8       |              |       8         |            |        91732        |               |                |   CONS_LATAM |          |       2        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         60520       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      60520     |        9       |              |       9         |            |        60520        |               |                |   CONS_LATAM |          |       6        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         528395      |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      528395    |        9       |              |                 |    9       |        528395       |               |                |   CONS_LATAM |          |       7        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         58753       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      58753     |        9       |              |       11        |            |        58753        |               |                |   CONS_LATAM |          |       1        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         58754       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      58754     |        8       |              |       8         |            |        58754        |               |                |   CONS_LATAM |          |       2        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         58755       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      58755     |        9       |              |       9         |            |        58755        |               |                |   CONS_LATAM |          |       6        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         58756       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      58756     |        9       |              |                 |    9       |        58756        |               |                |   CONS_LATAM |          |       7        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         58799       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |                |        9       |              |                 |    9       |                     |               |                |   CONS_LATAM |          |       7        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         12345       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      12345     |        9       |              |                 |    9       |        12345        |               |                |   CONS_LATAM |          |       7        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         12347       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      12347     |        9       |              |                 |    9       |        12347        |               |                |   CONS_LATAM |          |       7        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         12348       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      12348     |        9       |              |                 |    9       |        12348        |               |                |   CONS_LATAM |          |       7        |

    And I wait "/edm/material_global_v1" Async Queue complete

    Given I import "/edm/plant_v1" by keyFields "localPlant,sourceSystem"
      | country | localCountry | localCurrency | localPlanningRelevant | localPlant | localPlantName | localPlantType | plant | plantType | region | site | sourceSystem |
      | MX | MX | MX | X | MX01 | J&J Colombia - LADS (CO01) |   | MX01 | MP, Manufacturing Plant | MX | MX | CONS_LATAM |
      | BR | BR | BRL | X | BR14 | J&J Colombia - LADS (CO01) |   | BR14 | MP, Manufacturing Plant | CO, COLOMBIA COLOMBIA | Cali | CONS_LATAM |
      | BR | BR | BRL | X | BR12 | J&J BR-Nova Odessa - Com&Distr | DC | BR12 | DC, Distribution Center | BR, BRAZIL BRAZIL | Nova Odessa DC | CONS_LATAM |
      | BR | BR | BRL | X | BR13 | J&J BR-Nova Odessa - Com&Distr | DC | BR62 | DC, Distribution Center | BR, BRAZIL BRAZIL | Nova Odessa DC | CONS_LATAM |
      | BR | BR | BRL | X | BR12 | J&J BR-Nova Odessa - Com&Distr | DC | BR12 | DC, Distribution Center | BR, BRAZIL BRAZIL | Nova Odessa DC | CONS_LATAM |
      | BR | BR | BRL | X | BR13 | J&J BR-Nova Odessa - Com&Distr | DC | BR62 | DC, Distribution Center | BR, BRAZIL BRAZIL | Nova Odessa DC | CONS_LATAM |
      | BR | BR | BRL | X | CO01 | J&J BR-Nova Odessa - Com&Distr | DC | BR62 | DC, Distribution Center | BR, BRAZIL BRAZIL | Nova Odessa DC | CONS_LATAM |
      | BR | BR | BRL | X | MX02 | J&J BR-Nova Odessa - Com&Distr | DC | BR62 | DC, Distribution Center | BR, BRAZIL BRAZIL | Nova Odessa DC | CONS_LATAM |
      | BR | BR | BRL | X | CR01 | J&J BR-Nova Odessa - Com&Distr | DC | BR62 | DC, Distribution Center | BR, BRAZIL BRAZIL | Nova Odessa DC | CONS_LATAM |
      | BR | BR | BRL | X | PE01 | J&J BR-Nova Odessa - Com&Distr | DC | BR62 | DC, Distribution Center | BR, BRAZIL BRAZIL | Nova Odessa DC | CONS_LATAM |
      | BR | BR | BRL |   | BR22 | J&J BR-Nova Odessa - Com&Distr | DC | BR22 | DC, Distribution Center | BR, BRAZIL BRAZIL | Nova Odessa DC | CONS_LATAM |


    And I wait "/edm/plant_v1" Async Queue complete

    Given I import "/plan/cns_material_plan_status" by keyFields "sourceSystem,localMaterialNumber,localPlant"
      | active | dpRelevant | localMaterialNumber |   localParentCode | localPlant | materialNumber | noPlanRelevant | parentActive |   ppc   | sourceSystem | spRelevant |
      |   X    |            |        58752        | 78910109411230000 |     MX02   |                |                |        X     | 58722   | CONS_LATAM   |     X      |
      |   X    |            |        97360        | 78910100877220000 |     CO13   |                |                |        X     | 97360   | CONS_LATAM   |     X      |
      |   X    |            |        57039        | 78910100877220000 |     MX02   |                |                |        X     | 57039   | CONS_LATAM   |     X      |
      |   X    |            |        80990        | 78910100877220000 |     BR12   |      80990     |        X       |        X     |         | CONS_LATAM   |            |
      |   X    |            |        91732        | 78910100877220000 |     BR12   |                |        X       |        X     | 91732   | CONS_LATAM   |            |
      |   X    |            |        60520        | 78910100877220000 |     BR13   |      60520     |        X       |        X     |         | CONS_LATAM   |            |
      |   X    |            |        528395       | 78910100877220000 |     CO01   |                |        X       |        X     | 528395  | CONS_LATAM   |            |
      |   X    |            |        58753        | 78910100877220000 |     MX02   |      58753     |        X       |        X     | 58753   | CONS_LATAM   |     X      |
      |   X    |            |        58754        | 78910100877220000 |     MX02   |      58754     |        X       |        X     | 58754   | CONS_LATAM   |     X      |
      |   X    |            |        58755        | 78910100877220000 |     CR01   |      58755     |        X       |        X     | 58755   | CONS_LATAM   |     X      |
      |   X    |            |        58756        | 78910100877220000 |     PE01   |      58756     |        X       |        X     | 58756   | CONS_LATAM   |     X      |
      |   X    |            |        58799        | 78910100877220000 |     MX02   |      58799     |        X       |        X     | 58799   | CONS_LATAM   |     X      |
      |   X    |            |        12345        | 78910100877220000 |     MX01   |      12345     |                |        X     | 12345   | CONS_LATAM   |            |
      |   X    |            |        12346        | 78910100877220000 |     MX01   |      12346     |        X       |        X     | 12346   | CONS_LATAM   |     X      |
      |   X    |            |        12347        | 78910100877220000 |     MX01   |      12347     |        X       |        X     | 12347   | CONS_LATAM   |     X      |
      |   X    |            |        12347        | 78910100877220000 |     MXX1   |      12347     |                |        X     | 12347   | CONS_LATAM   |            |
      |   X    |            |        12348        | 78910100877220000 |     MX01   |      12348     |                |        X     | 12348   | CONS_LATAM   |            |


    And I wait "/plan/cns_material_plan_status" Async Queue complete

    Given I import "/plan/cns_plan_object_filter" by keyFields "sourceObjectAttribute1,sourceObjectAttribute1Value,sourceObjectAttribute2,sourceObjectAttribute2Value,sourceObjectTechName,sourceSystem"
     | comments | inclusionExclusion | sourceObjectAttribute1 | sourceObjectAttribute1Value | sourceObjectAttribute2 | sourceObjectAttribute2Value | sourceObjectTechName | sourceSystem |
     |          |        I           |        plntCd          |              DO01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              AR01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              PA03           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              MX01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              PA01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR19           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              PE01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CR01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              AR01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CO02           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR14           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              EC01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              MX01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              AR01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CR01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              EC01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              PA01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR16           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              UY01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              UY01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR07           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              PA01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CL01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              UY01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CO01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              DO01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR16           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              PE01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              GT01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              PA03           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CR01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CR01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR19           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CO01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              DO01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              MX02           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              DO01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              PE01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR25           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CL01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR16           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              GT01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              PA03           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR25           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              MX01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              GT02           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CO02           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              UY01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR07           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              MX02           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CL01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CL01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              GT01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              MX02           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR25           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CR02           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CO01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CR02           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              AR02           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              AR02           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CR02           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              EC01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              GT02           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CO01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              AR02           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR07           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR07           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CR02           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              MX01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              AR02           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              AR01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              EC01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              GT02           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              GT02           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR25           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              PA01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR16           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              CO02           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              MX02           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              GT01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              BR19           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              PE01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        E           |        plntCd          |              AB01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        xxxxxx          |              MXX1           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_LATAM |
     |          |        I           |        plntCd          |              MXX1           |          xxxxxxxx      |             GGG             |   purchase_order_oa  |   CONS_LATAM |


    And I wait "/plan/cns_plan_object_filter" Async Queue complete

    Given I import "/plan/cns_tlane_control" by keyFields "sequenceNumber,tlaneName"
      | sequenceNumber | tlaneName | validFrom | validTo | originLocation | supSys | supSysVendor | supSysCustomer | destinationLocation | recSys | recSysVendor | recSysCustomer |  | mode | leadTime | triangulationDetail | processTypeId | sourceSystemCriticalParameters | trigSysTransaction | trigSysPlant | trigSysVendor | trigSysCustomer | trigSysShipTo | criticalParameter1Table | criticalParameter1Field | criticalParameter1Low | criticalParameter1High | criticalParameter1Operator | criticalParameter1IE | criticalParameter2Table | criticalParameter2Field | criticalParameter2Low | criticalParameter2High | criticalParameter2Operator | criticalParameter2IE | criticalParameter3Table | criticalParameter3Field | criticalParameter3Low | criticalParameter3High | criticalParameter3Operator | criticalParameter3IE | criticalParameter4Table | criticalParameter4Field | criticalParameter4Low | criticalParameter4High | criticalParameter4Operator | criticalParameter4IE | criticalParameter5Table | criticalParameter5Field | criticalParameter5Low | criticalParameter5High | criticalParameter5Operator | criticalParameter5IE | criticalParameter6Table | criticalParameter6Field | criticalParameter6Low | criticalParameter6High | criticalParameter6Operator | criticalParameter6IE | criticalParameter7Table | criticalParameter7Field | criticalParameter7Low | criticalParameter7High | criticalParameter7Operator | criticalParameter7IE | criticalParameter8Table | criticalParameter8Field | criticalParameter8Low | criticalParameter8High | criticalParameter8Operator | criticalParameter8IE | criticalParameter9Table | criticalParameter9Field | criticalParameter9Low | criticalParameter9High | criticalParameter9Operator | criticalParameter9IE | criticalParameter10Table | criticalParameter10Field | criticalParameter10Low | criticalParameter10High | criticalParameter10Operator | criticalParameter10IE |
      | 1 | CO01toMX02 | 1012018 | 31/12/2998 | CONS_LATAM_CO01 |  |  |  | CONS_LATAM_MX02 |  |  |  |  | Ship | 35 | Yes | 1 | CONS_LATAM | Purchase Order | MX01 |  |  |  | cns_prod_loc_attrib | primarySupplierPlantCode | CO01 |  | = | I | material_plant | localPlant | MX02 |  | = | I | material_plant | localProcurementType | F |  | = | I | material_plant | localMrpType | X0 |  | = | I | material_plant | localMrpController | 999 |  | = | E | material_plant | localSpecialProcurementType | 44 |  | = | I | material_plant | localPlantStatus | 08,11,13 |  | = | I |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | |
      | 2 | CO01toEC01 | 1012018 | 31/12/2998 | CONS_LATAM_CO01 |  |  |  | CONS_LATAM_EC01 |  |  |  |  | Ship | 28 | No | 1 | CONS_LATAM |  |  |  |  |  | cns_prod_loc_attrib | primarySupplierPlantCode | CO01 |  | = | I | material_plant | localPlant | EC01 |  | = | I | material_plant | localProcurementType | F |  | = | I | material_plant | localMrpType | X0 |  | = | I | material_plant | localMrpController | 999 |  | = | E | material_plant | localSpecialProcurementType | 44 |  | = | I | material_plant | localPlantStatus | 08,11,13 |  | = | I |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | |
      | 3 | CO01toPE01 | 1012018 | 31/12/2998 | CONS_LATAM_CO01 |  |  |  | CONS_LATAM_PE01 |  |  |  |  | Ship | 28 | No | 1 | CONS_LATAM |  |  |  |  |  | cns_prod_loc_attrib | primarySupplierPlantCode | CO01 |  | = | I | material_plant | localPlant | PE01 |  | = | I | material_plant | localProcurementType | F |  | = | I | material_plant | localMrpType | X0 |  | = | I | material_plant | localMrpController | 999 |  | = | E | material_plant | localSpecialProcurementType | 44 |  | = | I | material_plant | localPlantStatus | 08,11,13 |  | = | I |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | |
      | 4 | CO01toCO02 | 1012018 | 31/12/2998 | CONS_LATAM_CO01 |  |  |  | CONS_LATAM_CO02 |  |  |  |  | Ship | 1 | No | 1 | CONS_LATAM |  |  |  |  |  | cns_prod_loc_attrib | primarySupplierPlantCode | CO01 |  | = | I | material_plant | localPlant | CO02 |  | = | I | material_plant | localProcurementType | F |  | = | I | material_plant | localMrpType | X0 |  | = | I | material_plant | localMrpController | 999 |  | = | E | material_plant | localSpecialProcurementType | 44 |  | = | I | material_plant | localPlantStatus | 08,11,13 |  | = | I |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | |
      | 5 | CO01toCL01 | 1012018 | 31/12/2998 | CONS_LATAM_CO01 |  |  |  | CONS_LATAM_CL01 |  |  |  |  | Ship | 21 | No | 1 | CONS_LATAM |  |  |  |  |  | cns_prod_loc_attrib | primarySupplierPlantCode | CO01 |  | = | I | material_plant | localPlant | CL01 |  | = | I | material_plant | localProcurementType | F |  | = | I | material_plant | localMrpType | X0 |  | = | I | material_plant | localMrpController | 999 |  | = | E | material_plant | localSpecialProcurementType | 44 |  | = | I | material_plant | localPlantStatus | 08,11,13 |  | = | I |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | |
      | 6 | CO01toUY01 | 1012018 | 31/12/2998 | CONS_LATAM_CO01 |  |  |  | CONS_LATAM_UY01 |  |  |  |  | Ship | 51 | No | 1 | CONS_LATAM |  |  |  |  |  | cns_prod_loc_attrib | primarySupplierPlantCode | CO01 |  | = | I | material_plant | localPlant | UY01 |  | = | I | material_plant | localProcurementType | F |  | = | I | material_plant | localMrpType | X0 |  | = | I | material_plant | localMrpController | 999 |  | = | E | material_plant | localSpecialProcurementType | 44 |  | = | I | material_plant | localPlantStatus | 08,11,13 |  | = | I |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | |
      | 10 | CO01toCR01 | 1012018 | 31/12/2998 | CONS_LATAM_CO01 |  |  |  | CONS_LATAM_CR01 |  |  |  |  | Ship | 40 | Yes | 1 | CONS_LATAM | Purchase Order | CR02 |  |  |  | cns_prod_loc_attrib | primarySupplierPlantCode | CO01 |  | = | I | material_plant | localPlant | CR01 |  | = | I | material_plant | localProcurementType | F |  | = | I | material_plant | localMrpType | X0 |  | = | I | material_plant | localMrpController | 999 |  | = | E | material_plant | localSpecialProcurementType | 44 |  | = | I | material_plant | localPlantStatus | 08,11,13 |  | = | I |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | |
      | 11 | CO01toGT01 | 1012018 | 31/12/2998 | CONS_LATAM_CO01 |  |  |  | CONS_LATAM_GT01 |  |  |  |  | Ship | 40 | Yes | 1 | CONS_LATAM | Purchase Order | GT02 |  |  |  | cns_prod_loc_attrib | primarySupplierPlantCode | CO01 |  | = | I | material_plant | localPlant | GT01 |  | = | I | material_plant | localProcurementType | F |  | = | I | material_plant | localMrpType | X0 |  | = | I | material_plant | localMrpController | 999 |  | = | E | material_plant | localSpecialProcurementType | 44 |  | = | I | material_plant | localPlantStatus | 08,11,13 |  | = | I |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | |
      | 20 | BR12toMX02 | 1012018 | 31/12/2998 | CONS_LATAM_BR12 |  |  |  | CONS_LATAM_MX02 |  |  |  |  | Ship | 37 | Yes | 1 | CONS_LATAM | Purchase Order | MX01 |  |  |  | cns_prod_loc_attrib | primarySupplierPlantCode | BR12 |  | = | I | material_plant | localPlant | MX02 |  | = | I | material_plant | localProcurementType | F |  | = | I | material_plant | localMrpType | X0 |  | = | I | material_plant | localMrpController | 999 |  | = | E | material_plant | localSpecialProcurementType | 40 |  | = | I | material_plant | localPlantStatus | 08,11,13 |  | = | I |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | |
      | 28 | PA03toGT01 | 1012018 | 31/12/2998 | CONS_LATAM_PA03 |  |  |  | CONS_LATAM_GT01 |  |  |  |  | Ship | 27 | Yes | 1 | CONS_LATAM | Purchase Order | GT02 |  |  |  | cns_prod_loc_attrib | primarySupplierPlantCode | PA03 |  | = | I | material_plant | localPlant | GT01 |  | = | I | material_plant | localProcurementType | F |  | = | I | material_plant | localMrpType | X0 |  | = | I | material_plant | localMrpController | 999 |  | = | E | material_plant | localSpecialProcurementType | 39 |  | = | I | material_plant | localPlantStatus | 08,11,13 |  | = | I |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | |
      | 29 | PA03toCR01 | 1012018 | 31/12/2998 | CONS_LATAM_PA03 |  |  |  | CONS_LATAM_CR01 |  |  |  |  | Ship | 20 | Yes | 1 | CONS_LATAM | Purchase Order | CR02 |  |  |  | cns_prod_loc_attrib | primarySupplierPlantCode | PA03 |  | = | I | material_plant | localPlant | CR01 |  | = | I | material_plant | localProcurementType | F |  | = | I | material_plant | localMrpType | X0 |  | = | I | material_plant | localMrpController | 999 |  | = | E | material_plant | localSpecialProcurementType | 39 |  | = | I | material_plant | localPlantStatus | 08,11,13 |  | = | I |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | |

    And I wait "/plan/cns_tlane_control" Async Queue complete

    Given I import "/plan/cns_tlane_control_triangulation" by keyFields "sequenceNumber,stepNumber,tlaneName"
      | sequenceNumber | stepNumber | tlaneName | originLocation | destinatonLocation  |
      | 1 | 1 | CO01toMX02 | CONS_LATAM_CO01 | CONS_LATAM_MX01   |
      | 1 | 2 | CO01toMX02 | CONS_LATAM_MX01 | CONS_LATAM_MX02   |
      | 10 | 1 | CO01toCR01 | CONS_LATAM_CO01 | CONS_LATAM_CR02  |
      | 10 | 2 | CO01toCR01 | CONS_LATAM_CR02 | CONS_LATAM_CR01  |
      | 11 | 1 | CO01toGT01 | CONS_LATAM_CO01 | CONS_LATAM_GT02  |
      | 11 | 2 | CO01toGT01 | CONS_LATAM_GT02 | CONS_LATAM_GT01  |
      | 20 | 1 | BR12toMX03 | CONS_LATAM_BR12 | CONS_LATAM_MX01  |
      | 20 | 2 | BR12toMX03 | CONS_LATAM_MX01 | CONS_LATAM_MX02  |
      | 28 | 1 | PA03toGT01 | CONS_LATAM_PA03 | CONS_LATAM_GT02  |
      | 28 | 2 | PA03toGT01 | CONS_LATAM_GT02 | CONS_LATAM_GT01  |
      | 29 | 1 | PA03toCR01 | CONS_LATAM_PA03 | CONS_LATAM_CR02  |
      | 29 | 2 | PA03toCR01 | CONS_LATAM_CR02 | CONS_LATAM_CR01  |

    And I wait "/plan/cns_tlane_control_triangulation" Async Queue complete

    Given I import "/edm/source_system_v1" by keyFields "localSourceSystem"
      | localSourceSystem | localSourceSystemName | modifiedBy | sourceSystem | sourceSystemName | sourceSystemType | status | timeStamp | valid | LOCAL_SOURCE_SYSTEM | LOCAL_SOURCE_SYSTEM_NAME | SOURCE_SYSTEM |  | SOURCE_SYSTEM_NAME | comments | flatFile |
      | [MDD FASE] | JDE EDO - FASE - JDE ENTERPRISEONE -PROD (JDE 8.12) |  | MDD_FASE |  |  |  |  |  |  |  |  |  |  |  |  |
      | hcs | USROTC |  | MDD_USROTC |  |  |  |  |  |  |  |  |  |  |  |  |
      | btbjapan | BTB JAPAN |  | MDD_BTBJAPAN |  |  |  |  |  |  |  |  |  |  |  |  |
      | [MDD USROTC] | HCS SAP-ECC-PROD-MP2 (USROTC) |  | MDD_USROTC |  |  |  |  |  |  |  |  |  |  |  |  |
      | fase | JDE GMED 8.12 |  | MDD_FASE |  |  |  |  |  |  |  |  |  |  |  |  |
      | [EMS] | EMS |  | EMS | Enterprise Master Data Management System | NGEMS |  |  |  |  |  |  |  |  |  |  |
      | [MDD ENDO] | JDE ETHICON ENDO - JDE ENTERPRISEONE-PROD |  | MDD_ENDO |  |  |  |  |  |  |  |  |  |  |  |  |
      | [MD DePuy Spine JDE XE] | Spine |  | MDDePuy | MD DePuy Ent | JDE |  |  |  |  |  |  |  |  |  |  |
      | btb | BTB NA |  | MDD_BtB |  |  |  |  |  |  |  |  |  |  |  |  |
      | ems | EMS |  | EMS | Enterprise Master Data Management System | EMS |  |  |  |  |  |  |  |  |  |  |
      | mars | MARS |  | MDD_MARS |  |  |  |  |  |  |  |  |  |  |  |  |
      | Project_One | Project One |  | CONS_LATAM | Consumer Latam Ent | SAP |  |  |  |  |  |  |  |  |  |  |
      | endo | JDE ENDO E1 |  | MDD_ENDO |  |  |  |  |  |  |  |  |  |  |  |  |
      | [Consumer LATAM] | Consumer Latam |  | CONS_LATAM | Consumer Latam Ent | NGEMS |  |  |  |  |  |  |  |  |  |  |
      | [BtB] | Back to Basics - MDG |  | MDD_BtB |  |  |  |  |  |  |  |  |  |  |  |  |
      | [MDD MARS] | MARS-SAP |  | MDD_MARS |  |  |  |  |  |  |  |  |  |  |  |  |

    And I wait "/edm/source_system_v1" Async Queue complete

    When I submit task with xml file "xml/omp/GDMStockPurchaseOrder_preAggregationCuration.xml" and execute file "jar/pangea-view.jar"

    When I submit aggregation task with xml file "xml/omp/GDMStockPurchaseOrder_aggregation.xml"

    When I submit task with xml file "xml/omp/OMPGdmStockPurchaseOrder.xml" and execute file "jar/pangea-view.jar"

    Then A file is found on sink application with name "GDMStock.tsv"

    And I check file data for filename "GDMStock.tsv" by keyFields "stockId"
      |      transitDate    |    processTypeId  | returnsQuantity |          inventoryLinkGroupId          | vendorId | batchId | activeOPRERP | activeSOPERP | transferQuantity | qualityQuantity |                processId                          |   locationId    | consignment | certaintyId | erpOrderId | quantity | productId | stockType |      receiptDate    | active | blockedQuantity | unrestrictedQuantity |                  stockId               | restrictedQuantity |      startDate      |
      | 1980/01/01 00:00:00 | InternalTransport |         0.0     | 57039/CONS_LATAM_MX02/3000793990/40/1  |  1189    |         |      YES     |      NO      |        0.0       |        0.0      | SU/57039/CONS_LATAM_MX02/1189/Default             | CONS_LATAM_MX02 |      YES    |     LE      | 3000793990 |  1800.0  |   57039   | movement  | 2017/01/03 00:00:00 |  YES   |      0.0        |         0.0          | 57039/CONS_LATAM_MX02/3000793990/40/1  |       0.0          | 2017/01/04 00:00:00 |
      | 1980/01/01 00:00:00 | VendorTransport   |         0.0     |                                        |  6109    |         |      YES     |      NO      |        0.0       |        0.0      | TR/58756/CONS_LATAM_PE01/CONS_LATAM_MX01/Default  | CONS_LATAM_PE01 |      YES    |     BE      | 3000793200 |  1000.0  |   58756   | movement  | 2017/01/03 00:00:00 |  YES   |      0.0        |         0.0          | 58756/CONS_LATAM_PE01/3000793200/10/1  |       0.0          | 2017/01/04 00:00:00 |
      | 1980/01/01 00:00:00 | ExternalTransport |         0.0     | 528395/CONS_LATAM_CO01/3000793995/20/1 |  1189    |         |      YES     |      NO      |        0.0       |        0.0      | TR/528395/CONS_LATAM_CO01/CONS_LATAM_BR12/Default | CONS_LATAM_CO01 |      YES    |     LE      | 3000793995 |  900.0   |   528395  | movement  | 2017/01/03 00:00:00 |  YES   |      0.0        |         0.0          | 528395/CONS_LATAM_CO01/3000793995/20/1 |       0.0          | 2017/01/04 00:00:00 |
      | 1980/01/01 00:00:00 | ExternalTransport |         0.0     | 80990/CONS_LATAM_BR12/3000793998/20/1  |  1189    |         |      YES     |      NO      |        0.0       |        0.0      | TR/80990/CONS_LATAM_BR12/CONS_LATAM_BR12/Default  | CONS_LATAM_BR12 |      YES    |     LE      | 3000793998 |  2100.0  |   80990   | movement  | 2017/01/03 00:00:00 |  YES   |      0.0        |         0.0          | 80990/CONS_LATAM_BR12/3000793998/20/1  |       0.0          | 2017/01/04 00:00:00 |
      | 1980/01/01 00:00:00 | VendorTransport   |         0.0     |                                        |  6109    |         |      YES     |      NO      |        0.0       |        0.0      | TR/58755/CONS_LATAM_CR01/CONS_LATAM_MX01/Default  | CONS_LATAM_CR01 |      YES    |     BE      | 3000793993 |  500.0   |   58755   | movement  | 2017/01/03 00:00:00 |  YES   |      0.0        |         0.0          | 58755/CONS_LATAM_CR01/3000793993/11/1  |       0.0          | 2017/01/04 00:00:00 |
      | 1980/01/01 00:00:00 | VendorTransport   |         0.0     |                                        |  6109    |         |      YES     |      NO      |        0.0       |        0.0      | TR/58755/CONS_LATAM_CR01/CONS_LATAM_MX01/Default  | CONS_LATAM_CR01 |      YES    |     BE      | 3000793100 |  1500.0  |   58755   | movement  | 2017/01/03 00:00:00 |  YES   |      0.0        |         0.0          | 58755/CONS_LATAM_CR01/3000793100/10/1  |       0.0          | 2017/01/04 00:00:00 |
      | 1980/01/01 00:00:00 | VendorTransport   |         0.0     | 58752/CONS_LATAM_MX02/3000793111/40/1  |  6109    |         |      YES     |      NO      |        0.0       |        0.0      | TR/58752/CONS_LATAM_MX02/CONS_LATAM_MX01/Default  | CONS_LATAM_MX02 |      NO     |     BE      | 3000793111 |  1800.0  |   58752   | movement  | 2017/01/03 00:00:00 |  YES   |      0.0        |         0.0          | 58752/CONS_LATAM_MX02/3000793111/40/1  |       0.0          | 2017/01/04 00:00:00 |
      | 1980/01/01 00:00:00 | VendorTransport   |         0.0     |                                        |  6109    |         |      YES     |      NO      |        0.0       |        0.0      | TR/58753/CONS_LATAM_MX02/CONS_LATAM_MX01/Default  | CONS_LATAM_MX02 |      YES    |     BE      | 3000793991 |  1800.0  |   58753   | movement  | 2017/01/03 00:00:00 |  YES   |      0.0        |         0.0          | 58753/CONS_LATAM_MX02/3000793991/20/1  |       0.0          | 2017/01/04 00:00:00 |
      | 1980/01/01 00:00:00 | VendorTransport   |         0.0     |                                        |  6109    |         |      YES     |      NO      |        0.0       |        0.0      | TR/58752/CONS_LATAM_MX02/CONS_LATAM_MX01/Default  | CONS_LATAM_MX02 |      YES    |     BE      | 3000793997 |  1968.0  |   58752   | movement  | 2017/01/03 00:00:00 |  YES   |      0.0        |         0.0          | 58752/CONS_LATAM_MX02/3000793997/10/1  |       0.0          | 2017/01/04 00:00:00 |

    Then I check region data "/dev/plan/edm_failed_data" by keyFields "errorCode,functionalArea,interfaceID,key1,key2,key3,key4,key5,sourceSystem"
      | errorCode |              errorValue                                                                    | functionalArea |  interfaceID              | key1       | key2     | key3 | key4 | key5 | sourceSystem |
      |  PO9      | Material Global V1 - materialNumber and primaryPlanningCode are empty                      | SP             | OMPGdmStock_PurchaseOrder | CONS_LATAM |3000793211|58799 |      |      | CONS_LATAM   |

    And I will remove all data with region "/edm/purchase_order_oa_v1"

    And I will remove all data with region "/edm/material_global_v1"

    And I will remove all data with region "/edm/plant_v1"

    And I will remove all data with region "/plan/cns_material_plan_status"

    And I will remove all data with region "/plan/cns_spl_pln_loc"

    And I will remove all data with region "/plan/cns_plan_object_filter"

    And I will remove all data with region "/edm/purchase_order_oa_v1_aggregation"

    And I will remove all data with region "/omp/gdm_stock_purchase_order"

    And I will remove all data with region "/edm/purchase_order_oa_v1_preAggregation"

    And I will remove all data with region "/dev/plan/edm_failed_data"

    And I will remove all data with region "/plan/cns_tlane_control"

    And I will remove all data with region "/plan/cns_tlane_control_triangulation"

    And I will remove all data with region "/edm/source_system_v1"

    And I will remove the test file on sink application "GDMStock.tsv"

