@pangea @AEAZ-6823
Feature: GDMDemand_STO AEAZ-6823

  @Scenario1
  Scenario: full load curation
    Given I import "/edm/purchase_order_oa_v1" by keyFields "delvSchedCntNbr,evTypeCd,matlMvmtNum,matlMvmtSeqNbr,matlMvmttYr,poLineNbr,poNum,sourceSystem"
      | sourceSystem | poNum       | poLineNbr | evTypeCd | matlMvmttYr | matlMvmtNum | matlMvmtSeqNbr | delvSchedCntNbr | poCatTypeCd | poTypeCd | crtOnDt  | supNum | prchsngOrgNum | prchsngGrpNum | prchsngCoCd | crncyCd | poDt     | vldFromDt | vldToDt | suplVendNum | suplPlntCd | rlseCmpltInd | rlseDocInd | delInd | matlNum | plntCd | slocCd | intrnlRefNum | poLineQty | poUomCd | localNumerator | localDenominator | stkTypeCd | delvCmpltInd | lineItemTypeCd | acctAsgnmtCatCd | prinPrchAgmtNum | prinPrchAgmtLineNbr | localBaseUOM | delvAddrNum | localPDT | localSpecialStock | cnfrmCd | subcntrcInd | localdelvAddrNum | prDocId    | prLineNbr | localBrazilianNCMCode | isuSlocCd | poHistCatCd | localMovementType | localPostingDate | recvEaQty | cnfrmSeqNbr | delvDt   | cnfrmQty | mrpAdjQty | localCreationIndVendorConf | slsOrdrNum | slsOrdrLineNbr | vendBtchNum | localdelvDt | schdQty | recvQty | localPurchaseReq | localPurchaseReqItem | stkTfrRecvQty | localmrpAdjQty | grLeadTimeDays | custNum | localSeqNumActAsgn | localSeqNumVendConf |
      | CONS_LATAM   | 3000793997  | 10        | 8        | 2017        | 5006382844  | 1              | 1               | F           | UB       | 20180102 | 6109   | MX01          | M39           | 8302        | MXN     | 20170102 |           |         |             | MX01       |              |            |        | 58752   | MX01   | MX01   |              | 1968      | EA      | 1              | 1                | X         | X            | 2              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 10        |                       |           | E           | 101               | 20170103         | 0         |             | 20170103 | 0        |           |                            |            |                |             | 20180117    |         |         |                  |                      |               |                | 1              | 7846    |                    |                     |
      | CONS_LATAM   | 3000793992  | 20        | 8        | 2017        | 5006382844  | 1              | 1               | F           | UB       | 20170102 | 6109   | MX01          | M39           | 8302        | MXN     | 20170102 |           |         |             | MX01       |              |            |        | 58754   | MX01   | MX01   |              | 3000      | EA      | 1              | 1                | X         | X            | 2              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 20        |                       |           | E           | 101               | 20170103         | 3000      |             | 20170103 | 0        |           |                            |            |                |             | 20180117    |         |         |                  |                      |               |                | 1              | 1456    |                    |                     |
      | CONS_LATAM   | 3000793993  | 11        | 8        | 2017        | 5006382844  | 1              | 1               | F           | UB       | 20170102 | 6109   | MX01          | M39           | 8302        | MXN     | 20170102 |           |         |             | MX01       |              |            |        | 58755   | MX01   | MX01   |              | 1000      | EA      | 1              | 1                | X         | X            | 2              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 11        |                       |           | E           | 101               | 20170103         | 200       |             | 20170103 | 0        |           |                            |            |                |             | 20180117    |         |         |                  |                      |               |                | 1              | 5478    |                    |                     |
      | CONS_LATAM   | 3000793993  | 11        | 8        | 2017        | 5006382845  | 1              | 1               | F           | UB       | 20170102 | 6109   | MX01          | M39           | 8302        | MXN     | 20170102 |           |         |             | MX01       |              |            |        | 58755   | MX01   | MX01   |              | 1000      | EA      | 1              | 1                | X         | X            | 2              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 11        |                       |           | E           | 101               | 20170103         | 300       |             | 20170103 | 0        |           |                            |            |                |             | 20180117    |         |         |                  |                      |               |                | 1              | 5478    |                    |                     |
      | CONS_LATAM   | 3000793999  | 10        | 8        | 2017        | 5006382844  | 1              | 1               | L           | ZLA      | 20170102 | 1189   | BR12          | M39           | 8302        | BR      | 20170102 |           |         |             | BR12       |              | 1          |        | 96161   | BR12   | BR12   |              | 3000      | EA      | 1              | 1                | X         | X            | K              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 10        |                       |           | E           | 101               | 20170103         | 0         |             | 20170103 | 1000     |           |                            |            |                |             | 20180117    |         |         |                  |                      |               |                | 1              | 7865    |                    |                     |
      | CONS_LATAM   | 3000793995  | 20        | 8        | 2017        | 5006382844  | 1              | 1               | L           | ZNB      | 20170102 | 1189   | BR12          | M39           | 8302        | BR      | 20170102 |           |         |             | BR19       |              | 1          |        | 528395  | BR19   | BR12   |              | 1000      | EA      | 1              | 1                | X         | X            | K              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 20        |                       |           | E           | 101               | 20170103         | 100       |             | 20170103 | 0        |           |                            |            |                |             | 20180117    |         |         |                  |                      |               |                | 1              | 4789    |                    |                     |
      | CONS_LATAM   | 3000793990  | 40        | 8        | 2017        | 5006382844  | 1              | 1               | L           | UB       | 20170102 | 1189   | BR14          | M39           | 8302        | BR      | 20170102 |           |         |             | BR14       |              | 1          |        | 57039   | BR14   | BR14   |              | 2000      | EA      | 1              | 1                | X         | X            | K              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 40        |                       |           | E           | 101               | 20170103         | 200       |             | 20170103 | 0        |           |                            |            |                |             | 20180117    |         |         |                  |                      |               |                | 1              | 8974    |                    |                     |
      | CONS_LATAM   | 30007930001 | 40        | 1        | 2017        | 5006382844  | 1              | 1               | F           | NB       | 20170102 | 6109   | MX01          | M39           | 8302        | MXN     | 20170102 |           |         |             | MX01       |              |            | X      | 58752   | MX01   | MX01   |              | 2000      | EA      | 1              | 1                | X         | X            | 3              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 40        |                       |           | E           | 101               | 20170103         | 0         |             | 20170103 | 200      |           |                            |            |                |             | 20180117    |         |         |                  |                      |               |                | 1              | 9547    |                    |                     |
      | CONS_LATAM   | 3000793200  | 10        | 8        | 2017        | 5006382844  | 1              |                 | F           | UB       | 20170102 | 6109   | MX01          | M39           | 8302        | MXN     | 20170102 |           |         |             | MX01       |              |            |        | 58756   | MX01   | MX01   |              | 4000      | EA      | 1              | 1                | X         | X            | 2              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 10        |                       |           | E           | 101               | 20170103         | 500       |             | 20170103 | 0        |           |                            |            |                |             | 20180110    |         |         |                  |                      |               |                | 1              | 5588    |                    |                     |
      | CONS_LATAM   | 3000793200  | 10        | 8        | 2017        | 5006382845  | 1              |                 | F           | UB       | 20170102 | 6109   | MX01          | M39           | 8302        | MXN     | 20170102 |           |         |             | MX01       |              |            |        | 58756   | MX01   | MX01   |              | 4000      | EA      | 1              | 1                | X         | X            | 2              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 10        |                       |           | E           | 101               | 20170103         | 500       |             | 20170103 | 0        |           |                            |            |                |             | 20180110    |         |         |                  |                      |               |                | 1              | 5588    |                    |                     |
      | CONS_LATAM   | 3000793200  | 10        | 8        | 2017        | 5006382846  | 1              |                 | F           | UB       | 20170102 | 6109   | MX01          | M39           | 8302        | MXN     | 20170102 |           |         |             | MX01       |              |            |        | 58756   | MX01   | MX01   |              | 4000      | EA      | 1              | 1                | X         | X            | 2              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 10        |                       |           | E           | 101               | 20170103         | 500       |             | 20170103 | 0        |           |                            |            |                |             | 20180110    |         |         |                  |                      |               |                | 1              | 5588    |                    |                     |
      | CONS_LATAM   | 3000793200  | 10        | 8        | 2017        | 5006382847  | 1              |                 | F           | UB       | 20170102 | 6109   | MX01          | M39           | 8302        | MXN     | 20170102 |           |         |             | MX01       |              |            |        | 58756   | MX01   | MX01   |              | 4000      | EA      | 1              | 1                | X         | X            | 2              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 10        |                       |           | E           | 101               | 20170103         | 500       |             | 20170103 | 0        |           |                            |            |                |             | 20180110    |         |         |                  |                      |               |                | 1              | 5588    |                    |                     |
      | CONS_LATAM   | 3000793200  | 10        | 8        | 2017        | 5006382848  | 1              |                 | F           | UB       | 20170102 | 6109   | MX01          | M39           | 8302        | MXN     | 20170102 |           |         |             | MX01       |              |            |        | 58756   | MX01   | MX01   |              | 4000      | EA      | 1              | 1                | X         | X            | 2              |                 | 5100003715      | 4950                | EA           |             | 2        |                   |         |             |                  | 1603571115 | 10        |                       |           | E           | 101               | 20170103         | 500       |             | 20170103 | 0        |           |                            |            |                |             | 20180110    |         |         |                  |                      |               |                | 1              | 5588    |                    |                     |

    And I wait "/edm/purchase_order_oa_v1" Async Queue complete

    Given I import "/edm/material_global_v1" by keyFields "localMaterialNumber"
      | baseUom | batchManageIndicator | brand | category | division | flagForDeletion | form | franchise | globalBusinessUnit | globalDpParentCode | localBaseUom | localDpParentCode | localManufacturingTechnology | localMaterialGroup | localMaterialNumber | localMaterialType | localRefDescription                      | manufacturingTechnology | materialGroup | materialNumber | materialStatus | materialType | minRemShelfLife | parentCode | primaryPlanningCode | productFamily | refDescription | sourceSystem | subBrand | totalShelfLife |
      |         |                      |       |          | 10       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 58752               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 58752          | 8              |              | 100             |            | 58752               |               |                | CONS_LATAM   |          | 0              |
      |         |                      |       |          | 11       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 80990               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 80990          | 8              |              | 365             |            | 80990               |               |                | CONS_LATAM   |          | 1825           |
      |         |                      |       |          | 10       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 57039               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 57039          | 8              |              | 120             |            | 57039               |               |                | CONS_LATAM   |          | 11             |
      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 96161               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 96161          | 9              |              | 11              |            | 96161               |               |                | CONS_LATAM   |          | 1              |
      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 91732               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 91732          | 8              |              | 8               |            | 91732               |               |                | CONS_LATAM   |          | 2              |
      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 60520               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 60520          | 9              |              | 9               |            | 60520               |               |                | CONS_LATAM   |          | 6              |
      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 528395              | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 528395         | 9              |              | 200             | 9          | 528395              |               |                | CONS_LATAM   |          | 7              |
      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 58753               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 58753          | 9              |              | 11              |            | 58753               |               |                | CONS_LATAM   |          | 1              |
      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 58754               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 58754          | 8              |              | 8               |            | 58754               |               |                | CONS_LATAM   |          | 2              |
      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 58755               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 58755          | 9              |              | 9               |            | 58755               |               |                | CONS_LATAM   |          | 6              |
      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 58756               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 58756          | 9              |              | 10              | 9          | 58756               |               |                | CONS_LATAM   |          | 7              |
    And I wait "/edm/material_global_v1" Async Queue complete

    Given I import "/plan/cns_material_plan_status" by keyFields "localMaterialNumber,localPlant,sourceSystem"
      | active | dpRelevant | localMaterialNumber | localParentCode   | localPlant | materialNumber | noPlanRelevant | parentActive | ppc    | sourceSystem | spRelevant |
      | X      |            | 58752               | 78910109411230000 | MX01       |                |                | X            | 58722  | CONS_LATAM   | X          |
      | X      |            | 97360               | 78910100877220000 | CO13       |                |                | X            | 97360  | CONS_LATAM   | X          |
      | X      |            | 57039               | 78910100877220000 | BR14       |                |                | X            | 57039  | CONS_LATAM   | X          |
      | X      |            | 80990               | 78910100877220000 | BR12       | 80990          | X              | X            |        | CONS_LATAM   |            |
      | X      |            | 91732               | 78910100877220000 | BR12       |                | X              | X            | 91732  | CONS_LATAM   |            |
      | X      |            | 60520               | 78910100877220000 | BR13       | 60520          | X              | X            |        | CONS_LATAM   |            |
      | X      |            | 528395              | 78910100877220000 | BR19       |                | X              | X            | 528395 | CONS_LATAM   |            |
      | X      |            | 58753               | 78910100877220000 | MX01       | 58753          | X              | X            | 58753  | CONS_LATAM   | X          |
      | X      |            | 58754               | 78910100877220000 | MX01       | 58754          | X              | X            | 58754  | CONS_LATAM   | X          |
      | X      |            | 58755               | 78910100877220000 | MX01       | 58755          | X              | X            | 58755  | CONS_LATAM   | X          |
      | X      |            | 58756               | 78910100877220000 | MX01       | 58756          | X              | X            | 58756  | CONS_LATAM   | X          |
    And I wait "/plan/cns_material_plan_status" Async Queue complete

    Given I import "/plan/cns_plan_object_filter" by keyFields "sourceObjectAttribute1,sourceObjectAttribute1Value,sourceObjectAttribute2,sourceObjectAttribute2Value,sourceObjectTechName,sourceSystem"
      | comments | inclusionExclusion | sourceObjectAttribute1 | sourceObjectAttribute1Value | sourceObjectAttribute2 | sourceObjectAttribute2Value | sourceObjectTechName | sourceSystem |
      |          | I                  | plntCd                 | DO01                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | AR01                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR12                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | PA03                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | MX01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | PA01                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR19                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | PE01                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CR01                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | AR01                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CO02                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR14                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | EC01                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | MX01                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | AR01                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CR01                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | EC01                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | PA01                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR12                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR16                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | UY01                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | UY01                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR07                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | PA01                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CL01                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | UY01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CO01                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | DO01                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR16                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | PE01                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | GT01                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | PA03                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CR01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CR01                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR19                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CO01                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | DO01                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | MX02                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | DO01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | PE01                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR12                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR25                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CL01                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR16                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | GT01                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | PA03                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR25                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | MX01                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | GT02                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CO02                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | UY01                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR07                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | MX02                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CL01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CL01                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | GT01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | MX02                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR25                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CR02                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CO01                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR12                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CR02                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | AR02                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | AR02                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CR02                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | EC01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | GT02                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR12                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CO01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | AR02                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR07                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR07                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CR02                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | MX01                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | AR02                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | AR01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | EC01                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | GT02                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | GT02                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR25                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | PA01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR16                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR12                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | CO02                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | MX02                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | GT01                        | poTypeCd               | NB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR19                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | PE01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | E                  | plntCd                 | AB01                        | poTypeCd               | UB                          | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR14                        | poTypeCd               | ZNB                         | purchase_order_oa    | CONS_LATAM   |
      |          | I                  | plntCd                 | BR14                        | poTypeCd               | ZLA                         | purchase_order_oa    | CONS_LATAM   |
    And I wait "/plan/cns_plan_object_filter" Async Queue complete

    Given I import "/plan/prod_loc_min_shelf" by keyFields "localMaterialNumber,localPlant,sourceSystem"
      | localMaterialNumber | localPlant | minMinShelfLife | minShelfLife | sourceSystem |
      | 10659               | BR12       |                 | 150          | CONS_LATAM   |
      | *                   | BR01       |                 | 180          | CONS_LATAM   |
      | *                   | BR16       |                 | 270          | CONS_LATAM   |
    And I wait "/plan/prod_loc_min_shelf" Async Queue complete

    Given I import "/plan/cns_plan_unit" by keyFields "localUom,sourceSystem"
      | factor | localUom | localUomName        | planFlag | plantFlag | roundingDecimal | sourceSystem | unit   |
      | 1      | PAL      | Pallet              | SP       |           | 0               | CONS_LATAM   | PAL    |
      | 1      | KI       | Crate               | DPSP     |           | 0               | CONS_LATAM   | CA     |
      | 1      | KG       | KiloGram            | SP       |           | 6               | CONS_LATAM   | KG     |
      | 1      | CS       | Case                | DPSP     |           | 0               | CONS_LATAM   | CA     |
      | 1      | L        | `                   | SP       |           | 6               | CONS_LATAM   | L      |
      | 1      | EA       | Each                | DPSP     |           | 0               | CONS_LATAM   | EA     |
      | 1      | M2       | Square Meter        | SP       |           | 6               | CONS_LATAM   | M2     |
      | 1      | DZ       | Dozen               | SP       |           | 3               | CONS_LATAM   | DZ     |
      | 1      | TH       | Thousand            | SP       |           | 6               | CONS_LATAM   | TS     |
      | 1      | KM       | Kilometer           | SP       |           | 3               | CONS_LATAM   | KM     |
      | 1      | ZUM      | Market Control Unit | DPÂ      |           | 6               | CONS_LATAM   | LA_ZUM |
    And I wait "/plan/cns_plan_unit" Async Queue complete

    When I submit task with xml file "xml/omp/OMPGdmDemandSTO.xml" and execute file "jar/pangea-view.jar"

    Then A file is found on sink application with name "GDMDemand_STO.tsv"

    Then I check file data for filename "GDMDemand_STO.tsv" by keyFields "demandId"
#    Then I check region data "/omp/gdm_demand" by keyFields "demandId"
      | active | activeFCTERP | activeOPRERP | activeSOPERP | batchId | certaintyId | customerId | demandId                               | dueDate             | fromDueDate         | inventoryLinkGroupId                   | locationId      | minRemainingShelfLife | planningStrategy        | productId | quantity | unitId | WRK02 |
      | YES    | NO           | YES          | NO           |         | U1          | 4789       | 528395/CONS_LATAM_BR19/3000793995/20/1 | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 528395/CONS_LATAM_BR19/3000793995/20/1 | CONS_LATAM_BR19 | 200                   | ProductLocationBalanced | 528395    | 900      | EA     | BR19  |
      | YES    | NO           | YES          | NO           |         | U1          | 5478       | 58755/CONS_LATAM_MX01/3000793993/11/1  | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 58755/CONS_LATAM_MX01/3000793993/11/1  | CONS_LATAM_MX01 | 9                     | ProductLocationBalanced | 58755     | 500      | EA     | MX01  |
      | YES    | NO           | YES          | NO           |         | U1          | 8974       | 57039/CONS_LATAM_BR14/3000793990/40/1  | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 57039/CONS_LATAM_BR14/3000793990/40/1  | CONS_LATAM_BR14 | 120                   | ProductLocationBalanced | 57039     | 1800     | EA     | BR14  |
      | YES    | NO           | YES          | NO           |         | U1          | 5588       | 58756/CONS_LATAM_MX01/3000793200/10   | 2018/01/08 00:00:01 | 2018/01/08 00:00:00 | 58756/CONS_LATAM_MX01/3000793200/10   | CONS_LATAM_MX01 | 10                    | ProductLocationBalanced | 58756     | 1500     | EA     | MX01  |
      | YES    | NO           | YES          | NO           |         | U1          | 7846       | 58752/CONS_LATAM_MX01/3000793997/10/1  | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 58752/CONS_LATAM_MX01/3000793997/10/1  | CONS_LATAM_MX01 | 100                   | ProductLocationBalanced | 58752     | 1968     | EA     | MX01  |
#      | YES    | NO           | YES          | NO           |         | U1          | 4789       | 528395/CONS_LATAM_BR19/3000793995/20/1 | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 528395/CONS_LATAM_BR19/3000793995/20/1 | CONS_LATAM_BR19 | 200                   | ProductLocationBalanced | 528395    | 900      | EA     | BR19  |
#      | YES    | NO           | YES          | NO           |         | U1          | 12345      | 80990/CONS_LATAM_BR12/3000793998/20/1  | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 80990/CONS_LATAM_BR12/3000793998/20/1  | CONS_LATAM_BR12 | 365                   | ProductLocationBalanced | 80990     | 2100     | EA     | BR12  |
#      | YES    | NO           | YES          | NO           |         | U1          | 5478       | 58755/CONS_LATAM_MX01/3000793993/11/1  | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 58755/CONS_LATAM_MX01/3000793993/11/1  | CONS_LATAM_MX01 | 9                     | ProductLocationBalanced | 58755     | 500      | EA     | MX01  |
#      | YES    | NO           | YES          | NO           |         | U1          | 8974       | 57039/CONS_LATAM_BR14/3000793990/40/1  | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 57039/CONS_LATAM_BR14/3000793990/40/1  | CONS_LATAM_BR14 | 120                   | ProductLocationBalanced | 57039     | 1800     | EA     | BR14  |
#      | YES    | NO           | YES          | NO           |         | U1          | 5588       | 58756/CONS_LATAM_MX01/3000793200/10    | 2018/01/08 00:00:01 | 2018/01/08 00:00:00 | 58756/CONS_LATAM_MX01/3000793200/10    | CONS_LATAM_MX01 | 10                    | ProductLocationBalanced | 58756     | 1000     | EA     | MX01  |
#      | YES    | NO           | YES          | NO           |         | U1          | 3578       | 58752/CONS_LATAM_MX01/3000793111/40/1  | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 58752/CONS_LATAM_MX01/3000793111/40/1  | CONS_LATAM_MX01 | 100                   | ProductLocationBalanced | 58752     | 1800     | EA     | MX01  |
#      | YES    | NO           | YES          | NO           |         | U1          | 7865       | 58753/CONS_LATAM_MX01/3000793991/20/1  | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 58753/CONS_LATAM_MX01/3000793991/20/1  | CONS_LATAM_MX01 | 11                    | ProductLocationBalanced | 58753     | 1800     | EA     | MX01  |
#      | YES    | NO           | YES          | NO           |         | U1          | 7846       | 58752/CONS_LATAM_MX01/3000793997/10/1  | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 58752/CONS_LATAM_MX01/3000793997/10/1  | CONS_LATAM_MX01 | 100                   | ProductLocationBalanced | 58752     | 1968     | EA     | MX01  |
#      | YES    | NO           | YES          | NO           |         | U1          | 8521       | 58755/CONS_LATAM_MX01/3000793100/10/1  | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 58755/CONS_LATAM_MX01/3000793100/10/1  | CONS_LATAM_MX01 | 9                     | ProductLocationBalanced | 58755     | 1500     | EA     | MX01  |

#      | YES    | NO           | YES          | NO           |         | U1          | 1456       | 58754/CONS_LATAM_MX01/3000793992/20/1  | 2018/01/15 00:00:01 | 2018/01/15 00:00:00 | 58754/CONS_LATAM_MX01/3000793992/20/1  | CONS_LATAM_MX01 | 8                     | ProductLocationBalanced | 58754     | 0        | EA     | MX01  |

#    And I delete the test data
#
#    And I will remove all data with region "/omp/gdm_demand"

#    When I execute xd job to merge file "GDMDemand_STO.tsv" to "GDMDemand_STO.tsv" by keyFields "demandId"

    
        