@pangea_test @AEAZ-6830
Feature:  OMPGdmDemandSalesOrder-Curation

  Scenario: Full Load consumption

#    Given I import "/edm/sales_order_v1" by keyFields "salesOrderItem,salesOrderNo,scheduleLineItem,sourceSystem"
#      | localBillingBlock | localBillingBlockItem | localChangeDt | localCustomerGroup | localCustomerPO   | localDeliveryBlock | localDentoBase | localDistrChannel | localDivision | localDocumentCateg | localIncoTerms1 | localIncoTerms2 | localItemBillRlvnt | localItemCategory | localItemDlvRlvnt | localMaterialNumber | localNumtoBase | localOrderCreateDt | localOrderDate | localOrderReason | localOrderType | localPlant | localPricingProcedure | localRejReason | localRequestedDate | localRoute | localSDItemCurrency | localSDItemValue | localSalesGroup | localSalesOffice | localSalesOrg | localSalesUnit | localSchLineConfimQty | localSchLineQty | localScheduleLineDate | localShipToParty | localShippingPoint | localSoldToParty | localStorageLocation | localValidFromDt | localValidToDt | salesOrderItem | salesOrderNo | salesOrderQty | scheduleLineItem | sourceSystem | localRejStat | localDelvStat |
#      |                   |                       | 20160701      |                    | 4506056414        |                    | 1              | 10                | 10            | C                  |                 |                 | A                  | ZTBN              |                   | 58752               | 10             | 20160525           | 20160525       |                  | ZORB           | BR01       | ZBRA01                |                | 20160607           | BR4006     | BRL                 | 1543.23          | NE4             | BR60             | BR01          | KI             | 34                    | 0               | 20160603              | 109038           | BR01               | 174574           |                      | 0                | 0              | 490            | 116708516    | 34            | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20171020      |                    | 1322163           |                    | 1              | 10                | 10            | C                  |                 |                 | A                  | ZTBN              |                   | 57039               | 1              | 20171011           | 20171011       |                  | ZORB           | BR14       | ZBRA01                |                | 20171019           | B19029     | BRL                 | 1626.9           | SP4             | BR62             | BR01          | KI             | 0                     | 15              | 20171019              | 182493           | BR19               | 182493           |                      | 0                | 0              | 20             | 8306862      | 38            | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20171020      |                    | 8306863           |                    | 1              | 10                | 10            | C                  |                 |                 | A                  | ZLBN              |                   | 60520               | 1              | 20161121           | 20161121       |                  | ZLVE           | BR13       | ZECU01                |                | 20161121           | ECGUAY     | USE                 | 23.68            | E01             | E100             | BR01          | KI             | 1                     | 0               | 20161122              | 139938           | EC01               | 139938           |                      | 0                | 0              | 150            | 8306863      | 2020          | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20150904      |                    | 3092015           |                    | 1              | 12                | 10            | C                  |                 |                 | A                  | ZLTQ              |                   | 68062               | 1              | 20150903           | 20150903       |                  | ZLVE           | CO02       | ZCOL01                | 121            | 20150907           | C02022     | COP                 | 545.03           | C27             | CO60             | BR01          | EA             | 80                    | 80              | 20150907              | 188002           | CO02               | 188002           |                      | 0                | 0              | 180            | 116043204    | 80            | 2                | CONS_LATAM   | C            | C             |
#      |                   |                       | 0             |                    | 115689885         |                    | 1              | 10                | 11            | I                  |                 |                 | A                  | ZSRT              |                   | 84603               | 1              | 20150414           | 20150414       | 337              | ZSRT           | BR14       | ZBRA04                |                | 20171019           | B08004     | BRL                 | 2.11             | B63             | BR29             | BR01          | EA             | 1                     | 0               | 20150416              | 108733           | BR08               | 108733           |                      | 0                | 0              | 60             | 115689885    | 38            | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20171212      |                    | 412699            |                    | 1              | 11                | 10            | C                  |                 |                 | A                  | ZLBN              |                   | 68052               | 1              | 20171211           | 20171211       |                  | ZLVE           | AR02       | ZARG01                | 55             | 20171211           | AR4000     | ARS                 | 545.03           | A03             | AR12             | AR02          | KI             | 0                     | 1               | 20171211              | 147885           | AR02               | 147885           | AR02                 | 0                | 0              | 220            | 118191240    | 1             | 2                | CONS_LATAM   | C            | C             |
#      |                   |                       | 0             |                    | RESERVA 2         |                    | 1              | 10                | 10            | C                  |                 |                 |                    | ZLNR              |                   | 55882               | 1              | 20171108           | 20171108       |                  | ZRIN           | BR07       | ZRESER                |                | 20171108           | BR4058     | BRL                 | 0                | B40             | BR23             | BR01          | EA             | 465                   | 465             | 20171108              | 164383           | BR07               | 164383           |                      | 20171108         | 0              | 40             | 40075674     | 465           | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 0             |                    | 20682250          |                    | 1              | 10                | 10            | C                  |                 |                 | A                  | ZLBN              |                   | 58826               | 1              | 20150910           | 20150910       |                  | ZLVE           | CO02       | ZCOL01                |                | 20150912           | C02001     | COP                 | 98616            | C03             | CO10             | CO01          | EA             | 24                    | 24              | 20150912              | 138575           | CO02               | 138575           |                      | 0                | 0              | 50             | 116058637    | 24            | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20180116      |                    | OC 377830         |                    | 1              | 10                | 10            | C                  |                 |                 | A                  | ZLBN              |                   | 89365               | 1              | 20180115           | 20180115       |                  | ZLVE           | AR02       | ZARW01                |                | 20180115           | AR4000     | ARS                 | 623.48           | A03             | AR12             | AR02          | KI             | 0                     | 1               | 20180115              | 173175           | AR02               | 173175           | AR02                 | 0                | 0              | 120            | 118270487    | 1             | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20160229      |                    | 1-1228302-22      |                    | 1              | 10                | 10            | C                  |                 |                 | A                  | ZLBN              |                   | 68052               | 1              | 20160229           | 20160229       |                  | ZLVE           | CO02       | ZCOL01                |                | 20160302           | C02001     | COP                 | 196368           | C08             | CO15             | CO01          | EA             | 24                    | 24              | 20160302              | 180835           | CO02               | 180835           |                      | 0                | 0              | 10             | 116488036    | 24            | 1                | CONS_LATAM   | N            | N             |
#      | 8                 |                       | 0             |                    | 166657            |                    | 1              | 11                | 10            | H                  |                 |                 | B                  | ZRBN              |                   | 65759               | 1              | 20170605           | 20170605       | 567              | ZRET           | BR07       | ZBRA16                |                | 20170605           | BR4004     | BRL                 | 1549.94          | NE5             | BR60             | BR01          | KI             | 19                    | 19              | 20170605              | 145918           | BR07               | 145918           | BR01                 | 0                | 0              | 40             | 61622476     | 19            | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20160428      |                    | 1131              |                    | 1              | 10                | 11            | C                  |                 |                 | A                  | ZLBN              |                   | 1009252             | 1              | 20160428           | 20160428       |                  | ZLVE           | AR03       | ZARG03                |                | 20160428           | AR1000     | ARS                 | 1236.24          | A11             | AR14             | AR02          | KI             | 0                     | 4               | 20160428              | 189036           | AR03               | 189036           | AR01                 | 0                | 0              | 100            | 116633136    | 4             | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 0             |                    | 46022657960000000000       |                    | 1              | 10                | 10            | C                  |                 |                 | A                  | ZLBN              |                   | 88281               | 1              | 20160825           | 20160825       |                  | ZLVE           | EC01       | ZECU01                |                | 20160825           | ECGUAY     | USE                 | 61               | E01             | E100             | EC01          | KI             | 1                     | 0               | 20160826              | 139940           | EC01               | 139940           |                      | 0                | 0              | 210            | 116953465    | 1             | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20171214      |                    | 3000826207-1      |                    | 1              | 12                | 10            | C                  |                 |                 | A                  | ZLBN              |                   | 57132               | 1              | 20171206           | 20171206       |                  | ZLVE           | PY01       | ZPRY01                |                | 20171206           | PY0001     | PYG                 | 12008168.04      | Y13             | PY12             | PY01          | EA             | 0                     | 4476            | 20171206              | 176942           | PY01               | 176942           |                      | 0                | 0              | 50             | 118177177    | 4476          | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20180123      |                    | 4231-3            |                    | 1              | 12                | 10            | C                  |                 |                 | A                  | ZLBN              |                   | 89312               | 1              | 20180119           | 20180119       |                  | ZLVE           | EC01       | ZECW01                |                | 20180119           | ECGUAY     | USE                 | 133.92           | E01             | E100             | EC01          | KI             | 0                     | 4               | 20180119              | 175699           | EC01               | 175699           |                      | 0                | 0              | 130            | 118285697    | 4             | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 0             |                    | 20810003          |                    | 1              | 10                | 10            | C                  |                 |                 | A                  | ZLBN              |                   | 66925               | 1              | 20160114           | 20160114       |                  | ZLVE           | CO02       | ZCOL01                |                | 20160116           | C02018     | COP                 | 396480           | C03             | CO10             | CO01          | EA             | 0                     | 80              | 20160116              | 136895           | CO02               | 136888           |                      | 0                | 0              | 70             | 116372103    | 80            | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20160825      |                    | 116951051         |                    | 1              | 10                | 11            | I                  |                 |                 | A                  | ZGRA              |                   | 81105               | 1              | 20160825           | 20160825       | 299              | ZGRA           | BR08       | ZBRAA6                |                | 20160825           | B08026     | BRL                 | 80.97            | B88             | BR20             | BR01          | KI             | 0                     | 2               | 20160825              | 125986           | BR08               | 125986           |                      | 0                | 0              | 80             | 116951051    | 2             | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 0             |                    | VL-REP-DX-559 REP |                    | 1              | 12                | 11            | I                  |                 |                 | A                  | ZLSR              |                   | 67976               | 1              | 20171218           | 20171218       | 337              | ZLSR           | CO03       | ZCOL07                |                | 20171218           | C02005     | COP                 | 1120             | C45             | CO50             | CO01          | EA             | 1                     | 0               | 20171220              | 136030           | CO03               | 136030           |                      | 0                | 0              | 16             | 118216040    | 1             | 2                | CONS_LATAM   | N            | N             |
#      |                   |                       | 0             |                    | 116099797         |                    | 1              | 10                | 11            | I                  |                 |                 | A                  | ZSRT              |                   | 81098               | 1              | 20150925           | 20150925       | 337              | ZSRT           | BR08       | ZBRA04                |                | 20150925           | B08000     | BRL                 | 10.64            | B71             | BR26             | BR01          | EA             | 0                     | 8               | 20150925              | 108003           | BR08               | 108003           |                      | 0                | 0              | 20             | 116099797    | 8             | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 0             |                    | 967326            |                    | 1              | 16                | 10            | C                  |                 |                 | A                  | ZVLO              |                   | 61161               | 1              | 20151008           | 20151008       |                  | ZVLO           | BR12       | ZBRA14                |                | 20151008           |            | BRL                 | 6.67             | 45              | BR30             | BR04          | EA             | 1                     | 1               | 20151008              | 185841           | BR39               | 185841           | BR39                 | 0                | 0              | 40             | 116129088    | 1             | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20150908      |                    | 116051650         |                    | 1              | 10                | 11            | C                  |                 |                 | A                  | ZTBN              |                   | 4560                | 1              | 20150908           | 20150908       |                  | ZORB           | BR08       | ZBRAA3                |                | 20150908           | B08004     | BRL                 | 47.17            | B63             | BR29             | BR01          | KI             | 0                     | 1               | 20150908              | 175124           | BR08               | 175124           |                      | 0                | 0              | 130            | 116051650    | 1             | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 0             |                    | 116278799         |                    | 1              | 10                | 11            | I                  |                 |                 | A                  | ZSRT              |                   | 85648               | 1              | 20151203           | 20151203       | 337              | ZSRT           | BR08       | ZBRA04                |                | 20151203           | B08004     | BRL                 | 2.11             | B92             | BR21             | BR01          | EA             | 0                     | 1               | 20151203              | 181640           | BR08               | 181640           |                      | 0                | 0              | 60             | 116278799    | 1             | 2                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20180209      |                    | 4502296970        |                    | 1              | 11                | 10            | C                  |                 |                 | A                  | ZTBN              |                   | 68874               | 12             | 20180115           | 20180115       |                  | ZORB           | BR25       | ZBRW01                |                | 20180119           | B25004     | BRL                 | 115.52           | B51             | BR65             | BR01          | KI             | 1                     | 1               | 20180119              | 126024           | BR25               | 126024           |                      | 0                | 0              | 60             | 118275439    | 1             | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 0             |                    | 117760343         |                    | 1              | 10                | 11            | I                  |                 |                 | A                  | ZSRT              |                   | 84361               | 1              | 20170628           | 20170628       | 337              | ZSRT           | BR08       | ZBRA04                |                | 20170628           | B08003     | BRL                 | 2.11             | B63             | BR29             | BR01          | EA             | 0                     | 1               | 20170628              | 170605           | BR08               | 170605           |                      | 0                | 0              | 10             | 117760343    | 1             | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 20151123      |                    | 940400787         |                    | 1              | 10                | 10            | C                  |                 |                 | A                  | ZLBN              |                   | 96002               | 12             | 20151119           | 20151119       |                  | ZLVE           | AR02       | ZARG01                |                | 20151119           | AR4000     | ARS                 | 507.16           | A01             | AR10             | AR02          | KI             | 0                     | 2               | 20151119              | 153093           | AR02               | 153093           | AR02                 | 0                | 0              | 40             | 116244155    | 2             | 1                | CONS_LATAM   | N            | N             |
#      |                   |                       | 0             |                    | 195446            |                    | 1              | 10                | 10            | C                  |                 |                 | A                  | ZLBN              |                   | 51846               | 1              | 20170405           | 20170405       |                  | ZLVE           | CO02       | ZCOL01                |                | 20170407           | C02005     | COP                 | 1511004          | C18             | CO75             | CO01          | EA             | 0                     | 66              | 20170407              | 139766           | CO02               | 139766           |                      | 0                | 0              | 460            | 117548791    | 66            | 1                | CONS_LATAM   | N            | N             |
#    And I wait "/edm/sales_order_v1" Async Queue complete
#
#    Given I import "/edm/material_global_v1" by keyFields "localMaterialNumber,sourceSystem"
#      | baseUom | batchManageIndicator | brand | category | division | flagForDeletion | form | franchise | globalBusinessUnit | globalDpParentCode | localBaseUom | localDpParentCode | localManufacturingTechnology | localMaterialGroup | localMaterialNumber | localMaterialType | localRefDescription                      | manufacturingTechnology | materialGroup | materialNumber | materialStatus | materialType | minRemShelfLife | parentCode | primaryPlanningCode | productFamily | refDescription | sourceSystem | subBrand | totalShelfLife |
#      |         |                      |       |          | 10       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 58752               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 58752          | 8              |              | 100             |            | 58752               |               |                | CONS_LATAM   |          | 0              |
#      |         |                      |       |          | 11       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 80990               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 80990          | 8              |              | 365             |            | 80990               |               |                | CONS_LATAM   |          | 1825           |
#      |         |                      |       |          | 10       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 57039               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 57039          | 8              |              | 120             |            | 57039               |               |                | CONS_LATAM   |          | 11             |
#      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 96161               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 96161          | 9              |              | 11              |            | 96161               |               |                | CONS_LATAM   |          | 1              |
#      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 91732               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 91732          | 8              |              | 8               |            | 91732               |               |                | CONS_LATAM   |          | 2              |
#      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 60520               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 60520          | 9              |              | 9               |            | 60520               |               |                | CONS_LATAM   |          | 6              |
#      |         |                      |       |          | 13       |                 |      |           |                    |                    | EA           |                   |                              | 80141605           | 528395              | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 528395         | 9              |              | 9               |            | 528395              |               |                | CONS_LATAM   |          | 7              |
#      |         |                      |       |          | 13       |                 |      |           |                    |                    | BTL          |                   |                              | 8011605            | 68052               | PROM              | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               | 68052          | 8              |              | 6               |            | 68052               |               |                | CONS_LATAM   |          | 7              |
#    And I wait "/edm/material_global_v1" Async Queue complete
#
#    Given I import "/plan/cns_material_plan_status" by keyFields "localMaterialNumber,localPlant,sourceSystem"
#      | active | dpRelevant | localMaterialNumber | localParentCode   | localPlant | materialNumber | noPlanRelevant | parentActive | ppc    | sourceSystem | spRelevant |
#      | X      |            | 58752               | 78910109411230000 | BR01       |                |                | X            | 58722  | CONS_LATAM   | X          |
#      | X      |            | 97360               | 78910100877220000 | CO13       |                |                | X            | 97360  | CONS_LATAM   | X          |
#      | X      |            | 57039               | 78910100877220000 | BR14       |                |                | X            | 57039  | CONS_LATAM   | X          |
#      | X      |            | 80990               | 78910100877220000 | BR12       | 80990          | X              | X            |        | CONS_LATAM   |            |
#      | X      |            | 96161               | 78910100877220000 | BR12       | 1234           | X              | X            | 7867   | CONS_LATAM   |            |
#      | X      |            | 91732               | 78910100877220000 | BR14       |                | X              | X            | 91732  | CONS_LATAM   |            |
#      | X      |            | 60520               | 78910100877220000 | BR13       | 60520          |                | X            |        | CONS_LATAM   | X          |
#      | X      |            | 528395              | 78910100877220000 | BR12       |                | X              | X            | 528395 | CONS_LATAM   |            |
#    And I wait "/plan/cns_material_plan_status" Async Queue complete
#
#    Given I import "/plan/cns_spl_pln_loc" by keyFields "localName,localNumber,sourceSystem,vendorOrCustomer"
#      | localCountry | localCurrency | localName                           | localNumber | localPlant | localRegion | pLanlocTypeDesc | pLanlocTypeId | planLocTypeDesc           | planLocTypeId | sourceSystem | specLocAtt1 | specLocAtt2 | specLocAtt3 | specLocAttDesc1 | specLocAttDesc2 | specLocAttDesc3 | vendorOrCustomer |
#      | BR           | BRL           | SUPPORT PACK IND E COM LTDA         | 1189        | BR12       | 103         |                 |               | Mfg Plant Copacker        | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | EC           | USE           | LODISAL S.A.                        | 528395      | BR12       | 103         |                 |               | Affiliate/Market Copacker | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | US           |               | JOHNSON & JOHNSON CONSUMER INC.     | 50161       | BR01       | 101         |                 |               | Ext Manufacturer FG       | VENDOR        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | UY           | UYU           | MODYLER SA                          | 65659       | UY01       | 103         |                 |               | Affiliate/Market Copacker | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | GT           | GTQ           | DHL GLOBAL FORWARDING (GUATEMALA)   | 36191       | GT01       | 103         |                 |               | Affiliate/Market Copacker | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | CO           | COP           | SUPPLA SA                           | 44776       | CO01       | 103         |                 |               | Mfg Plant Copacker        | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | CL           | CLP           | Apl Logistics Chile S.A.            | 79232       | BR14       | 103         |                 |               | Affiliate/Market Copacker | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | DO           | DOP           | YOBEL SRL? ? ? ? ? ? ? ?            | 34427       | DO01       | 103         |                 |               | Affiliate/Market Copacker | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | MX           | MXN           | AVP MAQUILA DE MEXICO S DE RL DE CV | 86017       | MX02       | 103         |                 |               | Affiliate/Market Copacker | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | CO           | COP           | ASPRILLA ORTIZ FABIO                | 15574       | CO01       | 103         |                 |               | Mfg Plant Copacker        | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | CR           | CRC           | D.H.L. COSTA RICA (CORMAR) S.A.     | 36328       | CR01       | 103         |                 |               | Affiliate/Market Copacker | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | MX           | MXN           | CILAG AG INTERNATIONAL              | 6109        | MX01       | 104         |                 |               | Ext Manufacturer FG       | VENDOR        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | PA           | USD           | J CAIN & CO                         | 36124       | PA03       | 103         |                 |               | Affiliate/Market Copacker | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#      | PE           | USD           | YOBEL SUPPLY CHAIN MANAGEMENT S.A.  | 20667       | PE01       | 103         |                 |               | Affiliate/Market Copacker | SUBCON        | CONS_LATAM   |             |             |             |                 |                 |                 | V                |
#    And I wait "/plan/cns_spl_pln_loc" Async Queue complete
#
#    Given I import "/plan/prod_loc_min_shelf" by keyFields "localMaterialNumber,localPlant,sourceSystem"
#      | localMaterialNumber | localPlant | minMinShelfLife | minShelfLife | sourceSystem |
#      | 58752               | BR01       |                 | 150          | CONS_LATAM   |
#      | *                   | BR01       |                 | 180          | CONS_LATAM   |
#      | *                   | BR16       |                 | 270          | CONS_LATAM   |
#    And I wait "/plan/prod_loc_min_shelf" Async Queue complete
#
#    Given I import "/plan/cns_plan_unit" by keyFields "localUom,sourceSystem"
#      | factor | localUom | localUomName        | planFlag | plantFlag | roundingDecimal | sourceSystem | unit   |
#      | 1      | PAL      | Pallet              | SP       |           | 0               | CONS_LATAM   | PAL    |
#      | 1      | KI       | Crate               | DPSP     |           | 0               | CONS_LATAM   | CA     |
#      | 1      | KG       | KiloGram            | SP       |           | 6               | CONS_LATAM   | KG     |
#      | 1      | CS       | Case                | DPSP     |           | 0               | CONS_LATAM   | CA     |
#      | 1      | L        | `                   | SP       |           | 6               | CONS_LATAM   | L      |
#      | 1      | EA       | Each                | DPSP     |           | 0               | CONS_LATAM   | EA     |
#      | 1      | M2       | Square Meter        | SP       |           | 6               | CONS_LATAM   | M2     |
#      | 1      | DZ       | Dozen               | SP       |           | 3               | CONS_LATAM   | DZ     |
#      | 1      | TH       | Thousand            | SP       |           | 6               | CONS_LATAM   | TS     |
#      | 1      | KM       | Kilometer           | SP       |           | 3               | CONS_LATAM   | KM     |
#      | 1      | ZUM      | Market Control Unit | DPÂ      |           | 6               | CONS_LATAM   | LA_ZUM |
#    And I wait "/plan/cns_plan_unit" Async Queue complete
#
#    Given I import "/edm/sales_history_v1" by keyFields "localPrecDocNo,localSPrecDocLnNo,localSubDocCatg,localSubsDocLnNo,localSubsDocNo,sourceSystem"
#      | sourceSystem | localPrecDocNo | localSPrecDocLnNo | localSubsDocNo | localSubsDocLnNo | localSubDocCatg | localBaseQuantity | localBaseUom | localSalesQuantity | localSalesUom | localPrecItemCatg | localCrtDt |
#      | CONS_LATAM   | 116708516      | 490               | 195007613      | 10               | J               | 10.000            | CRT          | 1                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 8306862        | 20                | 195007613      | 20               | J               | 5.000             | CRT          | 1                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 8306862        | 20                | 195007613      | 25               | J               | 5.000             | CRT          | 1                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 8306863        | 150               | 195007613      | 30               | J               | 3.000             | CRT          | 3                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 116043204      | 180               | 195007613      | 40               | J               | 90.000            | CRT          | 5                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 115689885      | 60                | 195007613      | 50               | J               | 1.000             | CRT          | 1                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 40075674       | 60                | 195007613      | 60               | J               | 5.000             | CRT          | 5                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 40075674       | 70                | 195007613      | 70               | J               | 3.000             | CRT          | 3                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 40075674       | 80                | 195007613      | 80               | J               | 3.000             | CRT          | 3                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 40075674       | 90                | 195007613      | 90               | J               | 3.000             | CRT          | 3                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 40075674       | 100               | 195007613      | 100              | J               | 3.000             | CRT          | 3                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 40075674       | 110               | 195007613      | 110              | J               | 3.000             | CRT          | 3                  | CRT           | J                 | 2015/06/24 |
#      | CONS_LATAM   | 40075674       | 120               | 195007613      | 120              | X               | 1.000             | CRT          | 1                  | CRT           | J                 | 2015/06/24 |
#    And I wait "/edm/sales_history_v1" Async Queue complete
#
#    Given I import "/project_one/knvh" by keyFields "kunnr"
#      | bokre | datab    | datbi    | grpno | hityp | hkunnr | hspart | hvkorg | hvtweg | hzuor | kunnr  | mandt | prfre | spart | vkorg | vtweg |
#      | X     | 20171006 | 99991231 | 0     | A     | 13231  | 11     | BR01   | 10     | 0     | 192514 | 120   | X     | 11    | BR01  | 10    |
#      | X     | 20180130 | 99991231 | 0     | A     | 361    | 10     | BR01   | 10     | 0     | 182493 | 120   | X     | 10    | BR01  | 10    |
#      | X     | 20070901 | 99991231 | 0     | A     | 7386   | 11     | BR01   | 10     | 0     | 105032 | 120   | X     | 11    | BR01  | 10    |
#      | X     | 20100629 | 99991231 | 0     | A     | 1185   | 10     | CO01   | 10     | 0     | 167049 | 120   | X     | 10    | CO01  | 10    |
#      | X     | 20090504 | 99991231 | 0     | A     | 977    | 10     | CO01   | 10     | 0     | 163574 | 120   | X     | 10    | CO01  | 10    |
#      | X     | 20170222 | 99991231 | 0     | A     | 13016  | 10     | MX02   | 11     | 0     | 193706 | 120   | X     | 10    | MX02  | 11    |
#      | X     | 20070416 | 99991231 | 0     | A     |        |        |        |        | 1     | 4110   | 120   | X     | 10    | VE03  | 10    |
#      | X     | 20170802 | 99991231 | 0     | A     | 11560  | 11     | MX02   | 10     | 0     | 198360 | 120   | X     | 11    | MX02  | 10    |
#      | X     | 20020822 | 99991231 | 0     | B     | 726    | 10     | BR01   | 10     | 0     | 107724 | 120   | X     | 10    | BR01  | 10    |
#    And I wait "/project_one/knvh" Async Queue complete
#
#    Given I import "/plan/cns_dem_grp_asgn" by keyFields "companyCode,countryAffiliate,customerId,region,sourceSystem"
#      | channel | channelDescription       | companyCode | countryAffiliate | customerId | customerName                        | customerShipTo | demandGroup | demandGroupDescription | demandGrpDescription           | fromDate | group | region | salesOrg | salesOrganization | sourceSystem | subFranchise | toDate |
#      | CH010   | Other Mass               |             | BR               | 109038     | GRUPO COMERCIAL 15 DE NOVEMBRO LTDA |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     | BR01              | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 182493     | GRUPO PALHETA REFEICOES COLETIVAS L |                | 76100014    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 283        | GRUPO MICROLITE S/A                 |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH011   | Door to Doore/E-commerce |             | BR               | 12046      | DENTAL CRUZEIRO LTDA                |                | 76100014    |                        | Door to Doore/E-commerce OTHER |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH006   | Distributor Traditional  |             | BR               | 96         | GRUPO RECOL REPR.E COMERCIO LTDA    |                | 76100031    |                        | RECOL                          |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH011   | Door to Doore/E-commerce |             | BR               | 12518      | GRUPO BEBEDAMOUR                    |                | 76100014    |                        | Door to Doore/E-commerce OTHER |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH011   | Door to Doore/E-commerce |             | BR               | 9385       | GRUPO PLUS COM DE PROD E EQUIP ODON |                | 76100014    |                        | Door to Doore/E-commerce OTHER |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH007   | Wholesaler Traditional   |             | BR               | 11192      | GRUPO SARDAGNA                      |                | 76100009    |                        | Wholesaler Traditional OTHER   |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH004   | Other Pharma             |             | BR               | 11992      | MEGA RIO LOGISTICA E DISTRIBUICAO D |                | 76100011    |                        | Other Pharmacy/Drugstore       |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 10643      | GRUPO FROHLICH S A IND E COM DE CER |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 469        | GRUPO SUPERMERCADO REAL DE EDEN LTD |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 510        | GRUPO NITER COMERCIO DE DROGAS LTDA |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH007   | Wholesaler Traditional   |             | BR               | 9414       | GRUPO CASA NORTE LTDA               |                | 76100009    |                        | Wholesaler Traditional OTHER   |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 195        | GRUPO LOJAS BRASILEIRAS S/A         |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 382        | GRUPO FUCHS GEWURZE DO BRASIL LTDA. |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH011   | Door to Doore/E-commerce |             | BR               | 12631      | DENTAL CURITIBANA COM PROD OD LTDA  |                | 76100014    |                        | Door to Doore/E-commerce OTHER |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 622        | GRUPO SUPERMERCADOS FEBERNATI SA    |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 7485       | GRUPO SUPERM BARONESA               |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 494        | GRUPO S.M.RASTELAO LTDA.            |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH001   | Pharmacy/Drugstore       |             | BR               | 681        | GRUPO DIMED SA DISTRIB DE MEDICAMEN |                | 76100013    |                        | Pharmacy/Drugstore OTHER       |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH001   | Pharmacy/Drugstore       |             | BR               | 9389       | GRUPO SANTA MARTA DISTRIB DE DROGAS |                | 76100013    |                        | Pharmacy/Drugstore OTHER       |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH008   | Clubs/Cash & Carry       |             | BR               | 1348       | GRUPO MAKRO ATAC SUL                |                | 76100006    |                        | Clubs/Cash & Carry OTHER       |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 9667       | GRUPO FORTE MIX                     |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 207        | GRUPO HOTEIS OTHON S/A LEME PALACE  |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH011   | Door to Doore/E-commerce |             | BR               | 12029      | GRUPO TONET COM DE MAT ODONTO       |                | 76100014    |                        | Door to Doore/E-commerce OTHER |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH006   | Distributor Traditional  |             | BR               | 108657     | J. B. FILHO TRANSPORTES L           |                | 76100010    |                        | Distributor Traditional OTHER  |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH005   | Modern Trade             |             | BR               | 7488       | GRUPO SAITO                         |                | 76100008    |                        | Modern Trade OTHER             |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH007   | Wholesaler Traditional   |             | BR               | 491        | GRUPO COMERCIAL IKEDA LTDA          |                | 76100009    |                        | Wholesaler Traditional OTHER   |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH001   | Pharmacy/Drugstore       |             | BR               | 8451       | GRUPO VANDROGAS                     |                | 76100013    |                        | Pharmacy/Drugstore OTHER       |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH006   | Distributor Traditional  |             | BR               | 145698     | LSLOG ARMAZENAGEM E LOGIS           |                | 76100010    |                        | Distributor Traditional OTHER  |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 336        | GRUPO NESTLE BRASIL LTDA.           |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 149        | GRUPO CARRARO & ROCHA LTDA.         |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH006   | Distributor Traditional  |             | BR               | 9538       | GRUPO ARMARINHOS  PARANÃ            |                | 76100010    |                        | Distributor Traditional OTHER  |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH007   | Wholesaler Traditional   |             | BR               | 11626      | GRUPO COMPRE FACIL                  |                | 76100009    |                        | Wholesaler Traditional OTHER   |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH005   | Modern Trade             |             | BR               | 9344       | GRUPO CASAS GUANABARA COMESTIVEIS L |                | 76100008    |                        | Modern Trade OTHER             |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH007   | Wholesaler Traditional   |             | BR               | 12461      | GRUPO JOTA FOTE COM DE ALIMENTOS LT |                | 76100009    |                        | Wholesaler Traditional OTHER   |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH011   | Door to Doore/E-commerce |             | BR               | 9347       | GRUPO D F COMERCIAL ODONTOLOGICA LT |                | 76100014    |                        | Door to Doore/E-commerce OTHER |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH007   | Wholesaler Traditional   |             | BR               | 9460       | GRUPO PEROLA DISTRIBUICAO E LOGISTI |                | 76100009    |                        | Wholesaler Traditional OTHER   |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH005   | Modern Trade             |             | BR               | 7771       | GRUPO CABRINI BERETTA CIA           |                | 76100008    |                        | Modern Trade OTHER             |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 395        | GRUPO G D L A GRAPHICS DESIGN AND A |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 456        | GRUPO SESC SERVICO SOCIAL DO COMERC |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH011   | Door to Doore/E-commerce |             | BR               | 10656      | GRUPO DENTAL S SEBASTIAO LTDA       |                | 76100014    |                        | Door to Doore/E-commerce OTHER |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH011   | Door to Doore/E-commerce |             | BR               | 12635      | ABCL DACACHE PROD ODONTOL LTDA      |                | 76100014    |                        | Door to Doore/E-commerce OTHER |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 166        | GRUPO NASSER S PRESENTES LTDA.      |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH005   | Modern Trade             |             | BR               | 9911       | GRUPO ELSON                         |                | 76100008    |                        | Modern Trade OTHER             |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH010   | Other Mass               |             | BR               | 461        | GRUPO LUCIO SILVEIRA & FILHOS       |                | 76100007    |                        | OTHER MASS OTHER               |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH011   | Door to Doore/E-commerce |             | BR               | 9356       | GRUPO DENTAL SAO SEBASTIAO LTDA     |                | 76100014    |                        | Door to Doore/E-commerce OTHER |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH011   | Door to Doore/E-commerce |             | BR               | 9335       | GRUPO ASSOCIACAO DOS LOJISTAS DO SH |                | 76100014    |                        | Door to Doore/E-commerce OTHER |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#      | CH011   | Door to Doore/E-commerce |             | BR               | 11022      | GRUPO DENTAL SORRISO                |                | 76100014    |                        | Door to Doore/E-commerce OTHER |          |       |        | BR01     |                   | CONS_LATAM   |              |        |
#    And I wait "/plan/cns_dem_grp_asgn" Async Queue complete

    When I submit aggregation task with xml file "xml/edm/EDMSalesHistoryAggregation.xml"

    When I submit task with xml file "xml/gdm_demand_sales_order.xml" and execute file "jar/pangea-view.jar"

#    Then A file is found on sink application with name "GDMDemandSalesOrder.tsv"

#    And I check file data for filename "GDMDemandSalesOrder.tsv" by keyFields "SupplyId"
#      | active | activeFCTERP | activeOPRERP | activeSOPERP | batchId | certaintyId | customerId | demandId                            | dueDate             | fromDueDate         | inventoryLinkGroupId | locationId      | minRemainingShelfLife | planningStrategy        | productId | quantity | unitId | wRK02 |
#      | YES    | NO           | YES          | NO           |         | VC          | 76100007   | 58752/CONS_LATAM_BR01/116708516/490 | 2016/06/03 00:00:01 | 2016/06/03 00:00:00 |                      | CONS_LATAM_BR01 | 150                   | ProductLocationBalanced | 58752     | 330.00   | EA     |       |
#      | YES    | NO           | YES          | NO           |         | VC          | 76100014   | 57039/CONS_LATAM_BR14/8306862/20    | 2018/01/16 00:00:01 | 2018/01/16 00:00:00 |                      | CONS_LATAM_BR14 | 120                   | ProductLocationBalanced | 57039     | 28.00    | EA     |       |
#      | YES    | NO           | YES          | NO           |         | VC          |            | 60520/CONS_LATAM_BR20/8306863/150   | 2018/02/24 00:00:01 | 2018/02/24 00:00:00 |                      | CONS_LATAM_BR20 | 9                     | ProductLocationBalanced | 60520     | 2017.00  | EA     |       |
#      | YES    | NO           | YES          | NO           |         | VC          | 76100014   | 91732/CONS_LATAM_BR14/115689885/60  | 2018/04/02 00:00:01 | 2018/04/02 00:00:00 |                      | CONS_LATAM_BR14 | 120                   | ProductLocationBalanced | 91732     | 37.00    | EA     |       |

#  Scenario: delete all test data
#
#    Then I delete the test data

#    And I will remove all data with region "/omp/gdm_demand_sales_order"
#
#    And I will remove the test file on sink application "GDMDemandSalesOrder.tsv"
