@pangea_test @AEAZ-4486
Feature:  OMPGdmSupply-Curation

  Scenario: Full Load consumption

    Given I import "/edm/source_list_v1" by keyFields "sourceSystem,localMaterialNumber,localPlant,localNumberofSourceListRecord"
      | sourceSystem | localMaterialNumber | localPlant | localNumberofSourceListRecord | materialNumber | plant | localCreatedOn | localCreatedBy | localSourceListRecordValidFrom | localSourceListRecordValidTo | localVendorAccountNumber | localFixedvendor | localAgreementNumber | localAgreementItem | localFixedOutlinePurchaseAgreementItem | localPlantfromWhichMaterialisProcured | localMatForManufPartNumber | localBlockedSourceofSupply | localPurchasingOrganization | localPurchasingDocumentCategory | localCategoryofSourceListRecord | localSourceListUsageinMaterialsPlanning |
      | CONS_LATAM   | 3                   | MX02       | 3                             | 51178          | AR01  | 20030306       | CCASTRO1       | 20120718                       | 99991230                     | 6109                     |                  |                      | 0                  |                                        |                                       |                            |                            | MX01                        |                                 | 7                               |                                         |
      | CONS_LATAM   | 4                   | BR16       | 4                             | 945            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     | 2519                     |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 5                   | BR06       | 5                             | 71325          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     |                          | 1                |                      | 0                  | 1                                      |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 6                   | VE01       | 6                             | 1331           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     |                          | 1                |                      | 0                  | 1                                      |                                       |                            |                            | VE00                        |                                 | 4                               |                                         |
      | CONS_LATAM   | 7                   | MX03       | 7                             | 92129          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     | 6359                     |                  |                      | 0                  |                                        |                                       |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   | 8                   | MX04       | 8                             | 51179          | AR01  | 20030306       | CCASTRO1       | 20120718                       | 99991230                     | 6109                     |                  |                      | 0                  |                                        |                                       |                            |                            | MX01                        |                                 | 7                               |                                         |
      | CONS_LATAM   | 9                   | BR17       | 9                             |                | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     |                          |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      |              | 10                  | BR08       | 10                            | 71326          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     | 1                |                      | 0                  | 1                                      |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 11                  | VE04       | 11                            | 1332           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     | 8917                     |                  |                      | 0                  |                                        |                                       |                            |                            |                             |                                 | 4                               |                                         |
      | CONS_LATAM   | 12                  | MX08       | 12                            | 92130          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     | 6359                     | 1                |                      | 0                  | 1                                      |                                       |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   | 13                  | MX09       | 13                            | 51180          | AR01  | 20030306       | CCASTRO1       | 20120718                       | 99991230                     |                          |                  |                      | 0                  |                                        | MX01                                  |                            |                            | MX01                        |                                 | 7                               |                                         |
      | CONS_LATAM   | 14                  | BR20       | 14                            | 946            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     | 2519                     |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 15                  | BR21       | 15                            | 71331          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     |                  |                      | 0                  |                                        | BR00                                  |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 16                  | VE22       | 16                            | 1335           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     |                          |                  |                      | 0                  |                                        |                                       |                            |                            | VE00                        |                                 | 4                               |                                         |
      | CONS_LATAM   | 17                  | MX23       | 17                            | 92137          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     | 6359                     | 1                |                      | 0                  | 1                                      |                                       |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   | 18                  | MX24       | 18                            | 948            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     |                          |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 19                  | BR25       | 19                            | 71333          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     | 1                |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 20                  | BR26       | 20                            | 1338           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     |                          |                  |                      | 0                  |                                        |                                       |                            |                            | VE00                        |                                 | 4                               |                                         |
      | CONS_LATAM   | 21                  | VE27       | 21                            | 92144          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     | 6359                     |                  |                      | 0                  |                                        |                                       |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   | 22                  | MX28       | 22                            | 949            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     | 2519                     |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 23                  | BR29       | 23                            | 71340          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     |                          |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 24                  | BR30       | 24                            | 1340           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     |                          |                  |                      | 0                  |                                        | VE00                                  |                            |                            | VE00                        |                                 | 4                               |                                         |
      | CONS_LATAM   | 25                  | VE31       | 25                            | 92150          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     |                          | 1                |                      | 0                  |                                        |                                       |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   |                     | VE32       | 26                            | 960            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     | 2519                     |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 27                  | MX33       | 27                            | 71352          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 28                  | MX34       | 28                            | 1342           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     | 8917                     |                  |                      | 0                  |                                        | VE00                                  |                            |                            | VE00                        |                                 | 4                               |                                         |
      | CONS_LATAM   | 29                  | MX35       | 29                            | 92160          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     | 6359                     |                  |                      | 0                  |                                        |                                       |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   | 30                  | VE36       | 30                            | 965            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     | 2519                     |                  |                      | 0                  |                                        | BR00                                  |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 31                  | VE37       | 31                            | 7145           | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     | 1                |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 32                  | MX38       | 32                            | 7146           | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     | 1                |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 33                  | MX39       | 33                            | 71350          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     | 1                |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 34                  | MX40       | 34                            | 71351          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     | 1                |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 35                  | MX41       | 35                            | 71352          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     | 1                | 9                    | 0                  |                                        | VR00                                  |                            |                            | BR00                        |                                 | 9                               |                                         |


    And I wait "/edm/source_list_v1" Async Queue complete

    Given I import "/edm/plant_v1" by keyFields "localPlant,sourceSystem"
      | sourceSystem | localPlant | plant | localPlanningRelevant |
      | CONS_LATAM   | MX02       | AR01  | X                     |
      | CONS_LATAM   | BR16       | AR01  | X                     |
      | CONS_LATAM   | BR06       | AR01  | X                     |
      | CONS_LATAM   | VE01       | AR01  | X                     |
      | CONS_LATAM   | MX03       | AR01  | X                     |
      | CONS_LATAM   | MX04       | AR01  | X                     |
      | CONS_LATAM   | BR17       | AR01  | X                     |
      | CONS_LATAM   | BR08       | AR01  | X                     |
      | CONS_LATAM   | VE04       | AR01  | X                     |
      | CONS_LATAM   | MX08       | AR01  |                       |
      | CONS_LATAM   | MX09       | AR01  | A                     |
      | CONS_LATAM   | BR20       | AR01  | X                     |
      | CONS_LATAM   | BR21       | AR01  | X                     |
      | CONS_LATAM   | VE22       | AR01  | X                     |
      | CONS_LATAM   | MX23       | AR01  | X                     |
      | CONS_LATAM   | MX24       | AR01  | X                     |
      | CONS_LATAM   | BR25       | AR01  | X                     |
      | CONS_LATAM   | BR26       | AR01  | X                     |
      | CONS_LATAM   | VE27       | AR01  | X                     |
      | CONS_LATAM   | MX28       | AR01  | X                     |
      | CONS_LATAM   | BR29       | AR01  | X                     |
      | CONS_LATAM   | BR30       | AR01  | X                     |
      | CONS_LATAM   | VE31       | AR01  | X                     |
      | CONS_LATAM   | VE32       | AR01  | X                     |
      |              | MX33       | AR01  | X                     |
      | CONS_LATAM   | MX34       | AR01  | X                     |
      | CONS_LATAM   | MX35       | AR01  | X                     |
      | CONS_LATAM   | VE36       | AR01  | X                     |
      | CONS_LATAM   | VE37       | AR01  | X                     |
      | CONS_LATAM   | MX39       | AR01  | X                     |

    And I wait "/edm/plant_v1" Async Queue complete

    Given I import "/edm/material_global_v1" by keyFields "localMaterialNumber,sourceSystem"
      | localMaterialNumber | materialNumber | sourceSystem | primaryPlanningCode |
      | 3                   | 51178          | CONS_LATAM   | 51178               |
      | 4                   | 945            | CONS_LATAM   | 945                 |
      | 5                   | 71325          | CONS_LATAM   | 71325               |
      | 6                   | 1331           | CONS_LATAM   | 1331                |
      | 7                   | 92129          | CONS_LATAM   | 92129               |
      | 8                   | 51179          | CONS_LATAM   | 51179               |
      | 9                   |                | CONS_LATAM   |                     |
      | 10                  | 71326          | CONS_LATAM   | 71326               |
      | 11                  | 1332           | CONS_LATAM   | 1332                |
      | 12                  | 92130          | CONS_LATAM   | 92130               |
      | 13                  | 51180          | CONS_LATAM   | 51180               |
      | 14                  | 946            | CONS_LATAM   | 946                 |
      | 15                  | 71331          | CONS_LATAM   | 71331               |
      | 16                  | 1335           | CONS_LATAM   | 1335                |
      | 17                  | 92137          | CONS_LATAM   | 92137               |
      | 18                  | 948            | CONS_LATAM   | 948                 |
      | 19                  | 71333          | CONS_LATAM   | 71333               |
      | 20                  | 1338           | CONS_LATAM   | 1338                |
      | 21                  | 92144          | CONS_LATAM   | 92144               |
      | 22                  | 949            | CONS_LATAM   | 949                 |
      | 23                  | 71340          | CONS_LATAM   | 71340               |
      | 24                  | 1340           | CONS_LATAM   | 1340                |
      | 25                  | 92150          | CONS_LATAM   | 92150               |
      |                     | 960            | CONS_LATAM   | 960                 |
      | 32                  | 71352          | CONS_LATAM   | 71352               |
      | 33                  | 71350          | CONS_LATAM   | 71350               |

    And I wait "/edm/material_global_v1" Async Queue complete

    Given I import "/edm/material_plant_v1" by keyFields "sourceSystem,localMaterialNumber,localPlant"
      | sourceSystem | localMaterialNumber | localPlant | materialNumber | plant | localPlantStatus | plantStatus | localProcurementType | localDeletionFlagPlant | localFixedlotsize | localMaximumLotSize | localMinimumLotSize | localRoundingValueForPoq | localLotsize | localMrpType | localMrpController | localInHouseProcessingTime | localSafetyStock | localMinimumSafetyStock | localProductionSupervisor | localProductionUnit | localPosttoInspectionStock | localComponentScrapInPercent | localCriticalpart | localAbcIndicator | localMaximumStocklevel | localCheckingGroupforAvailabilityCheck | localPlannedDeliveryTimeInDays | localDependentRequirements | localSafetytimeIndicator | localSafetyTime | localSpecialProcurementType | localPlanningStrategyGroup | localConsumptionPeriodBackward | localConsumptionPeriodForward | localConsumptionMode | localGoodsReceiptProcessingTimeInDays | localBatchManagementRequirmentIndicator | localPlanningTimeFence | localPosttoinspstk | localComponentScrap | localBaseQuantity | purchsngGrpCd |
      | CONS_LATAM   | 3                   | MX02       | 7703910        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 10                  | 1                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 4                   | BR16       | 7703911        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 100                 | 2                   | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 5                   | BR06       | 7703912        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 1000                | 3                   | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 6                   | VE01       | 7703913        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 20                  |                     | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               | 30                          | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00          |
      | CONS_LATAM   | 7                   | MX03       | 7703914        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 50                  |                     | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               | 30                          | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 8                   | MX04       | 7703915        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 75                  |                     | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               | 30                          | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 9                   | BR17       | 7703916        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 25                  | 7                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 10                  | BR08       | 7703917        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     | 8                   | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 11                  | VE04       | 7703918        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     | 9                   | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00          |
      | CONS_LATAM   | 12                  | MX08       | 7703919        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 15                  | 10                  | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 13                  | MX09       | 7703920        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 25                  | 11                  | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 30                             | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 14                  | BR20       | 7703921        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 12                  | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 15                  | BR21       | 7703922        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 13                  | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 16                  | VE22       | 7703923        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 65                  | 0                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00          |
      | CONS_LATAM   | 17                  | MX23       | 7703924        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00          |
      | CONS_LATAM   | 18                  | MX24       | 7703925        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 19                  | BR25       | 7703926        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 20                  | BR26       | 7703927        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 21                  | VE27       | 7703928        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00          |
      | CONS_LATAM   |                     | MX28       | 7703929        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 0                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00          |
      | CONS_LATAM   | 23                  | BR29       | 7703930        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 0                   | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 24                  | BR30       |                | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 0                   | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 25                  | VE31       | 7703932        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     | 0                   | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 26                  | VE32       | 7703933        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 0                   |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00          |
      | CONS_LATAM   | 27                  | MX33       | 7703934        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 28                  | MX34       | 7703935        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00          |
      | CONS_LATAM   | 29                  | MX35       | 7703936        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 30                  | VE36       | 7703937        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     | 0                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 31                  | VE37       | 7703938        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 65                  |                     | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00          |
      | CONS_LATAM   | 32                  | MX38       | 7703939        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 0                   |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 33                  | MX39       | 7703950        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 34                  | VE01       | 7703941        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00          |
      | CONS_LATAM   | 35                  | MX02       | 7703942        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 0                   |                     | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 36                  | VE01       | 7703943        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 0                   | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               |               |
      | CONS_LATAM   | 37                  | MX02       | 7703944        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 0                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               | 30                          | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |
      | CONS_LATAM   | 38                  | MX02       | 7703945        | AR01  | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 0                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               | 31                          | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01          |

    And I wait "/edm/material_plant_v1" Async Queue complete

    Given I import "/plan/cns_material_plan_status" by keyFields "sourceSystem,localMaterialNumber"
      | sourceSystem | localMaterialNumber | localPlant | materialNumber | localParentCode | ppc | active | dpRelevant | spRelevant | parentActive | noPlanRelevant |
      | CONS_LATAM   | 3                   | MX02       | 7703910        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 4                   | BR16       | 7703911        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 5                   | BR06       | 7703912        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 6                   | VE01       | 7703913        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 7                   | MX03       | 7703914        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 8                   | MX04       | 7703915        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 9                   | BR17       | 7703916        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 10                  | BR08       | 7703917        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 11                  | VE04       | 7703918        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 12                  | MX08       | 7703919        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 13                  | MX09       | 7703920        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 14                  | BR20       | 7703921        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 15                  | BR21       | 7703922        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 16                  | VE22       | 7703923        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 17                  | MX23       | 7703924        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 18                  | MX24       | 7703925        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 19                  | BR25       | 7703926        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 20                  | BR26       | 7703927        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 21                  | VE27       | 7703928        | G3a             | G4a | X      | X          |            | X            | X              |
      | CONS_LATAM   | 22                  | MX28       | 7703929        | G3a             | G4a | X      | X          | Z          | X            | X              |
      | CONS_LATAM   | 23                  | BR29       | 7703930        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 24                  | BR30       |                | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 25                  | VE31       | 7703932        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 26                  | VE32       | 7703933        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 27                  | MX33       | 7703934        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 28                  | MX34       | 7703935        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   |                     | MX35       | 7703936        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 30                  | VE36       | 7703937        | G3a             | G4a | X      | X          | X          | X            | X              |
      |              | 31                  | VE37       | 7703938        | G3a             | G4a | X      | X          | X          | X            | X              |
      | CONS_LATAM   | 33                  | MX39       | 7703950        | G3a             | G4a | X      | X          | X          | X            | X              |


    And I wait "/plan/cns_material_plan_status" Async Queue complete

    Given I import "/plan/cns_process_type" by keyFields "processTypeId,processTypeDesc"
      | processTypeId           | processTypeDesc                                                                                                                                 |
      | ExternalPurchase        | External Purchase                                                                                                                               |
      | ExternalTransport       | External Transport (Transport from 1 fiscal entity to another fiscal entity in the same ERP system, modeled through sales order/purchase order) |
      | InterERPTransport       | InterERP Transport (Transport between 2 different ERP systems, modeled through sales order/purchase order)                                      |
      | InternalTransport       | Internal Transport (Transport from 1 plant to another plant in the same ERP system, modeled through transport lanes in SAP)                     |
      | Production              | Production                                                                                                                                      |
      | SubcontractingTransport | Subcontracting Transport (Transport to ship components to a subcontractor)                                                                      |
      | Subcontracting          | Subcontracting                                                                                                                                  |
      | VendorPurchase          | Vendor Purchase                                                                                                                                 |
      | VendorTransport         | Vendor Transport (specific for the Pangea Vendor modeling: transport from a Vendor location to a plant)                                         |

    And I wait "/plan/cns_process_type" Async Queue complete

    Given I import "/plan/cns_spl_pln_loc" by keyFields "localNumber,vendorOrCustomer,sourceSystem,localPlant,localName"
      | localNumber | vendorOrCustomer | sourceSystem | localPlant | localName |
      | 6109        | V                | CONS_LATAM   |            |           |
      | 2519        | V                | CONS_LATAM   |            |           |
      | 6359        |                  | CONS_LATAM   |            |           |
      | 8917        | V                | CONS_LATAM   | MX02       |           |

    And I wait "/plan/cns_spl_pln_loc" Async Queue complete

    When I submit task with xml file "xml/omp/OMPGdmSupply.xml" and execute file "jar/pangea-view.jar"

    Then A file is found on sink application with name "OMPGdmSupply.tsv"

    And I check file data for filename "OMPGdmSupply.tsv" by keyFields "SupplyId"
      | PROCESSTYPEID    | PURCHASINGORGANIZATION | PURCHASINGGROUP | LocationId        | INCQuantity | ProductId | MinQuantity | ActiveSOPERP | SupplierId        | Active | VENDORID | Preference | ActiveOPRERP | LABEL             | FromDate            | ToDate              | MaxQuantity | TransportType | SupplyId                   |
      | externalPurchase | MX01                   | VE00            | CONS_LATAM_MX23   | 0.001       | 92137     |             | NO           | CONS_LATAM_MX23   | YES    | 6359     | 0          | YES          | External Purchase | 2009/05/08 00:00:00 | 9999/12/30 00:00:00 |             | DEFAULT       | 92137/CONS_LATAM_MX23/6359 |
      | vendorPurchase   | BR00                   | BR00            | CONS_LATAM_V_2519 | 0.001       | 946       | 12          | NO           | CONS_LATAM_V_2519 | YES    | 2519     | 1          | YES          | Vendor Purchase   | 2015/07/31 00:00:00 | 9999/12/30 00:00:00 | 0           | DEFAULT       | 946/CONS_LATAM_BR20/2519   |
      | vendorPurchase   | BR00                   | BR00            | CONS_LATAM_V_2519 | 100.000     | 945       | 2           | NO           | CONS_LATAM_V_2519 | YES    | 2519     | 1          | YES          | Vendor Purchase   | 2015/07/31 00:00:00 | 9999/12/30 00:00:00 | 100         | DEFAULT       | 945/CONS_LATAM_BR16/2519   |
      | externalPurchase | MX01                   | MX01            | CONS_LATAM_MX03   | 100.000     | 92129     |             | NO           | CONS_LATAM_MX03   | YES    | 6359     | 1          | YES          | External Purchase | 2009/05/08 00:00:00 | 9999/12/30 00:00:00 | 50          | DEFAULT       | 92129/CONS_LATAM_MX03/6359 |
      | vendorPurchase   | MX01                   | MX01            | CONS_LATAM_V_6109 | 0.001       | 51178     | 1           | NO           | CONS_LATAM_V_6109 | YES    | 6109     | 1          | YES          | Vendor Purchase   | 2012/07/18 00:00:00 | 9999/12/30 00:00:00 | 10          | DEFAULT       | 51178/CONS_LATAM_MX02/6109 |

    Then I check region data "/dev/plan/edm_failed_data" by keyFields "errorCode,functionalArea,interfaceID,key1,key2,key3,key4,key5,sourceSystem"
      | errorCode | errorValue                                                             | functionalArea | interfaceID  | key1       | key2 | key3 | key4 | key5 | sourceSystem |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM | 27   | MX33 |      |      | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM | 28   | MX34 |      |      | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM | 29   | MX35 |      |      | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM | 30   | VE36 |      |      | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM | 31   | VE37 |      |      | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM | 9    | BR17 |      |      | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM |      | VE32 |      |      | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM | 34   | MX40 |      |      | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM | 35   | MX41 |      |      | CONS_LATAM   |

#    Then I check region data "/plan/edm_failed_data" by keyFields "functionalArea,interfaceID,errorCode,sourceSystem,key1,key2,key3,key4,key5"
#      | functionalArea | interfaceID | errorCode | sourceSystem | businessArea | key1  | key2 | key3 | key4 | key5 | errorValue |

    And I will remove all data with region "/edm/source_list_v1"

    And I will remove all data with region "/edm/plant_v1"

    And I will remove all data with region "/edm/material_global_v1"

    And I will remove all data with region "/edm/material_plant_v1"

    And I will remove all data with region "/plan/cns_material_plan_status"

    And I will remove all data with region "/plan/cns_process_type"

    And I will remove all data with region "/plan/cns_spl_pln_loc"

    And I will remove the test file on sink application "OMPGdmSupply.tsv"

