@pangea_test @AEAZ-5951
Feature: OMPGdmStock AEAZ-5951
  As a Data user, I want EDG to create GDM file for GDMStock 5 and send to OMP so that data can be consumed by OMP for planning

  Scenario: full load

    And I will remove the test file on sink application "GDMStock_plannedOrder.tsv"

    Given I import "/edm/planned_order_v1" by keyFields "mfgPlanOrdrDocId,srcSysCd"
      | firmingInd | fxScrapQty | grDaysLeadQty | matlNum | mfgPlanOrdrDocId | mrpCtlId | planOrdrEndDt | planOrdrEndTm | planOrdrQty | planOrdrStrtDt | planOrdrTypeCd | planPlntCd | plngScnroCd | plntCd | prcmtTypeCd | prdtnFnshdDt | prdtnStrtDt | prdtnStrtTm | prdtnVers | prdtnVersNum | reqQty | sLocCd | splPrcmtTypeCd | srcSysCd   | uomCd |
      | X          | 0          | 0             | 138821  | 49748397         | H00      | 20180904      | 0             | 36300       | 20180903       | LA             | BR12       | 000         | BR12   | E           | 0            | 0           | 0           | V001      | 0            | 0      | BR28   | E              | CONS_LATAM | EA    |
      | X          | 0          | 0             | 189915  | 95941803         | C11      | 20181203      | 0             | 86544       | 20181203       | LA             | BR12       | 000         | BR12   | E           | 0            | 0           | 0           | V001      | 0            | 0      | BR28   | E              | CONS_LATAM | EA    |
      |            | 0          | 4             | 215161  | 112368557        | C61      | 20180808      | 240000        | 5600        | 20180808       | LA             | BR12       | 000         | BR12   | E           | 0            | 0           | 0           | V001      | 0            | 0      | BR28   | E              | CONS_LATAM | L     |
      | X          | 0          | 6             | 174461  | 117229550        | A04      | 20180809      | 0             | 12000       | 20180620       | LA             | CO01       | 000         | CO01   | E           | 0            | 0           | 0           | V001      | 0            | 0      | CO01   | E              | CONS_LATAM | EA    |
      | X          | 0          | 7             | 213481  | 117229560        | A14      | 20180809      | 0             | 15000       | 20180620       | LA             | AR01       | 000         | AR01   | E           | 0            | 0           | 0           | V001      | 0            | 0      | AR01   | E              | CONS_LATAM | EA    |
      | X          | 0          | 0             | 441346  | 117076013        | C61      | 20190423      | 0             | 26400       | 20190422       | LA             | AR01       | 000         | AR01   | E           | 0            | 0           | 0           | V001      | 0            | 0      | ARO1   | E              | CONS_LATAM | EA    |
      | X          | 0          | 0             | 441347  | 117076014        | C61      | 20190423      | 0             | 26400       | 20190422       | LA             | AR01       | 000         | AR01   | E           | 0            | 0           | 0           | V001      | 0            | 0      | AR01   | E              | CONS_LATAM | EA    |
      | X          | 0          | 0             | 441363  | 117076016        | C61      | 20190423      | 0             | 26400       | 20190422       | LA             | AE01       | 000         | AE01   | E           | 0            | 0           | 0           | V001      | 0            | 0      | AE01   | E              | CONS_LATAM | EA    |
      | X          | 0          | 0             | 441364  | 117076018        | C61      | 20190423      | 0             | 10000       | 20190422       | LA             | CO02       | 000         | CO02   | E           | 0            | 0           | 0           | V001      | 0            | 0      | CO02   | E              | CONS_LATAM | EA    |
      | X          | 0          | 0             | 441369  | 117076019        | C61      | 20190423      | 0             | 10000       | 20190422       | LA             | CR01       | 000         | CR01   | E           | 0            | 0           | 0           | V001      | 0            | 0      | CR01   | E              | CONS_LATAM | EA    |
    And I wait "/edm/planned_order_v1" Async Queue complete

    Given I import "/edm/material_global_v1" by keyFields "localMaterialNumber,sourceSystem"
      | baseUom | batchManageIndicator | brand | category | division | flagForDeletion | form | franchise | getPrimaryPlanningCode | globalBusinessUnit | globalDpParentCode | localBaseUom | localDpParentCode | localManufacturingTechnology | localMaterialGroup | localMaterialNumber | localMaterialType | localRefDescription                | manufacturingTechnology | materialGroup | materialNumber | materialNumber16 | materialStatus | materialType | minRemShelfLife | minremshelflife21 | parentCode | primaryPlanningCode | productFamily | refDescription                     | sourceSystem | subBrand | testReservation | totalShelfLife |
      | EA      | X                    |       |          | 10       |                 |      |           |                        |                    |                    | EA           |                   |                              | FNW011             | 138821              | ROH               | CINTA SILIC PINK 61 MM MONDI CLIPS |                         |               |                |                  | 8              | ROH          | 150             |                   |            | 138821              |               | CINTA SILIC PINK 61 MM MONDI CLIPS | CONS_LATAM   |          |                 | 365            |
      | EA      | X                    |       |          | 10       |                 |      |           |                        |                    |                    | EA           |                   |                              | FNW011             | 189915              | ROH               | CINTA SILIC PINK 61 MM MONDI CLIPS |                         |               | 189915         |                  | 8              | ROH          | 150             |                   |            | 189915              |               | CINTA SILIC PINK 61 MM MONDI CLIPS | CONS_LATAM   |          |                 | 365            |
      | L       | X                    |       |          | 10       |                 |      |           |                        |                    |                    | L            |                   |                              | FNW011             | 215161              | ROH               | CINTA SILIC PINK 61 MM MONDI CLIPS |                         |               | 215160         |                  | 8              | ROH          | 150             |                   |            | 215161              |               | CINTA SILIC PINK 61 MM MONDI CLIPS | CONS_LATAM   |          |                 | 365            |
      | EA      | X                    |       |          | 10       |                 |      |           |                        |                    |                    | EA           |                   |                              | FNW011             | 174461              | ROH               | CINTA SILIC PINK 61 MM MONDI CLIPS |                         |               | 174461         |                  | 8              | ROH          | 150             |                   |            | 174461              |               | CINTA SILIC PINK 61 MM MONDI CLIPS | CONS_LATAM   |          |                 | 365            |
      | EA      | X                    |       |          | 10       |                 |      |           |                        |                    |                    | EA           |                   |                              | FNW011             | 213481              | ROH               | CINTA SILIC PINK 61 MM MONDI CLIPS |                         |               | 213481         |                  | 8              | ROH          | 150             |                   |            | 213481              |               | CINTA SILIC PINK 61 MM MONDI CLIPS | CONS_LATAM   |          |                 | 365            |
      | EA      | X                    |       |          | 10       |                 |      |           |                        |                    |                    | EA           |                   |                              | FNW011             | 441346              | ROH               | CINTA SILIC PINK 61 MM MONDI CLIPS |                         |               |                |                  | 8              | ROH          | 150             |                   |            | 441346              |               | CINTA SILIC PINK 61 MM MONDI CLIPS | CONS_LATAM   |          |                 | 365            |
      | EA      | X                    |       |          | 10       |                 |      |           |                        |                    |                    | EA           |                   |                              | FNW011             | 441363              | ROH               | CINTA SILIC PINK 61 MM MONDI CLIPS |                         |               | 441363         |                  | 8              | ROH          | 150             |                   |            | 441363              |               | CINTA SILIC PINK 61 MM MONDI CLIPS | CONS_LATAM   |          |                 | 365            |
      | EA      | X                    |       |          | 10       |                 |      |           |                        |                    |                    | EA           |                   |                              | FNW011             | 441364              | ROH               | CINTA SILIC PINK 61 MM MONDI CLIPS |                         |               | 441364         |                  | 8              | ROH          | 150             |                   |            | 441364              |               | CINTA SILIC PINK 61 MM MONDI CLIPS | CONS_LATAM   |          |                 | 365            |
      | EA      | X                    |       |          | 10       |                 |      |           |                        |                    |                    | EA           |                   |                              | FNW011             | 441369              | ROH               | CINTA SILIC PINK 61 MM MONDI CLIPS |                         |               | 441369         |                  | 8              | ROH          | 150             |                   |            | 441369              |               | CINTA SILIC PINK 61 MM MONDI CLIPS | CONS_LATAM   |          |                 | 365            |
    And I wait "/edm/material_global_v1" Async Queue complete

    Given I import "/edm/plant_v1" by keyFields "localPlant,sourceSystem"
      | country | localCountry | localCurrency | localPlanningRelevant | localPlant | localPlantName                   | localPlantType | plant | plantType               | region                                    | site                 | sourceSystem |
      | MX      | MX           | MXN           | X                     | MX02       | Sales & Marketing                | DC             | MX32  | DC, Distribution Center | MX, MEXICO MEXICO                         | Importadora DC       | CONS_LATAM   |
      | VE      | VE           | VEF           | X                     | VE02       | J&J VE-Valencia-DistribuiciÃ³n   | DC             | VE07  | DC, Distribution Center | VE, VENEZUELA VENEZUELA                   | Valencia DC          | CONS_LATAM   |
      | GT      | GT           | GTQ           | X                     | GT02       | J&J Guatemala - Bond Fiscal      | DC             | GT02  | DC, Distribution Center | GT, GUATEMALA GUATEMALA                   | Guatemala BF DC      | CONS_LATAM   |
      | PA      | PA           | PAB           | X                     | PA01       | J&J Panama - S&M Consumer        | DC             | PA05  | DC, Distribution Center | PA, PANAMA PANAMA                         | Panama DC            | CONS_LATAM   |
      | GT      | GT           | GTQ           | X                     | GT01       | J&J Guatemala - S&M Consumer     | DC             | GT01  | DC, Distribution Center | GT, GUATEMALA GUATEMALA                   | Guatemala DC         | CONS_LATAM   |
      | MX      | MX           | MXN           | X                     | MX01       | PT Importado                     | DC             | MX31  | DC, Distribution Center | MX, MEXICO MEXICO                         | PT Importadora DC    | CONS_LATAM   |
      | CL      | CL           | CLP           | X                     | CL01       | J&J CL-Santiago-Chile Consumer   | DC             | CL03  | DC, Distribution Center | CL, CHILE CHILE                           | Chile DC             | CONS_LATAM   |
      | PY      | PY           | PYG           | X                     | PY01       | S & M Consumer                   | DC             | PY01  | DC, Distribution Center | PY, PARAGUAY PARAGUAY                     | Paraguay             | CONS_LATAM   |
      | PA      | PA           | PAB           | X                     | PA03       | J&J Panama - Zona Libre          | DC             | PA06  | DC, Distribution Center | PA, PANAMA PANAMA                         | Panama Zona Libre DC | CONS_LATAM   |
      | BR      | BR           | BRL           | X                     | BR07       | J&J BR-JoÃ£o Pessoa-COM&Distrib  | DC             | BR54  | DC, Distribution Center | BR, BRAZIL BRAZIL                         | Pessoa DC            | CONS_LATAM   |
      | VE      | VE           | VEF           | X                     | VE01       | J&J VE-Valencia-Planta           | DC             | VE06  | MP, Manufacturing Plant | VE, VENEZUELA VENEZUELA                   | Valencia             | CONS_LATAM   |
      | UY      | UY           | UYU           | X                     | UY05       | S & M Consumer RecintoAduanero   | DC             | UY05  | DC, Distribution Center | UY, URUGUAY URUGUAY                       | Recinto Aduanero     | CONS_LATAM   |
      | CR      | CR           | CRC           |                       | CR01       | J&J Costa Rica - S&M Consumer    | DC             | CR01  | DC, Distribution Center | CR, COSTA RICA COSTA RICA                 | Costa Rica DC        | CONS_LATAM   |
      | UY      | UY           | UYU           | X                     | UY01       | S & M Consumer                   | DC             | UY07  | DC, Distribution Center | UY, URUGUAY URUGUAY                       | Uruguay              | CONS_LATAM   |
      | AR      | AR           | ARS           | X                     | AR01       | Pilar Plant                      | DC             | AR06  | MP, Manufacturing Plant | AR, ARGENTINA ARGENTINA                   | Pilar                | CONS_LATAM   |
      | DO      | DO           | DOP           | X                     | DO01       | J&J DO-S.Domingos 1-R.Dominica   | DC             | DO02  | DC, Distribution Center | DO, DOMINICAN REPUBLIC DOMINICAL REPUBLIC | Dominica             | CONS_LATAM   |
      | CO      | CO           | BRL           | X                     | CO01       | J&J Colombia - LADS (CO01)       | DC             | CO07  | MP, Manufacturing Plant | CO, COLOMBIA COLOMBIA                     | Cali                 | CONS_LATAM   |
      | VE      | VE           | VEF           | X                     | VE05       | J&J VE-Valencia-ETHNOR           |                | VE05  | DC, Distribution Center | VE, VENEZUELA VENEZUELA                   | Valencia Ethnor DC   | CONS_LATAM   |
      | AR      | AR           | ARS           | X                     | AR02       | S & M Pilar                      | DC             | AR07  | DC, Distribution Center | AR, ARGENTINA ARGENTINA                   | Pilar DC             | CONS_LATAM   |
      | BR      | BR           | BRL           | X                     | BR12       | J&J BR SÃ£o JosÃ© Campos - Indus | DC             | BR59  | MP, Manufacturing Plant | BR, BRAZIL BRAZIL                         | Sao Jose dos Campos  | CONS_LATAM   |
      | PE      | PE           | PEN           | X                     | PE01       | J&J PE-Lima-S&M                  | DC             | PE03  | DC, Distribution Center | PE, PERU PERU                             | Peru DC              | CONS_LATAM   |
      | BR      | BR           | BRL           | X                     | BR25       | J&J BR-GoiÃ¢nia - Com&Distrib    | DC             | BR69  | DC, Distribution Center | BR, BRAZIL BRAZIL                         | Goiania DC           | CONS_LATAM   |
      | BR      | BR           | BRL           | X                     | BR19       | J&J BR-Nova Odessa - Com&Distr   | DC             | BR63  | DC, Distribution Center | BR, BRAZIL BRAZIL                         | Nova Odessa DC       | CONS_LATAM   |
      | CR      | CR           | CRC           | X                     | CR02       | J&J Costa Rica - Bond Fiscal     | DC             | CR02  | DC, Distribution Center | CR, COSTA RICA COSTA RICA                 | Costa Rica BF DC     | CONS_LATAM   |
      | CO      | CO           | BRL           | X                     | CO02       | J&J Colombia - S&M (CO02)        | DC             | CO08  | DC, Distribution Center | CO, COLOMBIA COLOMBIA                     | Cali DC              | CONS_LATAM   |
      | BR      | BR           | BRL           | X                     | BR16       | J&J BR-Extrema - Com&Distrib     | DC             | BR61  | DC, Distribution Center | BR, BRAZIL BRAZIL                         | Extrema DC           | CONS_LATAM   |
      | EC      | EC           | BRL           | X                     | EC01       | Johnson & Johnson del Ecuador    | DC             | EC03  | DC, Distribution Center | EC, ECUADOR ECUADOR                       | Ecuador DC           | CONS_LATAM   |
    And I wait "/edm/plant_v1" Async Queue complete

    Given I import "/plan/cns_material_plan_status" by keyFields "localMaterialNumber,localPlant,sourceSystem"
      | active | dpRelevant | localMaterialNumber | localParentCode   | localPlant | materialNumber | noPlanRelevant | parentActive | ppc    | sourceSystem | spRelevant |
      | X      | X          | 138821              | 78912700000000000 | BR12       | 138821         | X              | X            | 138821 | CONS_LATAM   |            |
      | X      | X          | 189915              | 78910100000000000 | BR12       | 189915         | X              | X            | 189915 | CONS_LATAM   |            |
      | X      | X          | 215161              | 78910100000000000 | BR12       | 215160         | X              | X            | 215161 | CONS_LATAM   |            |
      | X      | X          | 174461              | 975930150         | CO01       | 174461         | X              | X            | 174461 | CONS_LATAM   |            |
      | X      |            | 213481              |                   | AR01       | 213481         | X              | X            | 213481 | CONS_LATAM   |            |
      | X      | X          | 441346              |                   | AR01       | 441346         |                |              | 441346 | CONS_LATAM   | X          |
      | X      | X          | 441363              |                   | AE01       | 441363         | X              |              | 441363 | CONS_LATAM   |            |
      | X      | X          | 441364              |                   | CO02       | 441364         | X              |              | 441364 | CONS_LATAM   |            |
      | X      | X          | 441369              |                   | CR01       | 441369         | X              |              | 441369 | CONS_LATAM   |            |
    And I wait "/plan/cns_material_plan_status" Async Queue complete

    Given I import "/plan/cns_plan_object_filter" by keyFields "sourceObjectAttribute1,sourceObjectAttribute2,sourceObjectAttribute2Value,sourceObjectTechName,sourceSystem"
      | inclusionExclusion | sourceObjectAttribute1 | sourceObjectAttribute1Value | sourceObjectAttribute2 | sourceObjectAttribute2Value | sourceObjectTechName | sourceSystem |
      | I                  | plntCd                 | CO01                        | planOrdrTypeCd         | NB                          | planned_order        | CONS_LATAM   |
      | I                  | plntCd                 | CO01                        | planOrdrTypeCd         | NB                          | planned_order        | CONS_LATAM   |
      | I                  | plntCd                 | AR01                        | planOrdrTypeCd         | NB                          | planned_order        | CONS_LATAM   |
      | I                  | plntCd                 | BR12                        | planOrdrTypeCd         | LA                          | planned_order        | CONS_LATAM   |
      | I                  | plntCd                 | CO01                        | planOrdrTypeCd         | LA                          | planned_order        | CONS_LATAM   |
      | I                  | plntCd                 | AR01                        | planOrdrTypeCd         | LA                          | planned_order        | CONS_LATAM   |
      | E                  | plntCd                 | AE01                        | planOrdrTypeCd         | NA                          | planned_order        | CONS_LATAM   |
      | E                  | plntCd                 | CO02                        | planOrdrTypeCd         | LB                          | planned_order        | CONS_LATAM   |
      | E                  | plntCd                 | CR01                        | planOrdrTypeCd         | NB                          | planned_order        | CONS_LATAM   |
    And I wait "/plan/cns_plan_object_filter" Async Queue complete

    When I submit task with xml file "xml/gdm_stock_5_planned_order.xml" and execute file "jar/pangea-view.jar"

    Then A file is found on sink application with name "GDMStock_plannedOrder.tsv"
    Then I check file data for filename "GDMStock_plannedOrder.tsv" by keyFields "stockId"
      | stockId                          | active | activeOPRERP | activeSOPERP | batchId | blockedQuantity | consignment | certaintyId | erpOrderId | inventoryLinkGroupId | vendorId | locationId      | processId                | processTypeId | productId | qualityQuantity | quantity | receiptDate         | restrictedQuantity | returnsQuantity | startDate           | stockType | transferQuantity | transitDate         | unrestrictedQuantity |
      | 138821/CONS_LATAM_BR12/49748397  | YES    | YES          | NO           |         | 0.0             | NO          | PA          | 49748397   |                      |          | CONS_LATAM_BR12 | 0/138821/CONS_LATAM_BR12 | Production    | 138821    | 0.0             | 36300    | 2018/09/04 00:00:00 | 0.0                | 0.0             | 2018/09/04 00:00:00 | movement  | 0.0              | 1980/01/01 00:00:00 | 0.0                  |
      | 189915/CONS_LATAM_BR12/95941803  | YES    | YES          | NO           |         | 0.0             | NO          | PA          | 95941803   |                      |          | CONS_LATAM_BR12 | 0/189915/CONS_LATAM_BR12 | Production    | 189915    | 0.0             | 86544    | 2018/12/03 00:00:00 | 0.0                | 0.0             | 2018/12/03 00:00:00 | movement  | 0.0              | 1980/01/01 00:00:00 | 0.0                  |
      | 215161/CONS_LATAM_BR12/112368557 | YES    | YES          | NO           |         | 0.0             | NO          | PA          | 112368557  |                      |          | CONS_LATAM_BR12 | 0/215161/CONS_LATAM_BR12 | Production    | 215161    | 0.0             | 5600     | 2018/08/08 00:00:00 | 0.0                | 0.0             | 2018/08/13 00:00:00 | movement  | 0.0              | 1980/01/01 00:00:00 | 0.0                  |
      | 174461/CONS_LATAM_CO01/117229550 | YES    | YES          | NO           |         | 0.0             | NO          | PA          | 117229550  |                      |          | CONS_LATAM_CO01 | 0/174461/CONS_LATAM_CO01 | Production    | 174461    | 0.0             | 12000    | 2018/08/09 00:00:00 | 0.0                | 0.0             | 2018/08/15 00:00:00 | movement  | 0.0              | 1980/01/01 00:00:00 | 0.0                  |
      | 213481/CONS_LATAM_AR01/117229560 | YES    | YES          | NO           |         | 0.0             | NO          | PA          | 117229560  |                      |          | CONS_LATAM_AR01 | 0/213481/CONS_LATAM_AR01 | Production    | 213481    | 0.0             | 15000    | 2018/08/09 00:00:00 | 0.0                | 0.0             | 2018/08/16 00:00:00 | movement  | 0.0              | 1980/01/01 00:00:00 | 0.0                  |
    Then I check region data "/plan/edm_failed_data" by keyFields "functionalArea,interfaceID,errorCode,sourceSystem,key1,key2,key3,key4,key5"
      | functionalArea | interfaceID | errorCode | sourceSystem | businessArea | key1 | key2 | key3 | key4 | key5 | errorValue |

  Scenario: delete all test data

    Then I delete the test data

    And I will remove all data with region "/omp/gdm_stock"

    And I will remove all data with region "/plan/edm_failed_data"
