@pangea_test @AEAZ-4486
Feature:  OMPGdmSupply-Curation

  Scenario: Full Load consumption

    Given I import "/edm/source_list_v1" by keyFields "sourceSystem,localMaterialNumber,localPlant"
      | sourceSystem | localMaterialNumber | localPlant | localNumberofSourceListRecord | materialNumber | plant | localCreatedOn | localCreatedBy | localSourceListRecordValidFrom | localSourceListRecordValidTo | localVendorAccountNumber | localFixedvendor | localAgreementNumber | localAgreementItem | localFixedOutlinePurchaseAgreementItem | localPlantfromWhichMaterialisProcured | localMatForManufPartNumber | localBlockedSourceofSupply | localPurchasingOrganization | localPurchasingDocumentCategory | localCategoryofSourceListRecord | localSourceListUsageinMaterialsPlanning |
      | CONS_LATAM   | 3                   | MX02       | 4                             | 51178          | AR01  | 20030306       | CCASTRO1       | 20120718                       | 99991230                     | 6109                     |                  |                      | 0                  |                                        |                                       |                            |                            | MX01                        |                                 | 7                               |                                         |
      | CONS_LATAM   | 4                   | BR16       | 5                             | 945            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     | 2519                     |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 5                   | BR06       | 6                             | 71325          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     |                          |       1          |                      | 0                  |     1                                  |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 6                   | VE01       | 3                             | 1331           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     |                          |       1          |                      | 0                  |     1                                  |                                       |                            |                            | VE00                        |                                 | 4                               |                                         |
      | CONS_LATAM   | 7                   | MX02       | 4                             | 92129          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     | 6359                     |                  |                      | 0                  |                                        |                                       |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   | 8                   | MX02       | 4                             | 51178          | AR01  | 20030306       | CCASTRO1       | 20120718                       | 99991230                     | 6109                     |                  |                      | 0                  |                                        |                                       |                            |                            | MX01                        |                                 | 7                               |                                         |
      | CONS_LATAM   | 9                   | BR16       | 5                             |                | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     |                          |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      |              | 10                  | BR06       | 6                             | 71325          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     |       1          |                      | 0                  |     1                                  |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 11                  | VE01       | 3                             | 1331           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     | 8917                     |                  |                      | 0                  |                                        |                                       |                            |                            |                             |                                 | 4                               |                                         |
      | CONS_LATAM   | 12                  | MX02       | 4                             | 92129          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     | 6359                     |       1          |                      | 0                  |     1                                  |                                       |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   | 13                  | MX02       | 4                             | 51178          | AR01  | 20030306       | CCASTRO1       | 20120718                       | 99991230                     |                          |                  |                      | 0                  |                                        | MX01                                  |                            |                            | MX01                        |                                 | 7                               |                                         |
      | CONS_LATAM   | 14                  | BR16       | 5                             | 945            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     | 2519                     |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 15                  | BR06       | 6                             | 71325          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     |                  |                      | 0                  |                                        | BR00                                  |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 16                  | VE01       | 3                             | 1331           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     |                          |                  |                      | 0                  |                                        |                                       |                            |                            | VE00                        |                                 | 4                               |                                         |
      | CONS_LATAM   | 17                  | MX02       | 4                             | 92129          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     | 6359                     |       1          |                      | 0                  |     1                                  |                                       |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   | 18                  | MX02       | 5                             | 945            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     |                          |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 19                  | BR16       | 6                             | 71325          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     |       1          |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 20                  | BR06       | 3                             | 1331           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     |                          |                  |                      | 0                  |                                        |                                       |                            |                            | VE00                        |                                 | 4                               |                                         |
      | CONS_LATAM   | 21                  | VE01       | 4                             | 92129          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     | 6359                     |                  |                      | 0                  |                                        |                                       |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   | 22                  | MX02       | 5                             | 945            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     | 2519                     |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 23                  | BR06       | 6                             | 71325          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     |                          |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 24                  | BR06       | 3                             | 1331           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     |                          |                  |                      | 0                  |                                        | VE00                                  |                            |                            | VE00                        |                                 | 4                               |                                         |
      | CONS_LATAM   | 25                  | VE01       | 4                             | 92129          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     |                          |       1          |                      | 0                  |                                        |                                       |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   |                     | VE01       | 5                             | 945            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     | 2519                     |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 27                  | MX02       | 6                             | 71325          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     |                  |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 28                  | MX02       | 3                             | 1331           | AR01  | 20030306       | CCASTRO1       | 20060910                       | 29991231                     | 8917                     |                  |                      | 0                  |                                        | VE00                                  |                            |                            | VE00                        |                                 | 4                               |                                         |
      | CONS_LATAM   | 29                  | MX02       | 4                             | 92129          | AR01  | 20030306       | CCASTRO1       | 20090508                       | 99991230                     | 6359                     |                  |                      | 0                  |                                        | MX01                                  |                            |                            | MX01                        |                                 | 5                               |                                         |
      | CONS_LATAM   | 30                  | VE01       | 5                             | 945            | AR01  | 20030306       | CCASTRO1       | 20150731                       | 99991230                     | 2519                     |                  |                      | 0                  |                                        | BR00                                  |                            |                            | BR00                        |                                 | 8                               |                                         |
      | CONS_LATAM   | 31                  | VE01       | 6                             | 71325          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     |       1          |                      | 0                  |                                        |                                       |                            |                            | BR00                        |                                 | 9                               |                                         |
      | CONS_LATAM   | 32                  | MX02       | 6                             | 71325          | AR01  | 20030306       | CCASTRO1       | 20070108                       | 29991231                     | 8917                     |       1          |                      | 0                  |                                        | BR00                                  |                            |                            | BR00                        |                                 | 9                               |                                         |

    And I wait "/edm/source_list_v1" Async Queue complete

    Given I import "/edm/plant_v1" by keyFields "localPlant,sourceSystem"
      | sourceSystem | localPlant | plant | localPlanningRelevant | localMaterialNumber |
      | CONS_LATAM   | MX02       | AR01  |          X            | 3                   |
      | CONS_LATAM   | BR16       | AR01  |          X            | 4                   |
      | CONS_LATAM   | BR06       | AR01  |          X            | 5                   |
      | CONS_LATAM   | VE01       | AR01  |          X            | 6                   |
      | CONS_LATAM   | MX02       | AR01  |          X            | 7                   |
      | CONS_LATAM   | MX02       | AR01  |          X            | 8                   |
      | CONS_LATAM   | BR16       | AR01  |          X            | 9                   |
      | CONS_LATAM   | BR06       | AR01  |          X            | 10                  |
      | CONS_LATAM   | VE01       | AR01  |          X            | 11                  |
      | CONS_LATAM   | MX02       | AR01  |                       | 12                  |
      | CONS_LATAM   | MX02       | AR01  |          A            | 13                  |
      | CONS_LATAM   | BR16       | AR01  |          X            | 14                  |
      | CONS_LATAM   | BR06       | AR01  |          X            | 15                  |
      | CONS_LATAM   | VE01       | AR01  |          X            | 16                  |
      | CONS_LATAM   | MX02       | AR01  |          X            | 17                  |
      | CONS_LATAM   | MX02       | AR01  |          X            | 18                  |
      | CONS_LATAM   | BR16       | AR01  |          X            | 19                  |
      | CONS_LATAM   | BR06       | AR01  |          X            | 20                  |
      | CONS_LATAM   | VE01       | AR01  |          X            | 21                  |
      | CONS_LATAM   | MX02       | AR01  |          X            | 22                  |
      | CONS_LATAM   | BR06       | AR01  |          X            | 23                  |
      | CONS_LATAM   | BR06       | AR01  |          X            | 24                  |
      | CONS_LATAM   | VE01       | AR01  |          X            | 25                  |
      | CONS_LATAM   | VE01       | AR01  |          X            | 26                  |
      |              | MX02       | AR01  |          X            | 27                  |
      | CONS_LATAM   |            | AR01  |          X            | 28                  |
      | CONS_LATAM   | VE01       | AR01  |          X            | 29                  |
      | CONS_LATAM   | VE01       | AR01  |          X            | 30                  |
      | CONS_LATAM   | VE01       | AR01  |          X            | 31                  |

    And I wait "/edm/plant_v1" Async Queue complete

    Given I import "/edm/material_global_v1" by keyFields "localMaterialNumber,sourceSystem"
      | localMaterialNumber | materialNumber | sourceSystem | primaryPlanningCode |
      | 3                   | 51178          | CONS_LATAM   | 51178               |
      | 4                   | 945            | CONS_LATAM   | 945                 |
      | 5                   | 71325          | CONS_LATAM   | 71325               |
      | 6                   | 1331           | CONS_LATAM   | 1331                |
      | 7                   | 92129          | CONS_LATAM   | 92129               |
      | 8                   | 51178          | CONS_LATAM   | 51178               |
      | 9                   |                | CONS_LATAM   |                     |
      | 10                  | 71325          | CONS_LATAM   | 71325               |
      | 11                  | 1331           | CONS_LATAM   | 1331                |
      | 12                  | 92129          | CONS_LATAM   | 92129               |
      | 13                  | 51178          | CONS_LATAM   | 51178               |
      | 14                  | 945            | CONS_LATAM   | 945                 |
      | 15                  | 71325          | CONS_LATAM   | 71325               |
      | 16                  | 1331           | CONS_LATAM   | 1331                |
      | 17                  | 92129          | CONS_LATAM   | 92129               |
      | 18                  | 945            | CONS_LATAM   | 945                 |
      | 19                  | 71325          | CONS_LATAM   | 71325               |
      | 20                  | 1331           | CONS_LATAM   | 1331                |
      | 21                  | 92129          | CONS_LATAM   | 92129               |
      | 22                  | 945            | CONS_LATAM   | 945                 |
      | 23                  | 71325          | CONS_LATAM   | 71325               |
      | 24                  | 1331           | CONS_LATAM   | 1331                |
      | 25                  | 92129          | CONS_LATAM   | 92129               |
      |                     | 945            | CONS_LATAM   | 945                 |
      | 32                  | 71325          | CONS_LATAM   | 71325               |

    And I wait "/edm/material_global_v1" Async Queue complete

    Given I import "/edm/material_plant_v1" by keyFields "sourceSystem,localMaterialNumber,localPlant"
      | sourceSystem | localMaterialNumber | localPlant | materialNumber | plant  | localPlantStatus | plantStatus | localProcurementType | localDeletionFlagPlant | localFixedlotsize | localMaximumLotSize | localMinimumLotSize | localRoundingValueForPoq | localLotsize | localMrpType | localMrpController | localInHouseProcessingTime | localSafetyStock | localMinimumSafetyStock | localProductionSupervisor | localProductionUnit | localPosttoInspectionStock | localComponentScrapInPercent | localCriticalpart | localAbcIndicator | localMaximumStocklevel | localCheckingGroupforAvailabilityCheck | localPlannedDeliveryTimeInDays | localDependentRequirements | localSafetytimeIndicator | localSafetyTime | localSpecialProcurementType | localPlanningStrategyGroup | localConsumptionPeriodBackward | localConsumptionPeriodForward | localConsumptionMode | localGoodsReceiptProcessingTimeInDays | localBatchManagementRequirmentIndicator | localPlanningTimeFence | localPosttoinspstk | localComponentScrap | localBaseQuantity |localPurchasingGroup |
      | CONS_LATAM   | 3                   | MX02       | 7703910        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 10                  | 1                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |
      | CONS_LATAM   | 4                   | BR16       | 7703911        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 100                 | 2                   | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 5                   | BR06       | 7703912        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 1000                | 3                   | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 6                   | VE01       | 7703913        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 20                  |                     | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               | 30                          | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00                |
      | CONS_LATAM   | 7                   | MX02       | 7703914        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 50                  |                     | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               | 30                          | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |
      | CONS_LATAM   | 8                   | MX02       | 7703915        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 75                  |                     | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               | 30                          | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |
      | CONS_LATAM   | 9                   | BR16       | 7703916        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 25                  | 7                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 10                  | BR06       | 7703917        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     | 8                   | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 11                  | VE01       | 7703918        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     | 9                   | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00                |
      | CONS_LATAM   | 12                  | MX02       | 7703919        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 15                  | 10                  | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |
      | CONS_LATAM   | 13                  | MX02       | 7703920        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 25                  | 11                  | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 30                             | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |
      | CONS_LATAM   | 14                  | BR16       | 7703921        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 12                  | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 15                  | BR06       | 7703922        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 13                  | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 16                  | VE01       | 7703923        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 65                  | 0                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00                |
      | CONS_LATAM   | 17                  | MX02       | 7703924        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00                |
      | CONS_LATAM   | 18                  | MX02       | 7703925        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |
      | CONS_LATAM   | 19                  | BR16       | 7703926        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 20                  | BR06       | 7703927        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 21                  | VE01       | 7703928        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00                |
      | CONS_LATAM   |                     | MX02       | 7703929        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 0                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00                |
      | CONS_LATAM   | 23                  | BR06       | 7703930        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 0                   | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |
      | CONS_LATAM   | 24                  | BR06       |                | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 0                   | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 25                  | VE01       | 7703932        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     | 0                   | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 26                  | VE01       | 7703933        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 0                   |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00                |
      | CONS_LATAM   | 27                  | MX02       | 7703934        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |
      | CONS_LATAM   | 28                  | MX02       | 7703935        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00                |
      | CONS_LATAM   | 29                  | VE01       | 7703936        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 500.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 30                  | VE01       | 7703937        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     | 0                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 31                  | VE01       | 7703938        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 65                  |                     | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | BR00                |
      | CONS_LATAM   | 32                  | BR16       | 7703939        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 0                   |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |
      | CONS_LATAM   | 33                  | BR06       | 7703940        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |
      | CONS_LATAM   | 34                  | VE01       | 7703941        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             |                     |                     | 1000.000                 | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | VE00                |
      | CONS_LATAM   | 35                  | MX02       | 7703942        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 0                   |                     | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |
      | CONS_LATAM   | 36                  | VE01       | 7703943        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 0                   | 100.000                  | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               |                             | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               |                     |
      | CONS_LATAM   | 37                  | MX02       | 7703944        | AR01   | 05               | 101         | F                    | BR02                   | 0.001             | 0                   | 0                   | 0.001                    | EX1          | X4           | 152                | 2                          | 0.001            | 0.001                   | 002                       | 0.001               | 0.001                      | 0.001                        | 0.001             | 0.001             | 0.001                  | 02                                     | 1                              | 1                          | 1                        | 1               | 30                          | 1                          | 1                              | 1                             | 1                    | 1                                     | 1                                       | 1                      | 0.001              | 0.001               | BA1               | MX01                |

    And I wait "/edm/material_plant_v1" Async Queue complete

    Given I import "/plan/cns_material_plan_status" by keyFields "sourceSystem,localMaterialNumber,localPlant"
      | sourceSystem | localMaterialNumber | localPlant | materialNumber    | localParentCode | ppc | active | dpRelevant | spRelevant | parentActive | noPlanRelevant |
      | CONS_LATAM   | 3                   | MX02       | 7703910           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 4                   | BR16       | 7703911           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 5                   | BR06       | 7703912           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 6                   | VE01       | 7703913           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 7                   | MX02       | 7703914           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 8                   | MX02       | 7703915           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 9                   | BR16       | 7703916           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 10                  | BR06       | 7703917           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 11                  | VE01       | 7703918           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 12                  | MX02       | 7703919           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 13                  | MX02       | 7703920           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 14                  | BR16       | 7703921           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 15                  | BR06       | 7703922           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 16                  | VE01       | 7703923           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 17                  | MX02       | 7703924           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 18                  | MX02       | 7703925           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 19                  | BR16       | 7703926           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 20                  | BR06       | 7703927           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 21                  | VE01       | 7703928           | G3a             | G4a | X      | X          |            | X            | X              |
      | CONS_LATAM   | 22                  | MX02       | 7703929           | G3a             | G4a | X      | X          |  Z         | X            | X              |
      | CONS_LATAM   | 23                  | BR06       | 7703930           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 24                  | BR06       | 7703931           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 25                  | VE01       | 7703932           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 26                  | VE01       | 7703933           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 27                  | MX02       | 7703939           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 28                  | MX02       | 7703940           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   |                     | VE01       | 7703941           | G3a             | G4a | X      | X          |  X         | X            | X              |
      | CONS_LATAM   | 30                  |            | 7703942           | G3a             | G4a | X      | X          |  X         | X            | X              |
      |              | 31                  | VE01       | 7703943           | G3a             | G4a | X      | X          |  X         | X            | X              |

    And I wait "/plan/cns_material_plan_status" Async Queue complete

    Given I import "/plan/cns_process_type" by keyFields "processTypeId,processTypeDesc"
      | processTypeId           | processTypeDesc                                                                                                                                 |
      | ExternalPurchase        | External Purchase                                                                                                                               |
      | ExternalTransport       | External Transport (Transport from 1 fiscal entity to another fiscal entity in the same ERP system, modeled through sales order/purchase order) |
      | InterERPTransport       | InterERP Transport (Transport between 2 different ERP systems, modeled through sales order/purchase order)                                      |
      | InternalTransport       | Internal Transport (Transport from 1 plant to another plant in the same ERP system, modeled through transport lanes in SAP)                     |
      | Production              | Production                                                                                                                                      |
      | SubcontractingTransport | Subcontracting Transport (Transport to ship components to a subcontractor)                                                                      |
      | Subcontracting          | Subcontracting                                                                                                                                  |
      | VendorPurchase          | Vendor Purchase                                                                                                                                 |
      | VendorTransport         | Vendor Transport (specific for the Pangea Vendor modeling: transport from a Vendor location to a plant)                                         |

    And I wait "/plan/cns_process_type" Async Queue complete

    Given I import "/plan/cns_spl_pln_loc" by keyFields "localNumber,vendorOrCustomer,sourceSystem,localPlant"
      | localNumber | vendorOrCustomer | sourceSystem | localPlant |
      | 6109        | V                | CONS_LATAM   | MX02       |
      | 6109        |                  | CONS_LATAM   | MX02       |
      | 2519        | V                | CONS_LATAM   |            |
      | 2519        |                  | CONS_LATAM   |            |
      | 6359        | V                | CONS_LATAM   | BR16       |
      | 6359        |                  | CONS_LATAM   | BR16       |
      | 8917        | V                | CONS_LATAM   |            |
      | 8917        |                  | CONS_LATAM   |            |


    And I wait "/plan/cns_spl_pln_loc" Async Queue complete

    When I submit task with xml file "xml/omp/OMPGdmSupply.xml" and execute file "jar/pangea-view.jar"

    Then A file is found on sink application with name "GDMSupply.tsv"

    And I check file data for filename "GDMSupply.tsv" by keyFields "SupplyId"
      | PROCESSTYPEID    | PURCHASINGORGANIZATION | PURCHASINGGROUP | LocationId             | INCQuantity | ProductId | MinQuantity | ActiveSOPERP |   SupplierId      | Active | VENDORID | Preference | ActiveOPRERP | LABEL             |  FromDate           | ToDate              | MaxQuantity | TransportType | SupplyId                   |
      | VendorPurchase   | BR00                   | BR00            | CONS_LATAM_BR16_V_8917 | 1000.000    | 71325     |             | NO           | CONS_LATAM_V_8917 | YES    | 8917     | 0          | YES          | Vendor Purchase   | 2007/01/08 00:00:00 | 2999/12/31 00:00:00 |             | DEFAULT       | 71325/CONS_LATAM_BR16/8917 |
      | VendorPurchase   | BR00                   | BR00            | CONS_LATAM_BR06        | 1000.000    | 71325     | 13          | NO           | CONS_LATAM_V_8917 | YES    | 8917     | 1          | YES          | Vendor Purchase   | 2007/01/08 00:00:00 | 2999/12/31 00:00:00 | 0           | DEFAULT       | 71325/CONS_LATAM_BR06/8917 |
      | VendorPurchase   | BR00                   | BR00            | CONS_LATAM_BR16_V_2519 | 0.001       | 945       | 12          | NO           | CONS_LATAM_V_2519 | YES    | 2519     | 1          | YES          | Vendor Purchase   | 2015/07/31 00:00:00 | 9999/12/30 00:00:00 | 0           | DEFAULT       | 945/CONS_LATAM_BR16/2519   |
      | ExternalPurchase | MX01                   | VE00            | CONS_LATAM_MX02_V_6359 | 0.001       | 92129     |             | NO           | CONS_LATAM_V_6359 | YES    | 6359     | 0          | YES          | External Purchase | 2009/05/08 00:00:00 | 9999/12/30 00:00:00 |             | DEFAULT       | 92129/CONS_LATAM_MX02/6359 |
      | VendorPurchase   | MX01                   | MX01            | CONS_LATAM_MX02        | 100.000     | 51178     |             | NO           | CONS_LATAM_V_6109 | YES    | 6109     | 1          | YES          | Vendor Purchase   | 2012/07/18 00:00:00 | 9999/12/30 00:00:00 | 75          | DEFAULT       | 51178/CONS_LATAM_MX02/6109 |
      | VendorPurchase   | MX01                   | MX01            | CONS_LATAM_MX02_V_6109 | 0.001       | 51178     | 1           | NO           | CONS_LATAM_V_6109 | YES    | 6109     | 1          | YES          | Vendor Purchase   | 2012/07/18 00:00:00 | 9999/12/30 00:00:00 | 10          | DEFAULT       | 51178/CONS_LATAM_MX02/6109 |
      | ExternalPurchase | MX01                   | MX01            | CONS_LATAM_MX02_V_6359 | 500.000     | 92129     | 10          | NO           | CONS_LATAM_V_6359 | YES    | 6359     | 0          | YES          | External Purchase | 2009/05/08 00:00:00 | 9999/12/30 00:00:00 | 15          | DEFAULT       | 92129/CONS_LATAM_MX02/6359 |
      | ExternalPurchase | MX01                   | MX01            | CONS_LATAM_MX02        | 100.000     | 92129     |             | NO           | CONS_LATAM_V_6359 | YES    | 6359     | 1          | YES          | External Purchase | 2009/05/08 00:00:00 | 9999/12/30 00:00:00 | 50          | DEFAULT       | 92129/CONS_LATAM_MX02/6359 |
      | VendorPurchase   | BR00                   | BR00            | CONS_LATAM_BR16_V_2519 | 100.000     | 945       | 2           | NO           | CONS_LATAM_V_2519 | YES    | 2519     | 1          | YES          | Vendor Purchase   | 2015/07/31 00:00:00 | 9999/12/30 00:00:00 | 100         | DEFAULT       | 945/CONS_LATAM_BR16/2519   |
      | VendorPurchase   |                        | VE00            | CONS_LATAM_VE01_V_8917 | 1000.000    | 1331      | 9           | NO           | CONS_LATAM_V_8917 | YES    | 8917     | 1          | YES          | Vendor Purchase   | 2006/09/10 00:00:00 | 2999/12/31 00:00:00 |             | DEFAULT       | 1331/CONS_LATAM_VE01/8917  |
    
    Then I check region data "/dev/plan/edm_failed_data" by keyFields "errorCode,functionalArea,interfaceID,key1,key2,key3,key4,key5,sourceSystem"
      | errorCode | errorValue                                                             | functionalArea | interfaceID  | key1        | key2    | key3 |    key4    |    key5    | sourceSystem |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM  | 27      | MX02 |            |            | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM  | 28      | MX02 |            |            | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM  | 29      | MX02 |            |            | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM  | 30      | VE01 |            |            | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM  | 31      | VE01 |            |            | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM  | 9       | BR16 |            |            | CONS_LATAM   |
      | N1        | Material Global V1 Primary planning code and Material Number are blank | SP             | OMPGdmSupply | CONS_LATAM  |         | VE01 |            |            | CONS_LATAM   |

    And I will remove all data with region "/edm/source_list_v1"

    And I will remove all data with region "/edm/plant_v1"

    And I will remove all data with region "/edm/material_global_v1"

    And I will remove all data with region "/edm/material_plant_v1"

    And I will remove all data with region "/plan/cns_material_plan_status"

    And I will remove all data with region "/plan/cns_process_type"

    And I will remove all data with region "/plan/cns_spl_pln_loc"

    And I will remove the test file on sink application "GDMSupply.tsv"

