@pangea_test @AEAZ-5870
Feature:  OMPGdmStockPurchaseOrder-Curation

  Scenario: Full Load consumption

    Given I import "/edm/purchase_order_oa_v1" by keyFields "delvSchedCntNbr,evTypeCd,localSeqNumActAsgn,localSeqNumVendConf,matlMvmtNum,matlMvmtSeqNbr,matlMvmttYr,poLineNbr,poNum,sourceSystem"
      | sourceSystem |    poNum   | poLineNbr | evTypeCd | matlMvmttYr | matlMvmtNum | matlMvmtSeqNbr | delvSchedCntNbr | poCatTypeCd | poTypeCd | crtOnDt | supNum | prchsngOrgNum | prchsngGrpNum | prchsngCoCd | crncyCd |   poDt   | vldFromDt | vldToDt | suplVendNum | suplPlntCd | rlseCmpltInd | rlseDocInd | delInd | matlNum | plntCd | slocCd | intrnlRefNum | poLineQty | poUomCd | localNumerator | localDenominator | stkTypeCd | delvCmpltInd | lineItemTypeCd | acctAsgnmtCatCd | prinPrchAgmtNum | prinPrchAgmtLineNbr | localBaseUOM | delvAddrNum | localPDT | localSpecialStock | cnfrmCd | subcntrcInd | localdelvAddrNum | prDocId    | prLineNbr | localBrazilianNCMCode | isuSlocCd | poHistCatCd | localMovementType | localPostingDate | recvEaQty | cnfrmSeqNbr | delvDt  | crtOnDt | cnfrmQty | mrpAdjQty | localCreationIndVendorConf | slsOrdrNum | slsOrdrLineNbr | vendBtchNum | localdelvDt | schdQty | recvQty | localPurchaseReq | localPurchaseReqItem | stkTfrRecvQty | localmrpAdjQty | grLeadTimeDays | custNum | localSeqNumActAsgn | localSeqNumVendConf |
      |  CONS_LATAM  | 3000793997 |    10     |    1     |    2017     | 5006382844  |       1        |        1        |      F      |     NB   | 20170102|  6109  |      MX01     |      M39      |     8302    |   MXN   | 20170102 |           |         |             |    MX01    |              |            |        |  58752  | MX01   |  MX01  |              |   1968    |    EA   |         1      |        2         |     X     |     X        |       2        |                 |    5100003715   |        4950         |          EA  |             |    0     |                   |         |             |                  | 1603571115 |     10    |                       |           |    E        |          101      |     20170103     |   0.000   |            | 20170103 |         |    0     |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      |  CONS_LATAM  | 3000793997 |    20     |    1     |    2017     | 5006382844  |       1        |        1        |      F      |     NB   | 20170102|  6109  |      MX01     |      M39      |     8302    |   MXN   | 20170102 |           |         |             |    MX01    |              |            |        |  58752  | MX01   |  MX01  |              |   2000    |    EA   |         1      |        1         |     X     |     X        |       2        |                 |    5100003715   |        4950         |          EA  |             |    0     |                   |         |             |                  | 1603571115 |     10    |                       |           |    E        |          101      |     20170103     |   0.000   |            | 20170103 |         |    200   |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      |  CONS_LATAM  | 3000793997 |    20     |    1     |    2017     | 5006382844  |       1        |        1        |      F      |     NB   | 20170102|  6109  |      MX01     |      M39      |     8302    |   MXN   | 20170102 |           |         |             |    MX01    |              |            |        |  58752  | MX01   |  MX01  |              |   3000    |    EA   |         1      |        1         |     X     |     X        |       2        |                 |    5100003715   |        4950         |          EA  |             |    0     |                   |         |             |                  | 1603571115 |     10    |                       |           |    E        |          101      |     20170103     |   3000.000|            | 20170103 |         |    0     |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      |  CONS_LATAM  | 3000793997 |    11     |    1     |    2017     | 5006382844  |       1        |        1        |      F      |     NB   | 20170102|  6109  |      MX01     |      M39      |     8302    |   MXN   | 20170102 |           |         |             |    MX01    |              |            |        |  58752  | MX01   |  MX01  |              |   1000    |    EA   |         1      |        1         |     X     |     X        |       2        |                 |    5100003715   |        4950         |          EA  |             |    0     |                   |         |             |                  | 1603571115 |     10    |                       |           |    E        |          101      |     20170103     |   200     |            | 20170103 |         |          |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      |  CONS_LATAM  | 3000793997 |    11     |    1     |    2017     | 5006382844  |       1        |        1        |      F      |     NB   | 20170102|  6109  |      MX01     |      M39      |     8302    |   MXN   | 20170102 |           |         |             |    MX01    |              |            |        |  58752  | MX01   |  MX01  |              |   1000    |    EA   |         1      |        1         |     X     |     X        |       2        |                 |    5100003715   |        4950         |          EA  |             |    0     |                   |         |             |                  | 1603571115 |     10    |                       |           |    E        |          101      |     20170103     |   300     |            | 20170103 |         |          |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      |  CONS_LATAM  | 3000793998 |    20     |    1     |    2017     | 5006382844  |       1        |        1        |      L      |     ZLA  | 20170102|  1189  |      BR12     |      M39      |     8302    |   BR    | 20170102 |           |         |             |    BR12    |              |   1        |        |  80990  | BR12   |  BR12  |              |   2350    |    EA   |         1      |        1         |     X     |     X        |       K        |                 |    5100003715   |        4950         |          EA  |             |    0     |                   |         |             |                  | 1603571115 |     10    |                       |           |    E        |          101      |     20170103     |   0.000   |            | 20170103 |         |    250   |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      |  CONS_LATAM  | 3000793999 |    10     |    1     |    2017     | 5006382844  |       1        |        1        |      L      |     ZLA  | 20170102|  1189  |      BR12     |      M39      |     8302    |   BR    | 20170102 |           |         |             |    BR12    |              |   1        |        |  96161  | BR12   |  BR12  |              |   3000    |    EA   |         1      |        1         |     X     |     X        |       K        |                 |    5100003715   |        4950         |          EA  |             |    0     |                   |         |             |                  | 1603571115 |     10    |                       |           |    E        |          101      |     20170103     |   0.000   |            | 20170103 |         |    1000  |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      |  CONS_LATAM  | 3000793995 |    20     |    1     |    2017     | 5006382844  |       1        |        1        |      L      |     ZNB  | 20170102|  1189  |      BR12     |      M39      |     8302    |   BR    | 20170102 |           |         |             |    BR12    |              |   1        |        |  528395 | BR12   |  BR12  |              |   1000    |    EA   |         1      |        1         |     X     |     X        |       K        |                 |    5100003715   |        4950         |          EA  |             |    0     |                   |         |             |                  | 1603571115 |     10    |                       |           |    E        |          101      |     20170103     |   100.000 |            | 20170103 |         |    0     |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      |  CONS_LATAM  | 3000793990 |    40     |    1     |    2017     | 5006382844  |       1        |        1        |      L      |     UB   | 20170102|  1189  |      BR14     |      M39      |     8302    |   BR    | 20170102 |           |         |             |            |              |   1        |        |  57039  | BR14   |  BR14  |              |   2000    |    EA   |         1      |        1         |     X     |     X        |       K        |                 |    5100003715   |        4950         |          EA  |             |    0     |                   |         |             |                  | 1603571115 |     10    |                       |           |    E        |          101      |     20170103     |   200.000 |            | 20170103 |         |    0     |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      |  CONS_LATAM  | 3000793997 |    40     |    1     |    2017     | 5006382844  |       1        |        1        |      F      |     NB   | 20170102|  6109  |      MX01     |      M39      |     8302    |   MXN   | 20170102 |           |         |             |    MX01    |              |            |        |  58752  | MX01   |  MX01  |              |   2000    |    EA   |         1      |        1         |     X     |     X        |       3        |                 |    5100003715   |        4950         |          EA  |             |    0     |                   |         |             |                  | 1603571115 |     10    |                       |           |    E        |          101      |     20170103     |   0.000   |            | 20170103 |         |    200   |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |
      |  CONS_LATAM  | 30007930001|    40     |    1     |    2017     | 5006382844  |       1        |        1        |      F      |     NB   | 20170102|  6109  |      MX01     |      M39      |     8302    |   MXN   | 20170102 |           |         |             |    MX01    |              |            |    X   |  58752  | MX01   |  MX01  |              |   2000    |    EA   |         1      |        1         |     X     |     X        |       3        |                 |    5100003715   |        4950         |          EA  |             |    0     |                   |         |             |                  | 1603571115 |     10    |                       |           |    E        |          101      |     20170103     |   0.000   |            | 20170103 |         |    200   |           |                            |            |                |             |             |         |         |                  |                      |               |                |      1         |         |                    |                     |

    And I wait "/edm/purchase_order_oa_v1" by keyFields" Async Queue complete

    Given I import "/edm/material_global_v1" by keyFields "localMaterialNumber,sourceSystem"
      | baseUom | batchManageIndicator | brand | category | division | flagForDeletion | form | franchise | globalBusinessUnit | globalDpParentCode | localBaseUom | localDpParentCode | localManufacturingTechnology | localMaterialGroup | localMaterialNumber | localMaterialType |       localRefDescription                | manufacturingTechnology | materialGroup | materialNumber | materialStatus | materialType | minRemShelfLife | parentCode | primaryPlanningCode | productFamily | refDescription | sourceSystem | subBrand | totalShelfLife |
      |         |                      |       |          |    10    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         58752       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      58752     |        8       |              |       0         |            |        58752        |               |                |   CONS_LATAM |          |       0        |
      |         |                      |       |          |    11    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         80990       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      80990     |        8       |              |       365       |            |        80990        |               |                |   CONS_LATAM |          |       1825     |
      |         |                      |       |          |    10    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         57039       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      57039     |        8       |              |       120       |            |        57039        |               |                |   CONS_LATAM |          |       11       |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         96161       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      96161     |        9       |              |       11        |            |        96161        |               |                |   CONS_LATAM |          |       1        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         91732       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      91732     |        8       |              |       8         |            |        91732        |               |                |   CONS_LATAM |          |       2        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         60520       |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      60520     |        9       |              |       9         |            |        60520        |               |                |   CONS_LATAM |          |       6        |
      |         |                      |       |          |    13    |                 |      |           |                    |                    |     EA       |                   |                              |          80141605  |         528395      |      PROM         | TM-OLLA MULTIU. 7 TAZAS OSTER PAÃ‘ALERAS |                         |               |      528395    |        9       |              |                 |    9       |        528395       |               |                |   CONS_LATAM |          |       7        |

    And I wait "/edm/material_global_v1" Async Queue complete

    Given I import "/edm/plant_v1" by keyFields "localPlant,sourceSystem"
      | country | localCountry | localCurrency | localPlanningRelevant | localPlant |     localPlantName             | localPlantType | plant |        plantType        |         region        |      site      | sourceSystem |
      |    MX   |      MX      |       MX      |          X            |    MX01    | J&J Colombia - LADS (CO01)     |                |  MX01 | MP, Manufacturing Plant | MX                    | MX             |  CONS_LATAM  |
      |    BR   |      BR      |       BRL     |          X            |    BR14    | J&J Colombia - LADS (CO01)     |                |  BR14 | MP, Manufacturing Plant | CO, COLOMBIA COLOMBIA | Cali           |  CONS_LATAM  |
      |    BR   |      BR      |       BRL     |          X            |    BR12    | J&J BR-Nova Odessa - Com&Distr |       DC       |  BR12 | DC, Distribution Center | BR, BRAZIL BRAZIL     | Nova Odessa DC |  CONS_LATAM  |
      |    BR   |      BR      |       BRL     |          X            |    BR13    | J&J BR-Nova Odessa - Com&Distr |       DC       |  BR62 | DC, Distribution Center | BR, BRAZIL BRAZIL     | Nova Odessa DC |  CONS_LATAM  |

    And I wait "/edm/plant_v1" Async Queue complete

    Given I import "/plan/cns_material_plan_status" by keyFields "sourceSystem,localMaterialNumber,localPlant"
      | active | dpRelevant | localMaterialNumber |   localParentCode | localPlant | materialNumber | noPlanRelevant | parentActive |   ppc   | sourceSystem | spRelevant |
      |   X    |            |        58752        | 78910109411230000 |     MX01   |                |                |        X     | 58722   | CONS_LATAM   |     X      |
      |   X    |            |        97360        | 78910100877220000 |     CO13   |                |                |        X     | 97360   | CONS_LATAM   |     X      |
      |   X    |            |        57039        | 78910100877220000 |     BR14   |                |                |        X     | 57039   | CONS_LATAM   |     X      |
      |   X    |            |        80990        | 78910100877220000 |     BR12   |      80990     |        X       |        X     |         | CONS_LATAM   |            |
      |   X    |            |        96161        | 78910100877220000 |     BR12   |      1234      |        X       |        X     | 7867    | CONS_LATAM   |            |
      |   X    |            |        91732        | 78910100877220000 |     BR12   |                |        X       |        X     | 91732   | CONS_LATAM   |            |
      |   X    |            |        60520        | 78910100877220000 |     BR13   |      60520     |        X       |        X     |         | CONS_LATAM   |            |
      |   X    |            |        528395       | 78910100877220000 |     BR12   |                |        X       |        X     | 528395  | CONS_LATAM   |            |


    And I wait "/plan/cns_material_plan_status" Async Queue complete

    Given I import "/plan/cns_plan_object_filter" by keyFields "sourceObjectAttribute1,sourceObjectAttribute1,sourceObjectAttribute2,sourceObjectAttribute2Value,sourceObjectTechName,sourceSystem"
     | comments | inclusionExclusion | sourceObjectAttribute1 | sourceObjectAttribute1Value | sourceObjectAttribute2 | sourceObjectAttribute2Value | sourceObjectTechName | sourceSystem |
     |          |        I           |        plntCd          |              DO01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              AR01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              PA03           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              MX01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              PA01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR19           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              PE01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CR01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              AR01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CO02           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR14           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              EC01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              MX01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              AR01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CR01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              EC01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              PA01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR16           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              UY01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              UY01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR07           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              PA01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CL01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              UY01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CO01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              DO01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR16           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              PE01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              GT01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              PA03           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CR01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CR01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR19           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CO01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              DO01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              MX02           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              DO01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              PE01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR25           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CL01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR16           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              GT01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              PA03           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR25           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              MX01           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              GT02           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CO02           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              UY01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR07           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              MX02           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CL01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CL01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              GT01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              MX02           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR25           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CR02           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CO01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CR02           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              AR02           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              AR02           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CR02           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              EC01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              GT02           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CO01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              AR02           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR07           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR07           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CR02           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              MX01           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              AR02           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              AR01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              EC01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              GT02           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              GT02           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR25           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              PA01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR16           |          poTypeCd      |             ZNB             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR12           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              CO02           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              MX02           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              GT01           |          poTypeCd      |             NB              |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              BR19           |          poTypeCd      |             ZLA             |   purchase_order_oa  |   CONS_latam |
     |          |        I           |        plntCd          |              PE01           |          poTypeCd      |             UB              |   purchase_order_oa  |   CONS_latam |


    And I wait "/plan/cns_plan_object_filter" Async Queue complete

    Given I import "/plan/cns_spl_pln_loc" by keyFields "localNumber,vendorOrCustomer,sourceSystem,localPlant"
    | localCountry | localCurrency |             localName               | localNumber | localPlant | localRegion | pLanlocTypeDesc | pLanlocTypeId |      planLocTypeDesc      | planLocTypeId | sourceSystem | specLocAtt1 | specLocAtt2 | specLocAtt3 | specLocAttDesc1 | specLocAttDesc2 | specLocAttDesc3 | vendorOrCustomer | vendororCustomer |
    |     BR       |     BRL       | SUPPORT PACK IND E COM LTDA         |     1189    |     BR12   |    103      |                 |               | Mfg Plant Copacker        |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     EC       |     USE       | LODISAL S.A.                        |     52839 5 |     BR12   |    103      |                 |               | Affiliate/Market Copacker |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     US       |               | JOHNSON & JOHNSON CONSUMER INC.     |     50161   |            |    101      |                 |               | Ext Manufacturer FG       |     VENDOR    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     UY       |     UYU       | MODYLER SA                          |     65659   |     UY01   |    103      |                 |               | Affiliate/Market Copacker |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     GT       |     GTQ       | DHL GLOBAL FORWARDING (GUATEMALA)   |     36191   |     GT01   |    103      |                 |               | Affiliate/Market Copacker |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     CO       |     COP       | SUPPLA SA                           |     44776   |     CO01   |    103      |                 |               | Mfg Plant Copacker        |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     CL       |     CLP       | Apl Logistics Chile S.A.            |     79232   |     BR14   |    103      |                 |               | Affiliate/Market Copacker |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     DO       |     DOP       | YOBEL SRL? ? ? ? ? ? ? ?            |     34427   |     DO01   |    103      |                 |               | Affiliate/Market Copacker |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     MX       |     MXN       | AVP MAQUILA DE MEXICO S DE RL DE CV |     86017   |     MX02   |    103      |                 |               | Affiliate/Market Copacker |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     CO       |     COP       | ASPRILLA ORTIZ FABIO                |     15574   |     CO01   |    103      |                 |               | Mfg Plant Copacker        |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     CR       |     CRC       | D.H.L. COSTA RICA (CORMAR) S.A.     |     36328   |     CR01   |    103      |                 |               | Affiliate/Market Copacker |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     MX       |     MXN       | CILAG AG INTERNATIONAL              |     6109    |     MX01   |    104      |                 |               | Ext Manufacturer FG       |     VENDOR    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     PA       |     USD       | J CAIN & CO                         |     36124   |     PA03   |    103      |                 |               | Affiliate/Market Copacker |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |
    |     PE       |     USD       | YOBEL SUPPLY CHAIN MANAGEMENT S.A.  |     20667   |     PE01   |    103      |                 |               | Affiliate/Market Copacker |     SUBCON    | CONS_LATAM   |             |             |             |                 |                 |                 |        V         |                  |


    And I wait "/plan/cns_spl_pln_loc" Async Queue complete

    When I submit task with xml file "xml/omp/GDMStockPurchaseOrder_aggr.xml"

    When I submit task with xml file "xml/omp/OMPGdmSupply.xml" and execute file "jar/pangea-view.jar"

    Then A file is found on sink application with name "GDMStock.tsv"

    And I check file data for filename "GDMStock.tsv" by keyFields ""
      |                StockId                | Active | ActiveOPRERP | ActiveSOPERP | BatchId | BlockedQuantity | Consignment | CertaintyID | ERPOrderId |         InventoryLinkGroupId          |        LIFNR      |    LocationId   |                  ProcessId                       |    ProcessTypeId  | ProductId | QualityQuantity | Quantity |       ReceiptDate   | RestrictedQuantity | ReturnsQuantity |        StartDate    | StockType | TransferQuantity |      TransitDate    | UnrestrictedQuantity |
      | 58752/CONS_LATAM_MX02/3000793997/10/1 |   YES  |      YES     |      NO      |         |      0.0        |      YES    |      BE     | 3000793997 |                                       | CONS_LATAM_V_6109 | CONS_LATAM_MX01 | TR/58752/CONS_LATAM_MX01/CONS_LATAM_MX01/Default | VendorTransport   |    58752  |       0.0       |  984.00  | 2017/01/03 00:00:00 |        0.0         |         0.0     | 2017/01/04 00:0i:00 | movement  |        0.0       | 1980/01/01 00:00:00 | 0.0                  |
      | 58752/CONS_LATAM_MX02/3000793997/20/1 |   YES  |      YES     |      NO      |         |      0.0        |      YES    |      BE     | 3000793997 |                                       | CONS_LATAM_V_6109 | CONS_LATAM_MX01 | TR/58752/CONS_LATAM_MX01/CONS_LATAM_MX01/Default | VendorTransport   |    58752  |       0.0       |  1800.00 | 2017/01/03 00:00:00 |        0.0         |         0.0     | 2017/01/04 00:0i:00 | movement  |        0.0       | 1980/01/01 00:00:00 | 0.0                  |
      | 58752/CONS_LATAM_MX02/3000793997/11/1 |   YES  |      YES     |      NO      |         |      0.0        |      YES    |      BE     | 3000793997 |                                       | CONS_LATAM_V_6109 | CONS_LATAM_MX01 | TR/58752/CONS_LATAM_MX01/CONS_LATAM_MX01/Default | VendorTransport   |    58752  |       0.0       |  1500.00 | 2017/01/03 00:00:00 |        0.0         |         0.0     | 2017/01/04 00:0i:00 | movement  |        0.0       | 1980/01/01 00:00:00 | 0.0                  |
      | 80990/CONS_LATAM_BR12/3000793998/20   |   YES  |      YES     |      NO      |         |      0.0        |      YES    |      LE     | 3000793998 | 80990/CONS_LATAM_BR12/3000793999/20/1 | CONS_LATAM_V_1189 | CONS_LATAM_BR12 | TR/80990/CONS_LATAM_BR12/CONS_LATAM_BR12/Default | ExternalTransport |    80990  |       0.0       |  2100.00 | 2017/01/03 00:00:00 |        0.0         |         0.0     | 2017/01/04 00:0i:00 | movement  |        0.0       | 1980/01/01 00:00:00 | 0.0                  |
      | 528395/CONS_LATAM_BR12/3000793995/20  |   YES  |      YES     |      NO      |         |      0.0        |      YES    |      LE     | 3000793995 | 528395/CONS_LATAM_BR12/3000793995/20/1| CONS_LATAM_V_1189 | CONS_LATAM_BR12 | TR/528395/CONS_LATAM_BR12/CONS_LATAM_BR12/Default| ExternalTransport |    528395 |       0.0       |  900.00  | 2017/01/03 00:00:00 |        0.0         |         0.0     | 2017/01/04 00:0i:00 | movement  |        0.0       | 1980/01/01 00:00:00 | 0.0                  |
      | 57039/CONS_LATAM_BR14/3000793990/20   |   YES  |      YES     |      NO      |         |      0.0        |      YES    |      LE     | 3000793990 | 57039/CONS_LATAM_BR14/3000793990/20/1 | CONS_LATAM_V_79232| CONS_LATAM_BR14 | SU/557039/CONS_LATAM_BR14/79232/Default          | InternalTransport |    57039  |       0.0       |  1800.00 | 2017/01/03 00:00:00 |        0.0         |         0.0     | 2017/01/04 00:0i:00 | movement  |        0.0       | 1980/01/01 00:00:00 | 0.0                  |
      | 58752/CONS_LATAM_MX02/3000793997/40   |   YES  |      YES     |      NO      |         |      0.0        |      YES    |      BE     | 3000793997 | 58752/CONS_LATAM_MX02/3000793997/40/1 | CONS_LATAM_V_6109 | CONS_LATAM_MX01 | TR/58752/CONS_LATAM_MX01/CONS_LATAM_MX01/Default | VendorTransport   |    58752  |       0.0       |  1800.00 | 2017/01/03 00:00:00 |        0.0         |         0.0     | 2017/01/04 00:0i:00 | movement  |        0.0       | 1980/01/01 00:00:00 | 0.0                  |



    And I will remove all data with region "/edm/purchase_order_oa_v1"

    And I will remove all data with region "/edm/material_global_v1"

    And I will remove all data with region "/edm/plant_v1"

    And I will remove all data with region "/plan/cns_material_plan_status"


    And I will remove all data with region "/plan/cns_spl_pln_loc"

    And I will remove the test file on sink application "GDMStock.tsv"

